SMACC: sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace Class Reference
sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace Class Reference
#include <cp_constraint_lateral_workspace.h>
Public Member Functions
void enable ()
void disable ()
CpConstraintLateralWorkspace (std::string referenceFrame, float lateralDistance, geometry_msgs::Vector3 size, geometry_msgs::Vector3 offset=geometry_msgs::Vector3())
virtual void onInitialize () override
virtual void update ()
void createCollisionBox (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject &collision, const ros::Time &time, int addOrRemove)
void createVirtualCollisionWalls (std::vector< moveit_msgs::CollisionObject > &collisions, const ros::Time &time, int addOrRemove)
Public Member Functions inherited from smacc::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Member Functions inherited from smacc::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (ros::Duration duration)
void executeUpdate ()
void setUpdatePeriod (ros::Duration duration)
Private Attributes
moveit::planning_interface::PlanningSceneInterface * planningSceneInterface_
::cl_move_group_interface::ClMoveGroup * movegroupclient_
std::string referenceFrame_
float lateralDistance_
geometry_msgs::Vector3 offset_
geometry_msgs::Vector3 size_
bool enabled_ = true
bool alreadyRemoved_ = true
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccComponent
virtual void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
virtual void onInitialize ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
virtual void update ()=0
Protected Attributes inherited from smacc::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 13 of file cp_constraint_lateral_workspace.h.
Constructor & Destructor Documentation
CpConstraintLateralWorkspace()
sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::CpConstraintLateralWorkspace (std::string referenceFrame, float lateralDistance, geometry_msgs::Vector3 size, geometry_msgs::Vector3 offset = geometry_msgs::Vector3())
Definition at line 21 of file cp_constraint_lateral_workspace.cpp.
        {
            referenceFrame_ = referenceFrame;
            size_ = size;
            offset_ = offset;
            lateralDistance_ = lateralDistance;
            this->setUpdatePeriod(ros::Duration(10.0)); // do not update too much frequenfly since we have a relative collision
        }
References lateralDistance_, offset_, referenceFrame_, smacc::ISmaccUpdatable::setUpdatePeriod(), and size_.
Member Function Documentation
createCollisionBox()
void sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::createCollisionBox (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject & collision, const ros::Time & time, int addOrRemove)
Definition at line 56 of file cp_constraint_lateral_workspace.cpp.
        {
            collision.operation = addOrRemove;
            collision.id = id;
            collision.primitives.resize(1);
            collision.primitives[0].type = collision.primitives[0].BOX;
            collision.primitives[0].dimensions.resize(3);
            collision.primitives[0].dimensions[0] = xl;
            collision.primitives[0].dimensions[1] = yl;
            collision.primitives[0].dimensions[2] = zl;
            collision.primitive_poses.resize(1);
            collision.primitive_poses[0].position.x = x;
            collision.primitive_poses[0].position.y = y;
            collision.primitive_poses[0].position.z = z;
            collision.primitive_poses[0].orientation.w = 1.0;
            collision.header.frame_id = frameid;
            collision.header.stamp = time;
        }
Referenced by createVirtualCollisionWalls().
createVirtualCollisionWalls()
void sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::createVirtualCollisionWalls (std::vector< moveit_msgs::CollisionObject > & collisions, const ros::Time & time, int addOrRemove)
Definition at line 79 of file cp_constraint_lateral_workspace.cpp.
        {
            moveit_msgs::CollisionObject box;
            createCollisionBox(offset_.x, offset_.y - lateralDistance_, offset_.z, size_.x, size_.y, size_.z, "right", referenceFrame_, box, time, addOrRemove);
            collisions.push_back(box);
            createCollisionBox(offset_.x, offset_.y + lateralDistance_, offset_.z, size_.x, size_.y, size_.z, "left", referenceFrame_, box, time, addOrRemove);
            collisions.push_back(box);
        }
References createCollisionBox(), lateralDistance_, offset_, referenceFrame_, and size_.
Referenced by update().
disable()
void sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::disable ()
Definition at line 15 of file cp_constraint_lateral_workspace.cpp.
        {
            enabled_ = false;
            this->update();
        }
References enabled_, and update().
enable()
void sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::enable ()
Definition at line 8 of file cp_constraint_lateral_workspace.cpp.
        {
            enabled_ = true;
            alreadyRemoved_ = false;
            this->update();
        }
References alreadyRemoved_, enabled_, and update().
onInitialize()
void sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::onInitialize () override virtual
Reimplemented from smacc::ISmaccComponent.
Definition at line 30 of file cp_constraint_lateral_workspace.cpp.
        {
            this->requiresClient(movegroupclient_);
            planningSceneInterface_ = &movegroupclient_->planningSceneInterface;
        }
References movegroupclient_, cl_move_group_interface::ClMoveGroup::planningSceneInterface, planningSceneInterface_, and smacc::ISmaccComponent::requiresClient().
update()
void sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::update () virtual
Implements smacc::ISmaccUpdatable.
Definition at line 36 of file cp_constraint_lateral_workspace.cpp.
        {
            if (enabled_)
            {
                auto time = ros::Time::now();
                std::vector<moveit_msgs::CollisionObject> collisionObjects;
                createVirtualCollisionWalls(collisionObjects, time, moveit_msgs::CollisionObject::ADD);
                this->planningSceneInterface_->applyCollisionObjects(collisionObjects);
            }
            else if (alreadyRemoved_)
            {
                auto time = ros::Time::now();
                std::vector<moveit_msgs::CollisionObject> collisionObjects;
                createVirtualCollisionWalls(collisionObjects, time, moveit_msgs::CollisionObject::REMOVE);
                this->planningSceneInterface_->applyCollisionObjects(collisionObjects);
                alreadyRemoved_ = false;
            }
        }
References alreadyRemoved_, createVirtualCollisionWalls(), enabled_, and planningSceneInterface_.
Referenced by disable(), and enable().
Member Data Documentation
alreadyRemoved_
bool sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::alreadyRemoved_ = true private
Definition at line 24 of file cp_constraint_lateral_workspace.h.
Referenced by enable(), and update().
enabled_
bool sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::enabled_ = true private
Definition at line 23 of file cp_constraint_lateral_workspace.h.
Referenced by disable(), enable(), and update().
lateralDistance_
float sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::lateralDistance_ private
Definition at line 20 of file cp_constraint_lateral_workspace.h.
Referenced by CpConstraintLateralWorkspace(), and createVirtualCollisionWalls().
movegroupclient_
::cl_move_group_interface::ClMoveGroup* sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::movegroupclient_ private
Definition at line 17 of file cp_constraint_lateral_workspace.h.
Referenced by onInitialize().
offset_
geometry_msgs::Vector3 sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::offset_ private
Definition at line 21 of file cp_constraint_lateral_workspace.h.
Referenced by CpConstraintLateralWorkspace(), and createVirtualCollisionWalls().
planningSceneInterface_
moveit::planning_interface::PlanningSceneInterface* sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::planningSceneInterface_ private
Definition at line 16 of file cp_constraint_lateral_workspace.h.
Referenced by onInitialize(), and update().
referenceFrame_
std::string sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::referenceFrame_ private
Definition at line 19 of file cp_constraint_lateral_workspace.h.
Referenced by CpConstraintLateralWorkspace(), and createVirtualCollisionWalls().
size_
geometry_msgs::Vector3 sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintLateralWorkspace::size_ private
Definition at line 22 of file cp_constraint_lateral_workspace.h.
Referenced by CpConstraintLateralWorkspace(), and createVirtualCollisionWalls().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_fetch_six_table_pick_n_sort_1/include/sm_fetch_six_table_pick_n_sort_1/clients/move_group_interface_client/components/cp_constraint_lateral_workspace.h
smacc_sm_reference_library/sm_fetch_six_table_pick_n_sort_1/src/sm_fetch_six_table_pick_n_sort_1/clients/move_group_interface_client/components/cp_constraint_lateral_workspace.cpp