SMACC: smacc::SmaccEventGenerator Class Reference
smacc::SmaccEventGenerator Class Reference
#include <smacc_event_generator.h>
Public Member Functions
SmaccEventGenerator ()
virtual ~SmaccEventGenerator ()
template<typename TState , typename TSource >
void onStateAllocation ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
void initialize (ISmaccState *ownerState)
virtual void onInitialized ()
Private Attributes
ISmaccState * ownerState_
friend ISmaccStateMachine
Detailed Description
Definition at line 22 of file smacc_event_generator.h.
Constructor & Destructor Documentation
SmaccEventGenerator()
smacc::SmaccEventGenerator::SmaccEventGenerator ()
Definition at line 12 of file smacc_event_generator.cpp.
    {
    }
~SmaccEventGenerator()
smacc::SmaccEventGenerator::~SmaccEventGenerator () virtual
Definition at line 16 of file smacc_event_generator.cpp.
    {
    }
Member Function Documentation
initialize()
void smacc::SmaccEventGenerator::initialize (smacc::ISmaccState * ownerState)
Definition at line 28 of file smacc_event_generator.cpp.
    {
        this->ownerState_ = ownerState;
        this->onInitialized();
    }
References onInitialized(), and ownerState_.
onEntry()
void smacc::SmaccEventGenerator::onEntry () virtual
Reimplemented in smacc::event_generators::EgConditionalGenerator, and smacc::state_reactors::EgRandomGenerator.
Definition at line 20 of file smacc_event_generator.cpp.
    {
    }
onExit()
void smacc::SmaccEventGenerator::onExit () virtual
Definition at line 24 of file smacc_event_generator.cpp.
    {
    }
onInitialized()
void smacc::SmaccEventGenerator::onInitialized () virtual
Definition at line 34 of file smacc_event_generator.cpp.
    {
    }
Referenced by initialize().
onStateAllocation()
template<typename TState , typename TSource > void smacc::SmaccEventGenerator::onStateAllocation
Definition at line 26 of file smacc_event_generator_impl.h.
    {
    }
postEvent() [1/2]
template<typename EventType > void smacc::SmaccEventGenerator::postEvent
Definition at line 20 of file smacc_event_generator_impl.h.
    {
        ownerState_->postEvent<EventType>();
    }
References ownerState_, and smacc::ISmaccState::postEvent().
postEvent() [2/2]
template<typename EventType > void smacc::SmaccEventGenerator::postEvent (const EventType & ev)
Definition at line 14 of file smacc_event_generator_impl.h.
    {
        ownerState_->postEvent(ev);
    }
References ownerState_, and smacc::ISmaccState::postEvent().
Member Data Documentation
ISmaccStateMachine
friend smacc::SmaccEventGenerator::ISmaccStateMachine private
Definition at line 45 of file smacc_event_generator.h.
ownerState_
ISmaccState* smacc::SmaccEventGenerator::ownerState_ private
Definition at line 44 of file smacc_event_generator.h.
Referenced by initialize(), and postEvent().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_event_generator.h
smacc/include/smacc/impl/smacc_event_generator_impl.h
smacc/src/smacc/smacc_event_generator.cpp