SMACC: cl_move_group_interface::CbMoveEndEffectorRelative Class Reference
cl_move_group_interface::CbMoveEndEffectorRelative Class Reference
#include <cb_move_end_effector_relative.h>
Public Member Functions
CbMoveEndEffectorRelative ()
CbMoveEndEffectorRelative (geometry_msgs::Transform transform)
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Public Attributes
geometry_msgs::Transform transform_
boost::optional< std::string > group_
Protected Member Functions
void moveRelative (moveit::planning_interface::MoveGroupInterface &moveGroupinterface, geometry_msgs::Transform &transformOffset)
Protected Member Functions inherited from smacc::SmaccAsyncClientBehavior
virtual void executeOnEntry () override
virtual void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Protected Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 14 of file cb_move_end_effector_relative.h.
Constructor & Destructor Documentation
CbMoveEndEffectorRelative() [1/2]
cl_move_group_interface::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative ()
Definition at line 14 of file cb_move_end_effector_relative.cpp.
    {
        transform_.rotation.w = 1;
    }
References transform_.
CbMoveEndEffectorRelative() [2/2]
cl_move_group_interface::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative (geometry_msgs::Transform transform)
Definition at line 19 of file cb_move_end_effector_relative.cpp.
    {
    }
Member Function Documentation
moveRelative()
void cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative (moveit::planning_interface::MoveGroupInterface & moveGroupinterface, geometry_msgs::Transform & transformOffset) protected
Definition at line 44 of file cb_move_end_effector_relative.cpp.
    {
        auto referenceStartPose = moveGroupInterface.getCurrentPose();
        tf::Quaternion currentOrientation;
        tf::quaternionMsgToTF(referenceStartPose.pose.orientation, currentOrientation);
        tf::Quaternion desiredRelativeRotation;
        tf::quaternionMsgToTF(transformOffset.rotation, desiredRelativeRotation);
        auto targetOrientation = desiredRelativeRotation * currentOrientation;
        geometry_msgs::PoseStamped targetObjectPose = referenceStartPose;
        tf::quaternionTFToMsg(targetOrientation, targetObjectPose.pose.orientation);
        targetObjectPose.pose.position.x += transformOffset.translation.x;
        targetObjectPose.pose.position.y += transformOffset.translation.y;
        targetObjectPose.pose.position.z += transformOffset.translation.z;
        moveGroupInterface.setPlanningTime(1.0);
        ROS_INFO_STREAM("[CbMoveEndEffectorRelative] Target End efector Pose: " << targetObjectPose);
        moveGroupInterface.setPoseTarget(targetObjectPose);
        moveGroupInterface.setPoseReferenceFrame("map");
        moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
        bool success = (moveGroupInterface.plan(computedMotionPlan) == moveit::planning_interface::MoveItErrorCode::SUCCESS);
        ROS_INFO_NAMED("CbMoveEndEffectorRelative", "Success Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED");
        if (success)
        {
            auto executionResult = moveGroupInterface.execute(computedMotionPlan);
            if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
            {
                ROS_INFO("[CbMoveEndEffectorRelative] motion execution succeeded");
                movegroupClient_->postEventMotionExecutionSucceded();
                this->postSuccessEvent();
            }
            else
            {
                moveGroupInterface.setPoseTarget(referenceStartPose); // undo to avoid abort-repeat state issues with this relative motion
                ROS_INFO("[CbMoveEndEffectorRelative] motion execution failed");
                movegroupClient_->postEventMotionExecutionFailed();
                this->postFailureEvent();
            }
        }
        else
        {
            moveGroupInterface.setPoseTarget(referenceStartPose); //undo since we did not executed the motion
            ROS_INFO("[CbMoveEndEffectorRelative] motion execution failed");
            movegroupClient_->postEventMotionExecutionFailed();
            this->postFailureEvent();
        }
    }
References movegroupClient_, cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded(), smacc::SmaccAsyncClientBehavior::postFailureEvent(), and smacc::SmaccAsyncClientBehavior::postSuccessEvent().
Referenced by onEntry().
onEntry()
void cl_move_group_interface::CbMoveEndEffectorRelative::onEntry () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 23 of file cb_move_end_effector_relative.cpp.
    {
        ROS_INFO_STREAM("[CbMoveEndEffectorRelative] Transform end effector pose relative: " << transform_);
        this->requiresClient(movegroupClient_);
        if (this->group_)
        {
            moveit::planning_interface::MoveGroupInterface move_group(*(this->group_));
            this->moveRelative(move_group, this->transform_);
        }
        else
        {
            this->moveRelative(movegroupClient_->moveGroupClientInterface, this->transform_);
        }
    }
References group_, movegroupClient_, cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, moveRelative(), smacc::ISmaccClientBehavior::requiresClient(), and transform_.
onExit()
void cl_move_group_interface::CbMoveEndEffectorRelative::onExit () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 40 of file cb_move_end_effector_relative.cpp.
    {
    }
Member Data Documentation
group_
boost::optional<std::string> cl_move_group_interface::CbMoveEndEffectorRelative::group_
Definition at line 19 of file cb_move_end_effector_relative.h.
Referenced by onEntry().
movegroupClient_
ClMoveGroup* cl_move_group_interface::CbMoveEndEffectorRelative::movegroupClient_ protected
Definition at line 33 of file cb_move_end_effector_relative.h.
Referenced by moveRelative(), and onEntry().
transform_
geometry_msgs::Transform cl_move_group_interface::CbMoveEndEffectorRelative::transform_
Definition at line 17 of file cb_move_end_effector_relative.h.
Referenced by CbMoveEndEffectorRelative(), and onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_end_effector_relative.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_end_effector_relative.cpp