SMACC: sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces Class Reference
sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces Class Reference
#include <cp_constraint_tables_workspaces.h>
Public Member Functions
void setBigTableCollisionVolume ()
void setSmallTableCollisionVolume ()
void disableTableCollisionVolume ()
virtual void onInitialize () override
virtual void update ()
Public Member Functions inherited from smacc::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Member Functions inherited from smacc::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (ros::Duration duration)
void executeUpdate ()
void setUpdatePeriod (ros::Duration duration)
Private Attributes
moveit::planning_interface::PlanningSceneInterface * planningSceneInterface_
CpSceneState * sceneState_
double safeTableHeightOffsetForCubeCollisions = 0
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccComponent
virtual void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
virtual void onInitialize ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
virtual void update ()=0
Protected Attributes inherited from smacc::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 15 of file cp_constraint_tables_workspaces.h.
Member Function Documentation
disableTableCollisionVolume()
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::disableTableCollisionVolume ()
Definition at line 19 of file cp_constraint_tables_workspaces.cpp.
        {
            safeTableHeightOffsetForCubeCollisions = -1;
            this->update();
        }
References safeTableHeightOffsetForCubeCollisions, and update().
onInitialize()
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::onInitialize () override virtual
Reimplemented from smacc::ISmaccComponent.
Definition at line 25 of file cp_constraint_tables_workspaces.cpp.
        {
            ClMoveGroup *movegroupclient;
            this->requiresClient(movegroupclient);
            planningSceneInterface_ = &movegroupclient->planningSceneInterface;
            ClPerceptionSystem *perceptionSystem;
            this->requiresClient(perceptionSystem);
            sceneState_ = perceptionSystem->sceneState_;
        }
References planningSceneInterface_, smacc::ISmaccComponent::requiresClient(), sceneState_, and sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::sceneState_.
setBigTableCollisionVolume()
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::setBigTableCollisionVolume ()
Definition at line 7 of file cp_constraint_tables_workspaces.cpp.
        {
            safeTableHeightOffsetForCubeCollisions = 0.17;
            this->update();
        }
References safeTableHeightOffsetForCubeCollisions, and update().
setSmallTableCollisionVolume()
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::setSmallTableCollisionVolume ()
Definition at line 13 of file cp_constraint_tables_workspaces.cpp.
        {
            safeTableHeightOffsetForCubeCollisions = 0;
            this->update();
        }
References safeTableHeightOffsetForCubeCollisions, and update().
update()
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::update () virtual
Implements smacc::ISmaccUpdatable.
Definition at line 37 of file cp_constraint_tables_workspaces.cpp.
        {
            std::vector<moveit_msgs::CollisionObject> collisionObjects(this->sceneState_->tablesInfo_.size());
            if (safeTableHeightOffsetForCubeCollisions != -1)
            {
                auto thickness = 0.12;
                int i = 0;
                for (auto &table : this->sceneState_->tablesInfo_)
                {
                    auto tablepose = table.pose_->toPoseStampedMsg();
                    std::string tablename = "table_" + std::to_string(i + 1);
                    //removeCollisionObjectNames[i] = tablename;
                    moveit_msgs::CollisionObject &collision = collisionObjects[i];
                    collision.operation = moveit_msgs::CollisionObject::ADD;
                    collision.id = tablename;
                    collision.primitives.resize(1);
                    collision.primitives[0].type = collision.primitives[0].BOX;
                    collision.primitives[0].dimensions.resize(3);
                    collision.primitives[0].dimensions[0] = 1.05;
                    collision.primitives[0].dimensions[1] = 1.4;
                    collision.primitives[0].dimensions[2] = 0.001 + thickness + safeTableHeightOffsetForCubeCollisions;
                    /* Define the pose of the table. */
                    collision.primitive_poses.resize(1);
                    collision.primitive_poses[0].position.x = tablepose.pose.position.x;
                    collision.primitive_poses[0].position.y = tablepose.pose.position.y;
                    collision.primitive_poses[0].position.z = 0.7 - thickness * 0.5;
                    collision.primitive_poses[0].orientation.w = 1.0;
                    collision.header.frame_id = tablepose.header.frame_id;
                    collision.header.stamp = tablepose.header.stamp;
                    i++;
                }
                this->planningSceneInterface_->applyCollisionObjects(collisionObjects);
            }
            else
            {
                int i = 0;
                std::vector<std::string> disableNames;
                for (auto &table : this->sceneState_->tablesInfo_)
                {
                    auto tablepose = table.pose_->toPoseStampedMsg();
                    std::string tablename = "table_" + std::to_string(i + 1);
                    disableNames.push_back(tablename);
                    i++;
                }
                this->planningSceneInterface_->removeCollisionObjects(disableNames);
            }
        }
References planningSceneInterface_, safeTableHeightOffsetForCubeCollisions, sceneState_, and sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSceneState::tablesInfo_.
Referenced by disableTableCollisionVolume(), setBigTableCollisionVolume(), and setSmallTableCollisionVolume().
Member Data Documentation
planningSceneInterface_
moveit::planning_interface::PlanningSceneInterface* sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::planningSceneInterface_ private
Definition at line 19 of file cp_constraint_tables_workspaces.h.
Referenced by onInitialize(), and update().
safeTableHeightOffsetForCubeCollisions
double sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::safeTableHeightOffsetForCubeCollisions = 0 private
Definition at line 23 of file cp_constraint_tables_workspaces.h.
Referenced by disableTableCollisionVolume(), setBigTableCollisionVolume(), setSmallTableCollisionVolume(), and update().
sceneState_
CpSceneState* sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintTableWorkspaces::sceneState_ private
Definition at line 22 of file cp_constraint_tables_workspaces.h.
Referenced by onInitialize(), and update().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/clients/move_group_interface_client/components/cp_constraint_tables_workspaces.h
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/src/sm_fetch_two_table_whiskey_pour/clients/move_group_interface_client/components/cp_constraint_tables_workspaces.cpp