SMACC: cl_multirole_sensor::ClMultiroleSensor< MessageType > Class Template Reference
cl_multirole_sensor::ClMultiroleSensor< MessageType > Class Template Reference
#include <cl_multirole_sensor.h>
Public Types
typedef MessageType TMessageType
Public Types inherited from smacc::client_bases::SmaccSubscriberClient< MessageType >
typedef MessageType TMessageType
Public Member Functions
ClMultiroleSensor ()
template<typename T >
boost::signals2::connection onMessageTimeout (void(T::*callback)(const ros::TimerEvent &), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void initialize () override
Public Member Functions inherited from smacc::client_bases::SmaccSubscriberClient< MessageType >
SmaccSubscriberClient ()
SmaccSubscriberClient (std::string topicname)
virtual ~SmaccSubscriberClient ()
template<typename T >
boost::signals2::connection onMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename T >
boost::signals2::connection onFirstMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void initialize ()
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Public Attributes
SmaccSignal< void(const ros::TimerEvent &)> onMessageTimeout_
std::function< void(const ros::TimerEvent &ev)> postTimeoutMessageEvent
boost::optional< ros::Duration > timeout_
Public Attributes inherited from smacc::client_bases::SmaccSubscriberClient< MessageType >
boost::optional< std::string > topicName
boost::optional< int > queueSize
smacc::SmaccSignal< void(const MessageType &)> onFirstMessageReceived_
smacc::SmaccSignal< void(const MessageType &)> onMessageReceived_
std::function< void(const MessageType &)> postMessageEvent
std::function< void(const MessageType &)> postInitialMessageEvent
Protected Member Functions
void resetTimer (const MessageType &msg)
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Private Member Functions
void timeoutCallback (const ros::TimerEvent &timerdata)
Private Attributes
ros::Timer timeoutTimer_
bool initialized_
Additional Inherited Members
Protected Attributes inherited from smacc::client_bases::SmaccSubscriberClient< MessageType >
ros::NodeHandle nh_
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Detailed Description
template<typename MessageType>
class cl_multirole_sensor::ClMultiroleSensor< MessageType >
Definition at line 25 of file cl_multirole_sensor.h.
Member Typedef Documentation
TMessageType
template<typename MessageType > typedef MessageType cl_multirole_sensor::ClMultiroleSensor< MessageType >::TMessageType
Definition at line 28 of file cl_multirole_sensor.h.
Constructor & Destructor Documentation
ClMultiroleSensor()
template<typename MessageType > cl_multirole_sensor::ClMultiroleSensor< MessageType >::ClMultiroleSensor () inline
Definition at line 31 of file cl_multirole_sensor.h.
      : smacc::client_bases::SmaccSubscriberClient<MessageType>()
  {
    ROS_INFO("[ClMultiroleSensor] constructor");
    initialized_ = false;
  }
References cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialized_.
Member Function Documentation
initialize()
template<typename MessageType > virtual void cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialize () inline override virtual
Reimplemented from smacc::client_bases::SmaccSubscriberClient< MessageType >.
Definition at line 60 of file cl_multirole_sensor.h.
  {
    if (!initialized_)
    {
      SmaccSubscriberClient<MessageType>::initialize();
      this->onMessageReceived(&ClMultiroleSensor<MessageType>::resetTimer, this);
      if (timeout_)
      {
        timeoutTimer_ = this->nh_.createTimer(*timeout_, boost::bind(&ClMultiroleSensor<MessageType>::timeoutCallback, this, _1));
        timeoutTimer_.start();
      }
      else
      {
        ROS_WARN("Timeout sensor client not set, skipping timeout watchdog funcionality");
      }
      initialized_ = true;
    }
  }
References smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialized_, smacc::client_bases::SmaccSubscriberClient< MessageType >::nh_, smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeout_, and cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutTimer_.
onMessageTimeout()
template<typename MessageType > template<typename T > boost::signals2::connection cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout (void(T::*)(const ros::TimerEvent &) callback, T * object) inline
Definition at line 39 of file cl_multirole_sensor.h.
  {
    return this->getStateMachine()->createSignalConnection(onMessageTimeout_, callback, object);
  }
References callback(), smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onOrthogonalAllocation()
template<typename MessageType > template<typename TOrthogonal , typename TSourceObject > void cl_multirole_sensor::ClMultiroleSensor< MessageType >::onOrthogonalAllocation () inline
Definition at line 47 of file cl_multirole_sensor.h.
  {
    SmaccSubscriberClient<MessageType>::template onOrthogonalAllocation<TOrthogonal, TSourceObject>();
    this->postTimeoutMessageEvent = [=](auto &timerdata) {
      onMessageTimeout_(timerdata);
      auto event = new EvTopicMessageTimeout<TSourceObject, TOrthogonal>();
      event->timerData = timerdata;
      this->postEvent(event);
    };
  }
References cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout_, and smacc::ISmaccClient::postEvent().
resetTimer()
template<typename MessageType > void cl_multirole_sensor::ClMultiroleSensor< MessageType >::resetTimer (const MessageType & msg) inline protected
Definition at line 85 of file cl_multirole_sensor.h.
  {
    //resetting the timer
    this->timeoutTimer_.stop();
    this->timeoutTimer_.start();
  }
References cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutTimer_.
timeoutCallback()
template<typename MessageType > void cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutCallback (const ros::TimerEvent & timerdata) inline private
Definition at line 96 of file cl_multirole_sensor.h.
  {
    postTimeoutMessageEvent(timerdata);
  }
References cl_multirole_sensor::ClMultiroleSensor< MessageType >::postTimeoutMessageEvent.
Member Data Documentation
initialized_
template<typename MessageType > bool cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialized_ private
Definition at line 94 of file cl_multirole_sensor.h.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::ClMultiroleSensor(), and cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialize().
onMessageTimeout_
template<typename MessageType > SmaccSignal<void(const ros::TimerEvent &)> cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout_
Definition at line 29 of file cl_multirole_sensor.h.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::onOrthogonalAllocation().
postTimeoutMessageEvent
template<typename MessageType > std::function<void(const ros::TimerEvent &ev)> cl_multirole_sensor::ClMultiroleSensor< MessageType >::postTimeoutMessageEvent
Definition at line 44 of file cl_multirole_sensor.h.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutCallback().
timeout_
template<typename MessageType > boost::optional<ros::Duration> cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeout_
Definition at line 82 of file cl_multirole_sensor.h.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialize().
timeoutTimer_
template<typename MessageType > ros::Timer cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutTimer_ private
Definition at line 93 of file cl_multirole_sensor.h.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialize(), and cl_multirole_sensor::ClMultiroleSensor< MessageType >::resetTimer().
The documentation for this class was generated from the following file:
smacc_client_library/multirole_sensor_client/include/multirole_sensor_client/cl_multirole_sensor.h