SMACC: sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall Class Reference
sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall Class Reference
#include <cp_constraint_virtual_side_wall.h>
Public Member Functions
void enable ()
void disable ()
CpConstraintVirtualSideWall (std::string name, std::string referenceFrame, geometry_msgs::Vector3 size, geometry_msgs::Vector3 offset=geometry_msgs::Vector3())
virtual void onInitialize () override
virtual void update ()
void createCollisionBox (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject &collision, const ros::Time &time, int addOrRemove)
void createVirtualCollisionWalls (std::vector< moveit_msgs::CollisionObject > &collisions, const ros::Time &time, int addOrRemove)
void enable ()
void disable ()
CpConstraintVirtualSideWall (std::string referenceFrame, geometry_msgs::Vector3 size, geometry_msgs::Vector3 offset=geometry_msgs::Vector3())
virtual void onInitialize () override
virtual void update ()
void createCollisionBox (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject &collision, const ros::Time &time, int addOrRemove)
void createVirtualCollisionWalls (std::vector< moveit_msgs::CollisionObject > &collisions, const ros::Time &time, int addOrRemove)
Public Member Functions inherited from smacc::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Member Functions inherited from smacc::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (ros::Duration duration)
void executeUpdate ()
void setUpdatePeriod (ros::Duration duration)
Private Attributes
moveit::planning_interface::PlanningSceneInterface * planningSceneInterface_
::cl_move_group_interface::ClMoveGroup * movegroupclient_
std::string name_
std::string referenceFrame_
geometry_msgs::Vector3 offset_
geometry_msgs::Vector3 size_
bool enabled_ = true
bool alreadyRemoved_ = true
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccComponent
virtual void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
virtual void onInitialize ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
virtual void update ()=0
Protected Attributes inherited from smacc::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 12 of file cp_constraint_virtual_side_wall.h.
Constructor & Destructor Documentation
CpConstraintVirtualSideWall() [1/2]
sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::CpConstraintVirtualSideWall (std::string name, std::string referenceFrame, geometry_msgs::Vector3 size, geometry_msgs::Vector3 offset = geometry_msgs::Vector3())
Definition at line 22 of file cp_constraint_virtual_side_wall.cpp.
        {
            name_= name;
            referenceFrame_ = referenceFrame;
            size_ = size;
            offset_ = offset;
            this->setUpdatePeriod(ros::Duration(10.0)); // do not update too much frequenfly since we have a relative collision
        }
References name_, offset_, referenceFrame_, smacc::ISmaccUpdatable::setUpdatePeriod(), and size_.
CpConstraintVirtualSideWall() [2/2]
sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::CpConstraintVirtualSideWall (std::string referenceFrame, geometry_msgs::Vector3 size, geometry_msgs::Vector3 offset = geometry_msgs::Vector3())
Member Function Documentation
createCollisionBox() [1/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::createCollisionBox (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject & collision, const ros::Time & time, int addOrRemove)
Definition at line 57 of file cp_constraint_virtual_side_wall.cpp.
        {
            collision.operation = addOrRemove;
            collision.id = id;
            collision.primitives.resize(1);
            collision.primitives[0].type = collision.primitives[0].BOX;
            collision.primitives[0].dimensions.resize(3);
            collision.primitives[0].dimensions[0] = xl;
            collision.primitives[0].dimensions[1] = yl;
            collision.primitives[0].dimensions[2] = zl;
            collision.primitive_poses.resize(1);
            collision.primitive_poses[0].position.x = x;
            collision.primitive_poses[0].position.y = y;
            collision.primitive_poses[0].position.z = z;
            collision.primitive_poses[0].orientation.w = 1.0;
            collision.header.frame_id = frameid;
            collision.header.stamp = time;
        }
Referenced by createVirtualCollisionWalls().
createCollisionBox() [2/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::createCollisionBox (float x, float y, float z, float xl, float yl, float zl, std::string id, std::string frameid, moveit_msgs::CollisionObject & collision, const ros::Time & time, int addOrRemove)
createVirtualCollisionWalls() [1/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::createVirtualCollisionWalls (std::vector< moveit_msgs::CollisionObject > & collisions, const ros::Time & time, int addOrRemove)
Definition at line 80 of file cp_constraint_virtual_side_wall.cpp.
        {
            moveit_msgs::CollisionObject box;
            createCollisionBox(offset_.x, offset_.y , offset_.z, size_.x, size_.y, size_.z, name_, referenceFrame_, box, time, addOrRemove);
            collisions.push_back(box);
        }
References createCollisionBox(), name_, offset_, referenceFrame_, and size_.
Referenced by update().
createVirtualCollisionWalls() [2/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::createVirtualCollisionWalls (std::vector< moveit_msgs::CollisionObject > & collisions, const ros::Time & time, int addOrRemove)
disable() [1/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::disable ()
Definition at line 16 of file cp_constraint_virtual_side_wall.cpp.
        {
            enabled_ = false;
            this->update();
        }
References enabled_, and update().
Referenced by sm_fetch_two_table_whiskey_pour::pick_states::StGraspApproach::runtimeConfigure().
disable() [2/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::disable ()
enable() [1/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::enable ()
Definition at line 9 of file cp_constraint_virtual_side_wall.cpp.
        {
            enabled_ = true;
            alreadyRemoved_ = false;
            this->update();
        }
References alreadyRemoved_, enabled_, and update().
Referenced by sm_fetch_two_table_whiskey_pour::StPlaceRetreat::onExit().
enable() [2/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::enable ()
onInitialize() [1/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::onInitialize () override virtual
Reimplemented from smacc::ISmaccComponent.
Definition at line 31 of file cp_constraint_virtual_side_wall.cpp.
        {
            this->requiresClient(movegroupclient_);
            planningSceneInterface_ = &movegroupclient_->planningSceneInterface;
        }
References movegroupclient_, cl_move_group_interface::ClMoveGroup::planningSceneInterface, planningSceneInterface_, and smacc::ISmaccComponent::requiresClient().
onInitialize() [2/2]
virtual void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::onInitialize () override virtual
Reimplemented from smacc::ISmaccComponent.
update() [1/2]
void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::update () virtual
Implements smacc::ISmaccUpdatable.
Definition at line 37 of file cp_constraint_virtual_side_wall.cpp.
        {
            if (enabled_)
            {
                auto time = ros::Time::now();
                std::vector<moveit_msgs::CollisionObject> collisionObjects;
                createVirtualCollisionWalls(collisionObjects, time, moveit_msgs::CollisionObject::ADD);
                this->planningSceneInterface_->applyCollisionObjects(collisionObjects);
            }
            else if (alreadyRemoved_)
            {
                auto time = ros::Time::now();
                std::vector<moveit_msgs::CollisionObject> collisionObjects;
                createVirtualCollisionWalls(collisionObjects, time, moveit_msgs::CollisionObject::REMOVE);
                this->planningSceneInterface_->applyCollisionObjects(collisionObjects);
                alreadyRemoved_ = false;
            }
        }
References alreadyRemoved_, createVirtualCollisionWalls(), enabled_, and planningSceneInterface_.
Referenced by disable(), and enable().
update() [2/2]
virtual void sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::update () virtual
Implements smacc::ISmaccUpdatable.
Member Data Documentation
alreadyRemoved_
bool sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::alreadyRemoved_ = true private
Definition at line 23 of file cp_constraint_virtual_side_wall.h.
Referenced by enable(), and update().
enabled_
bool sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::enabled_ = true private
Definition at line 22 of file cp_constraint_virtual_side_wall.h.
Referenced by disable(), enable(), and update().
movegroupclient_
cl_move_group_interface::ClMoveGroup * sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::movegroupclient_ private
Definition at line 16 of file cp_constraint_virtual_side_wall.h.
Referenced by onInitialize().
name_
std::string sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::name_ private
Definition at line 18 of file cp_constraint_virtual_side_wall.h.
Referenced by CpConstraintVirtualSideWall(), and createVirtualCollisionWalls().
offset_
geometry_msgs::Vector3 sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::offset_ private
Definition at line 20 of file cp_constraint_virtual_side_wall.h.
Referenced by CpConstraintVirtualSideWall(), and createVirtualCollisionWalls().
planningSceneInterface_
moveit::planning_interface::PlanningSceneInterface * sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::planningSceneInterface_ private
Definition at line 15 of file cp_constraint_virtual_side_wall.h.
Referenced by onInitialize(), and update().
referenceFrame_
std::string sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::referenceFrame_ private
Definition at line 19 of file cp_constraint_virtual_side_wall.h.
Referenced by CpConstraintVirtualSideWall(), and createVirtualCollisionWalls().
size_
geometry_msgs::Vector3 sm_fetch_two_table_whiskey_pour::cl_move_group_interface::CpConstraintVirtualSideWall::size_ private
Definition at line 21 of file cp_constraint_virtual_side_wall.h.
Referenced by CpConstraintVirtualSideWall(), and createVirtualCollisionWalls().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/clients/move_group_interface_client/components/cp_constraint_virtual_side_wall.h
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/clients/move_group_interface_client/components/cp_cube_obstacle.h
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/src/sm_fetch_two_table_whiskey_pour/clients/move_group_interface_client/components/cp_constraint_virtual_side_wall.cpp