SMACC: cl_move_group_interface::CbMoveEndEffector Class Reference
cl_move_group_interface::CbMoveEndEffector Class Reference
#include <cb_move_end_effector.h>
Public Member Functions
CbMoveEndEffector ()
CbMoveEndEffector (geometry_msgs::PoseStamped target_pose, std::string tip_link="")
virtual void onEntry () override
Public Member Functions inherited from smacc::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Public Attributes
geometry_msgs::PoseStamped targetPose
std::string tip_link_
boost::optional< std::string > group_
Protected Member Functions
bool moveToAbsolutePose (moveit::planning_interface::MoveGroupInterface &moveGroupInterface, geometry_msgs::PoseStamped &targetObjectPose)
Protected Member Functions inherited from smacc::SmaccAsyncClientBehavior
virtual void executeOnEntry () override
virtual void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Protected Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 14 of file cb_move_end_effector.h.
Constructor & Destructor Documentation
CbMoveEndEffector() [1/2]
cl_move_group_interface::CbMoveEndEffector::CbMoveEndEffector ()
Definition at line 14 of file cb_move_end_effector.cpp.
{
}
CbMoveEndEffector() [2/2]
cl_move_group_interface::CbMoveEndEffector::CbMoveEndEffector (geometry_msgs::PoseStamped target_pose, std::string tip_link = "")
Definition at line 18 of file cb_move_end_effector.cpp.
  : targetPose(target_pose)
{
  tip_link_ = tip_link;
}
References tip_link_.
Member Function Documentation
moveToAbsolutePose()
bool cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose (moveit::planning_interface::MoveGroupInterface & moveGroupInterface, geometry_msgs::PoseStamped & targetObjectPose) protected
Definition at line 43 of file cb_move_end_effector.cpp.
{
  auto& planningSceneInterface = movegroupClient_->planningSceneInterface;
  ROS_DEBUG("[CbMoveEndEffector] Synchronous sleep of 1 seconds");
  ros::Duration(0.5).sleep();
  moveGroupInterface.setPlanningTime(1.0);
  ROS_INFO_STREAM("[CbMoveEndEffector] Target End efector Pose: " << targetObjectPose);
  moveGroupInterface.setPoseTarget(targetObjectPose, tip_link_);
  moveGroupInterface.setPoseReferenceFrame(targetObjectPose.header.frame_id);
  moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
  bool success = (moveGroupInterface.plan(computedMotionPlan) == moveit::planning_interface::MoveItErrorCode::SUCCESS);
  ROS_INFO_NAMED("CbMoveEndEffector", "Success Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED");
  if (success)
  {
    auto executionResult = moveGroupInterface.execute(computedMotionPlan);
    if (executionResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
    {
      ROS_INFO("[CbMoveEndEffector] motion execution succeeded");
      movegroupClient_->postEventMotionExecutionSucceded();
      this->postSuccessEvent();
    }
    else
    {
      ROS_INFO("[CbMoveEndEffector] motion execution failed");
      movegroupClient_->postEventMotionExecutionFailed();
      this->postFailureEvent();
    }
  }
  else
  {
    ROS_INFO("[CbMoveEndEffector] motion execution failed");
    movegroupClient_->postEventMotionExecutionFailed();
    this->postFailureEvent();
  }
  ROS_DEBUG("[CbMoveEndEffector] Synchronous sleep of 1 seconds");
  ros::Duration(0.5).sleep();
  return success;
}
References movegroupClient_, cl_move_group_interface::ClMoveGroup::planningSceneInterface, cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded(), smacc::SmaccAsyncClientBehavior::postFailureEvent(), smacc::SmaccAsyncClientBehavior::postSuccessEvent(), and tip_link_.
Referenced by onEntry().
onEntry()
void cl_move_group_interface::CbMoveEndEffector::onEntry () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 24 of file cb_move_end_effector.cpp.
{
  this->requiresClient(movegroupClient_);
  if (this->group_)
  {
      ROS_DEBUG("[CbMoveEndEfector] new thread started to move absolute end effector");
      moveit::planning_interface::MoveGroupInterface move_group(*(this->group_));
      this->moveToAbsolutePose(move_group, targetPose);
      ROS_DEBUG("[CbMoveEndEfector] to move absolute end effector thread destroyed");
  }
  else
  {
      ROS_DEBUG("[CbMoveEndEfector] new thread started to move absolute end effector");
      this->moveToAbsolutePose(movegroupClient_->moveGroupClientInterface, targetPose);
      ROS_DEBUG("[CbMoveEndEfector] to move absolute end effector thread destroyed");
  }
}
References group_, movegroupClient_, cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, moveToAbsolutePose(), smacc::ISmaccClientBehavior::requiresClient(), and targetPose.
Member Data Documentation
group_
boost::optional<std::string> cl_move_group_interface::CbMoveEndEffector::group_
Definition at line 19 of file cb_move_end_effector.h.
Referenced by onEntry().
movegroupClient_
ClMoveGroup* cl_move_group_interface::CbMoveEndEffector::movegroupClient_ protected
Definition at line 30 of file cb_move_end_effector.h.
Referenced by moveToAbsolutePose(), and onEntry().
targetPose
geometry_msgs::PoseStamped cl_move_group_interface::CbMoveEndEffector::targetPose
Definition at line 17 of file cb_move_end_effector.h.
Referenced by onEntry(), and sm_fetch_two_table_pick_n_place_1::pick_states::StMovePregraspPose::runtimeConfigure().
tip_link_
std::string cl_move_group_interface::CbMoveEndEffector::tip_link_
Definition at line 18 of file cb_move_end_effector.h.
Referenced by CbMoveEndEffector(), and moveToAbsolutePose().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_end_effector.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_end_effector.cpp