SMACC: cl_move_base_z::CbUndoPathBackwards Class Reference
cl_move_base_z::CbUndoPathBackwards Class Reference
#include <cb_undo_path_backwards.h>
Public Member Functions
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Public Attributes
boost::optional< UndoPathLocalPlanner > forceUndoLocalPlanner
Private Attributes
tf::TransformListener listener
Additional Inherited Members
Protected Member Functions inherited from smacc::SmaccAsyncClientBehavior
virtual void executeOnEntry () override
virtual void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Protected Attributes inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
ClMoveBaseZ * moveBaseClient_
ros::Publisher visualizationMarkersPub_
Detailed Description
Definition at line 21 of file cb_undo_path_backwards.h.
Member Function Documentation
onEntry()
void cl_move_base_z::CbUndoPathBackwards::onEntry () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 9 of file cb_undo_path_backwards.cpp.
{
  auto *odomTracker = moveBaseClient_->getComponent<OdomTracker>();
  auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
  nav_msgs::Path forwardpath = odomTracker->getPath();
  // ROS_INFO_STREAM("[UndoPathBackward] Current path backwards: " << forwardpath);
  odomTracker->setWorkingMode(WorkingMode::CLEAR_PATH);
  ClMoveBaseZ::Goal goal;
  // this line is used to flush/reset backward planner in the case it were already there
  // plannerSwitcher->setDefaultPlanners();
  if (forwardpath.poses.size() > 0)
  {
    goal.target_pose = forwardpath.poses.front();
    if(forceUndoLocalPlanner)
    {
      if(forceUndoLocalPlanner == UndoPathLocalPlanner::PureSpinningLocalPlanner)
      {
        ROS_INFO("[CbUndoPathBackwards] forced to use Pure Spinning local planner");
        plannerSwitcher->setUndoPathPureSpinningPlannerConfiguration();
      }
      else
      {
        plannerSwitcher->setUndoPathBackwardsPlannerConfiguration();
        ROS_INFO("[CbUndoPathBackwards] forced to use BackwardsLocalPlanner (default)");
      }
    }
    else
    {
      ROS_INFO("[CbUndoPathBackwards] using default local planner: BackwardsLocalPlanner");
      plannerSwitcher->setUndoPathBackwardsPlannerConfiguration();
    }
    moveBaseClient_->sendGoal(goal);
  }
}
References forceUndoLocalPlanner, smacc::ISmaccClient::getComponent(), cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_, cl_move_base_z::PureSpinningLocalPlanner, and smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
onExit()
void cl_move_base_z::CbUndoPathBackwards::onExit () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 50 of file cb_undo_path_backwards.cpp.
{
  auto *odomTracker = moveBaseClient_->getComponent<OdomTracker>();
  odomTracker->popPath();
}
References smacc::ISmaccClient::getComponent(), and cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_.
Member Data Documentation
forceUndoLocalPlanner
boost::optional<UndoPathLocalPlanner> cl_move_base_z::CbUndoPathBackwards::forceUndoLocalPlanner
Definition at line 24 of file cb_undo_path_backwards.h.
Referenced by onEntry().
listener
tf::TransformListener cl_move_base_z::CbUndoPathBackwards::listener private
Definition at line 31 of file cb_undo_path_backwards.h.
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_undo_path_backwards.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/client_behaviors/cb_undo_path_backwards.cpp