SMACC: smacc Namespace Reference
smacc Namespace Reference
Namespaces
namespace client_bases
namespace components
namespace default_events
namespace default_transition_tags
namespace event_generators
namespace introspection
namespace state_reactors
namespace utils
Classes
struct AddTEventType
class CbServiceServerCallbackBase
class CbSubscriptionCallbackBase
class ClientHandler
struct ComponentKey
struct EvCbFailure
struct EvCbFinished
struct EvCbSuccess
class HasSpecificNamedOnExit
class HasStandardOnExit
class ISmaccClient
class ISmaccClientBehavior
class ISmaccComponent
class ISmaccOrthogonal
class ISmaccState
class ISmaccStateMachine
class ISmaccUpdatable
class Orthogonal
class SignalDetector
class SmaccAsyncClientBehavior
class SmaccClientBehavior
class SmaccEventGenerator
class SmaccSignal
class SmaccState
struct SmaccStateMachineBase
State Machine.
class StateReactor
class Transition
Enumerations
enum class SMRunMode { DEBUG , RELEASE }
enum class EventLifeTime { ABSOLUTE , CURRENT_STATE }
enum class StateMachineInternalAction {
STATE_CONFIGURING , STATE_ENTERING , STATE_STEADY , STATE_EXITING ,
TRANSITIONING
}
Functions
template<typename StateMachineType >
void run ()
template<typename TState , typename TTransitionTagName >
void specificNamedOnExit (TState &st, TTransitionTagName tn, std::true_type)
template<typename TState , typename TTransitionTagName >
void specificNamedOnExit (TState &, TTransitionTagName tn, std::false_type)
template<typename TState , typename TTransitionTagName >
void specificNamedOnExit (TState &m, TTransitionTagName tn)
template<typename TState >
void standardOnExit (TState &st, std::true_type)
template<typename TState >
void standardOnExit (TState &, std::false_type)
template<typename TState >
void standardOnExit (TState &m)
Enumeration Type Documentation
EventLifeTime
enum class smacc::EventLifeTime strong
Enumerator
ABSOLUTE
CURRENT_STATE
Definition at line 32 of file smacc_state_machine.h.
{
    ABSOLUTE,
    CURRENT_STATE /*events are discarded if we are leaving the state it were created. I is used for client behaviors whose lifetime is associated to state*/
};
SMRunMode
enum class smacc::SMRunMode strong
Enumerator
DEBUG
RELEASE
Definition at line 43 of file common.h.
{
  DEBUG,
  RELEASE
};
StateMachineInternalAction
enum class smacc::StateMachineInternalAction strong
Enumerator
STATE_CONFIGURING
STATE_ENTERING
STATE_STEADY
STATE_EXITING
TRANSITIONING
Definition at line 37 of file smacc_state_machine.h.
{
    STATE_CONFIGURING,
    STATE_ENTERING,
    STATE_STEADY,
    STATE_EXITING,
    TRANSITIONING
};
Function Documentation
run()
template<typename StateMachineType > void smacc::run ()
Definition at line 80 of file smacc_signal_detector.h.
{
    // create the asynchronous state machine scheduler
    SmaccFifoScheduler scheduler1(true);
    // create the signalDetector component
    SignalDetector signalDetector(&scheduler1);
    // create the asynchronous state machine processor
    SmaccFifoScheduler::processor_handle sm =
        scheduler1.create_processor<StateMachineType>(&signalDetector);
    // initialize the asynchronous state machine processor
    signalDetector.setProcessorHandle(sm);
    scheduler1.initiate_processor(sm);
    //create a thread for the asynchronous state machine processor execution
    boost::thread otherThread(boost::bind(&sc::fifo_scheduler<>::operator(), &scheduler1, 0));
    // use the  main thread for the signal detector component (waiting actionclient requests)
    signalDetector.pollingLoop();
    scheduler1.terminate();
    otherThread.join();
}
References smacc::SignalDetector::pollingLoop(), and smacc::SignalDetector::setProcessorHandle().
specificNamedOnExit() [1/3]
template<typename TState , typename TTransitionTagName > void smacc::specificNamedOnExit (TState & , TTransitionTagName tn, std::false_type)
Definition at line 30 of file state_traits.h.
    {
    }
specificNamedOnExit() [2/3]
template<typename TState , typename TTransitionTagName > void smacc::specificNamedOnExit (TState & m, TTransitionTagName tn)
Definition at line 35 of file state_traits.h.
    {
        specificNamedOnExit(m, tn,
                            std::integral_constant<bool, HasSpecificNamedOnExit<TState, TTransitionTagName>::value>());
    }
References specificNamedOnExit().
specificNamedOnExit() [3/3]
template<typename TState , typename TTransitionTagName > void smacc::specificNamedOnExit (TState & st, TTransitionTagName tn, std::true_type)
Definition at line 24 of file state_traits.h.
    {
        st.onExit(tn);
    }
Referenced by smacc::Transition< Event, Destination, Tag, TransitionContext, pTransitionAction >::reactions< State >::react_with_action(), smacc::Transition< Event, Destination, Tag, TransitionContext, pTransitionAction >::reactions< State >::react_without_action(), and specificNamedOnExit().
standardOnExit() [1/3]
template<typename TState > void smacc::standardOnExit (TState & , std::false_type)
Definition at line 68 of file state_traits.h.
    {
    }
standardOnExit() [2/3]
template<typename TState > void smacc::standardOnExit (TState & m)
Definition at line 73 of file state_traits.h.
    {
        standardOnExit(m,
                       std::integral_constant<bool, HasStandardOnExit<TState>::value>());
    }
References standardOnExit().
standardOnExit() [3/3]
template<typename TState > void smacc::standardOnExit (TState & st, std::true_type)
Definition at line 62 of file state_traits.h.
    {
        st.onExit();
    }
Referenced by smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::exit(), and standardOnExit().