SMACC: smacc::utils Namespace Reference
smacc::utils Namespace Reference
Classes
struct Bind
struct Bind< 1 >
struct Bind< 2 >
struct Bind< 3 >
struct Bind< 4 >
Functions
std::string cleanShortTypeName (const std::type_info &tinfo)
Function Documentation
cleanShortTypeName()
std::string smacc::utils::cleanShortTypeName (const std::type_info & tinfo)
Definition at line 14 of file common.cpp.
{
    auto typeinfo= TypeInfo::getFromStdTypeInfo(tinfo);
    auto nontemplatedfullclasname = typeinfo->getNonTemplatedTypeName();
    //ROS_INFO("State full classname: %s", fullclassname.c_str());
    std::vector<std::string> strs;
    boost::split(strs, nontemplatedfullclasname, boost::is_any_of("::"));
    std::string classname = strs.back();
    //ROS_INFO("State classname: %s", classname.c_str());
    return classname;
}
References smacc::introspection::TypeInfo::getFromStdTypeInfo().
Referenced by smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getShortName(), smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::initiate_impl(), smacc::SignalDetector::pollingLoop(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().