SMACC: sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper Struct Reference
sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper Struct Reference
#include <st_close_gripper.h>
Public Types
typedef mpl::list< Transition< EvActionSucceeded< ClGripper, OrGripper >, StGraspRetreat > > reactions
Public Types inherited from smacc::SmaccState< StCloseGripper, SS >
typedef SS TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef mpl::list<> LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
SmaccState ()=delete
SmaccState (my_context ctx)
Public Member Functions inherited from smacc::SmaccState< StCloseGripper, SS >
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc::introspection::SmaccStateInfo * getStateInfo ()
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
bool getGlobalSMData (std::string name, T &ret)
void setGlobalSMData (std::string name, T value)
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc::ISmaccState
virtual ISmaccStateMachine & getStateMachine ()=0
ISmaccState * getParentState ()
ros::NodeHandle & getROSNode ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
template<typename T >
bool param (std::string param_name, T &param_val, const T &default_val) const
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Static Public Member Functions
static void staticConfigure ()
Static Public Member Functions inherited from smacc::SmaccState< StCloseGripper, SS >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, StCloseGripper &)> initializationFunction)
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
static void configure_orthogonal (Args &&... args)
static std::shared_ptr< smacc::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
static std::shared_ptr< smacc::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
static std::shared_ptr< smacc::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Additional Inherited Members
Public Attributes inherited from smacc::SmaccState< StCloseGripper, SS >
bool finishStateThrown
mpl::list<> * smacc_inner_type
Protected Attributes inherited from smacc::ISmaccState
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc::SmaccEventGenerator > > eventGenerators_
ros::NodeHandle nh
ros::NodeHandle contextNh
ISmaccState * parentState_
const smacc::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 7 of file st_close_gripper.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvActionSucceeded<ClGripper, OrGripper>, StGraspRetreat> > sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper::reactions
Definition at line 14 of file st_close_gripper.h.
Member Function Documentation
onEntry()
void sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper::onEntry () inline
Definition at line 34 of file st_close_gripper.h.
         {
            ros::Duration(1.0).sleep();
         }
onExit()
void sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper::onExit () inline
Definition at line 39 of file st_close_gripper.h.
         {
            ClMoveGroup *moveGroupClient;
            this->requiresClient(moveGroupClient);
            //auto cubepos = cubeinfo->pose_->toPoseStampedMsg();
            // //std::vector<moveit_msgs::CollisionObject> collisionObjects;
            // moveit_msgs::CollisionObject cubeCollision;
            // auto time = ros::Time::now();
            // createCollisionBox(cubepos.pose.position.x, cubepos.pose.position.y, cubepos.pose.position.z, 0.06, 0.06, 0.06, "collisioncube", "map",  cubeCollision, time, moveit_msgs::CollisionObject::ADD);
            // planningSceneInterface.applyCollisionObject(cubeCollision);
            // // collisionObjects.push_back(cubeCollision);
            // std::vector<std::string> touch_links{"l_gripper_finger_link", "r_gripper_finger_link"};
            // moveGroupClient->moveGroupClientInterface.attachObject("collisioncube", "gripper_link", touch_links);
            // //moveGroupClient->moveGroupClientInterface.setSupportSurfaceName("table_1");
            moveGroupClient->getComponent<CpConstraintTableWorkspaces>()->disableTableCollisionVolume();
            ros::Duration(1.0).sleep();
         }
References smacc::ISmaccState::requiresClient().
runtimeConfigure()
void sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper::runtimeConfigure () inline
Definition at line 23 of file st_close_gripper.h.
         {
            ClPerceptionSystem *perceptionSystem;
            this->requiresClient(perceptionSystem);
            auto cubeinfo = perceptionSystem->getTargetCurrentCubeInfo();
            auto cbattach = this->getOrthogonal<OrArm>()->getClientBehavior<CbAttachObject>();
            cbattach->targetObjectName_ = cubeinfo->pose_->getFrameId();
         }
References cl_move_base_z::Pose::getFrameId(), sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::getTargetCurrentCubeInfo(), sm_fetch_six_table_pick_n_sort_1::cl_perception_system::CubeInfo::pose_, and smacc::ISmaccState::requiresClient().
SmaccState() [1/2]
smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState () delete
SmaccState() [2/2]
smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState (my_context ctx) inline
Definition at line 53 of file smacc_state_base.h.
    {
      static_assert(std::is_base_of<ISmaccState, Context>::value || std::is_base_of<ISmaccStateMachine, Context>::value, "The context class must be a SmaccState or a SmaccStateMachine");
      static_assert(!std::is_same<MostDerived, Context>::value, "The context must be a different state or state machine than the current state");
      ROS_WARN("[%s] creating ", STATE_NAME);
      this->set_context(ctx.pContext_);
      this->stateInfo_ = getStateInfo();
      // storing a reference to the parent state
      auto &ps = this->template context<Context>();
      parentState_ = dynamic_cast<ISmaccState *>(&ps);
      finishStateThrown = false;
      this->contextNh = optionalNodeHandle(ctx.pContext_);
      ROS_DEBUG("[%s] Ros node handle namespace for this state: %s", STATE_NAME, contextNh.getNamespace().c_str());
      if (contextNh.getNamespace() == "/")
      {
        auto nhname = smacc::utils::cleanShortTypeName(typeid(Context));
        ROS_INFO("[%s] Creating ros NodeHandle for this state: %s", STATE_NAME, nhname.c_str());
        contextNh = ros::NodeHandle(nhname);
      }
    }
staticConfigure()
static void sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper::staticConfigure () inline static
Definition at line 17 of file st_close_gripper.h.
         {
            configure_orthogonal<OrGripper, CbCloseGripper>();
            configure_orthogonal<OrArm, CbAttachObject>();
         }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_fetch_six_table_pick_n_sort_1/include/sm_fetch_six_table_pick_n_sort_1/states/pick_states/st_close_gripper.h