SMACC: cl_move_group_interface::CbMoveCartesianRelative Class Reference
cl_move_group_interface::CbMoveCartesianRelative Class Reference
#include <cb_move_cartesian_relative.h>
Public Member Functions
CbMoveCartesianRelative ()
CbMoveCartesianRelative (geometry_msgs::Vector3 offset)
virtual void onEntry () override
virtual void onExit () override
void moveRelativeCartesian (moveit::planning_interface::MoveGroupInterface *movegroupClient, geometry_msgs::Vector3 &offset)
Public Member Functions inherited from smacc::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Public Attributes
geometry_msgs::Vector3 offset_
boost::optional< double > scalingFactor_
boost::optional< std::string > group_
ClMoveGroup * moveGroupSmaccClient_
Additional Inherited Members
Protected Member Functions inherited from smacc::SmaccAsyncClientBehavior
virtual void executeOnEntry () override
virtual void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Detailed Description
Definition at line 14 of file cb_move_cartesian_relative.h.
Constructor & Destructor Documentation
CbMoveCartesianRelative() [1/2]
cl_move_group_interface::CbMoveCartesianRelative::CbMoveCartesianRelative ()
Definition at line 11 of file cb_move_cartesian_relative.cpp.
{
}
CbMoveCartesianRelative() [2/2]
cl_move_group_interface::CbMoveCartesianRelative::CbMoveCartesianRelative (geometry_msgs::Vector3 offset)
Definition at line 15 of file cb_move_cartesian_relative.cpp.
                                                                            : offset_(offset)
{
}
Member Function Documentation
moveRelativeCartesian()
void cl_move_group_interface::CbMoveCartesianRelative::moveRelativeCartesian (moveit::planning_interface::MoveGroupInterface * movegroupClient, geometry_msgs::Vector3 & offset)
Definition at line 40 of file cb_move_cartesian_relative.cpp.
{
  std::vector<geometry_msgs::Pose> waypoints;
  // this one was working fine but the issue is that for relative motions it grows up on ABORT-State-Loop pattern.
  // But, we need current pose because maybe setCurrentPose was not set by previous behaviors. The only solution would be
  // distinguishing between the execution error and the planning error with no state change
  //auto referenceStartPose = movegroupClient->getPoseTarget();
  auto referenceStartPose = movegroupClient->getCurrentPose();
  movegroupClient->setPoseReferenceFrame(referenceStartPose.header.frame_id);
  ROS_INFO_STREAM("[CbMoveCartesianRelative] RELATIVE MOTION, SOURCE POSE: " << referenceStartPose);
  ROS_INFO_STREAM("[CbMoveCartesianRelative] Offset: " << offset);
  waypoints.push_back(referenceStartPose.pose);  // up and out
  auto endPose = referenceStartPose.pose;
  endPose.position.x += offset.x;
  endPose.position.y += offset.y;
  endPose.position.z += offset.z;
  ROS_INFO_STREAM("[CbMoveCartesianRelative] DESTINY POSE: " << endPose);
  // target_pose2.position.x -= 0.15;
  waypoints.push_back(endPose);  // left
  movegroupClient->setPoseTarget(endPose);
  float scalinf = 0.5;
  if (scalingFactor_)
    scalinf = *scalingFactor_;
  ROS_INFO_STREAM("[CbMoveCartesianRelative] Using scaling factor: " << scalinf);
  movegroupClient->setMaxVelocityScalingFactor(scalinf);
  moveit_msgs::RobotTrajectory trajectory;
  double fraction = movegroupClient->computeCartesianPath(waypoints,
                                                          0.01,  // eef_step
                                                          0.00,  // jump_threshold
                                                          trajectory);
  moveit::planning_interface::MoveItErrorCode behaviorResult;
  if (fraction != 1.0 || fraction == -1)
  {
    ROS_WARN_STREAM("[CbMoveCartesianRelative] Cartesian plan joint-continuity percentaje. Execution skipped because not 100% of cartesian motion: " << fraction*100<<"%");
    behaviorResult = moveit::planning_interface::MoveItErrorCode::PLANNING_FAILED;
  }
  else
  {
    ROS_INFO_STREAM("[CbMoveCartesianRelative] Cartesian plan joint-continuity percentaje: " << fraction);
    moveit::planning_interface::MoveGroupInterface::Plan grasp_pose_plan;
    // grasp_pose_plan.start_state_ = *(moveGroupInterface.getCurrentState());
    grasp_pose_plan.trajectory_ = trajectory;
    behaviorResult = movegroupClient->execute(grasp_pose_plan);
  }
  if (behaviorResult == moveit_msgs::MoveItErrorCodes::SUCCESS)
  {
    ROS_INFO("[CbMoveCartesianRelative] relative motion execution succeeded: fraction %lf.", fraction);
    moveGroupSmaccClient_->postEventMotionExecutionSucceded();
    this->postSuccessEvent();
  }
  else
  {
    movegroupClient->setPoseTarget(referenceStartPose); // undo changes since we did not executed the motion
    ROS_INFO("[CbMoveCartesianRelative] relative motion execution failed: fraction %lf.", fraction);
    moveGroupSmaccClient_->postEventMotionExecutionFailed();
    this->postFailureEvent();
  }
}
References moveGroupSmaccClient_, cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded(), smacc::SmaccAsyncClientBehavior::postFailureEvent(), smacc::SmaccAsyncClientBehavior::postSuccessEvent(), and scalingFactor_.
Referenced by onEntry().
onEntry()
void cl_move_group_interface::CbMoveCartesianRelative::onEntry () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 19 of file cb_move_cartesian_relative.cpp.
{
  this->requiresClient(moveGroupSmaccClient_);
  if (this->group_)
  {
      moveit::planning_interface::MoveGroupInterface move_group(*(this->group_));
      this->moveRelativeCartesian(&move_group, offset_);
  }
  else
  {
      this->moveRelativeCartesian(&moveGroupSmaccClient_->moveGroupClientInterface, offset_);
  }
}
References group_, cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, moveGroupSmaccClient_, moveRelativeCartesian(), offset_, and smacc::ISmaccClientBehavior::requiresClient().
onExit()
void cl_move_group_interface::CbMoveCartesianRelative::onExit () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 34 of file cb_move_cartesian_relative.cpp.
{
}
Member Data Documentation
group_
boost::optional<std::string> cl_move_group_interface::CbMoveCartesianRelative::group_
Definition at line 21 of file cb_move_cartesian_relative.h.
Referenced by onEntry().
moveGroupSmaccClient_
ClMoveGroup* cl_move_group_interface::CbMoveCartesianRelative::moveGroupSmaccClient_
Definition at line 35 of file cb_move_cartesian_relative.h.
Referenced by moveRelativeCartesian(), and onEntry().
offset_
geometry_msgs::Vector3 cl_move_group_interface::CbMoveCartesianRelative::offset_
Definition at line 17 of file cb_move_cartesian_relative.h.
Referenced by onEntry().
scalingFactor_
boost::optional<double> cl_move_group_interface::CbMoveCartesianRelative::scalingFactor_
Definition at line 19 of file cb_move_cartesian_relative.h.
Referenced by moveRelativeCartesian().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_cartesian_relative.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_cartesian_relative.cpp