SMACC: cl_ros_publisher::CbPublishOnce< RosMsgType > Class Template Reference
cl_ros_publisher::CbPublishOnce< RosMsgType > Class Template Reference
#include <cb_publish_once.h>
Public Member Functions
CbPublishOnce ()
template<typename TMessage >
CbPublishOnce (const TMessage &data)
template<typename TMessage >
void setMessage (const TMessage &data)
virtual void onEntry () override
virtual void onExit () override
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Private Attributes
std::function< void()> deferedPublishFn
ClRosPublisher * client_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Detailed Description
template<typename RosMsgType>
class cl_ros_publisher::CbPublishOnce< RosMsgType >
Definition at line 9 of file cb_publish_once.h.
Constructor & Destructor Documentation
CbPublishOnce() [1/2]
template<typename RosMsgType > cl_ros_publisher::CbPublishOnce< RosMsgType >::CbPublishOnce () inline
Definition at line 16 of file cb_publish_once.h.
        : deferedPublishFn(nullptr)
    {
    }
CbPublishOnce() [2/2]
template<typename RosMsgType > template<typename TMessage > cl_ros_publisher::CbPublishOnce< RosMsgType >::CbPublishOnce (const TMessage & data) inline
Definition at line 22 of file cb_publish_once.h.
    {
        this->setMessage(data);
    }
References cl_ros_publisher::CbPublishOnce< RosMsgType >::setMessage().
Member Function Documentation
onEntry()
template<typename RosMsgType > virtual void cl_ros_publisher::CbPublishOnce< RosMsgType >::onEntry () inline override virtual
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 35 of file cb_publish_once.h.
    {
        this->requiresClient(client_);
        if (deferedPublishFn != nullptr)
            deferedPublishFn();
    }
References cl_ros_publisher::CbPublishOnce< RosMsgType >::deferedPublishFn, and smacc::ISmaccClientBehavior::requiresClient().
onExit()
template<typename RosMsgType > virtual void cl_ros_publisher::CbPublishOnce< RosMsgType >::onExit () inline override virtual
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 43 of file cb_publish_once.h.
    {
    }
setMessage()
template<typename RosMsgType > template<typename TMessage > void cl_ros_publisher::CbPublishOnce< RosMsgType >::setMessage (const TMessage & data) inline
Definition at line 28 of file cb_publish_once.h.
    {
        deferedPublishFn = [=]() {
            client_->publish(data);
        };
    }
References cl_ros_publisher::CbPublishOnce< RosMsgType >::client_, cl_ros_publisher::CbPublishOnce< RosMsgType >::deferedPublishFn, and cl_ros_publisher::ClRosPublisher::publish().
Referenced by cl_ros_publisher::CbPublishOnce< RosMsgType >::CbPublishOnce().
Member Data Documentation
client_
template<typename RosMsgType > ClRosPublisher* cl_ros_publisher::CbPublishOnce< RosMsgType >::client_ private
Definition at line 13 of file cb_publish_once.h.
Referenced by cl_ros_publisher::CbPublishOnce< RosMsgType >::setMessage().
deferedPublishFn
template<typename RosMsgType > std::function<void()> cl_ros_publisher::CbPublishOnce< RosMsgType >::deferedPublishFn private
Definition at line 12 of file cb_publish_once.h.
Referenced by cl_ros_publisher::CbPublishOnce< RosMsgType >::onEntry(), and cl_ros_publisher::CbPublishOnce< RosMsgType >::setMessage().
The documentation for this class was generated from the following file:
smacc_client_library/ros_publisher_client/include/ros_publisher_client/client_behaviors/cb_publish_once.h