SMACC: cl_move_group_interface::ClMoveGroup Class Reference
cl_move_group_interface::ClMoveGroup Class Reference
#include <cl_movegroup.h>
Public Member Functions
ClMoveGroup (std::string groupName)
virtual ~ClMoveGroup ()
void postEventMotionExecutionSucceded ()
void postEventMotionExecutionFailed ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionSuccedded (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionFailed (TCallback callback, T *object)
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Public Attributes
moveit::planning_interface::MoveGroupInterface moveGroupClientInterface
moveit::planning_interface::PlanningSceneInterface planningSceneInterface
Private Attributes
std::function< void()> postEventMotionExecutionSucceded_
std::function< void()> postEventMotionExecutionFailed_
smacc::SmaccSignal< void()> onSucceded_
smacc::SmaccSignal< void()> onFailed_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Detailed Description
Definition at line 61 of file cl_movegroup.h.
Constructor & Destructor Documentation
ClMoveGroup()
cl_move_group_interface::ClMoveGroup::ClMoveGroup (std::string groupName)
Definition at line 11 of file cl_movegroup.cpp.
    : moveGroupClientInterface(groupName)
{
    ros::WallDuration(10.0).sleep();
}
~ClMoveGroup()
cl_move_group_interface::ClMoveGroup::~ClMoveGroup () virtual
Definition at line 17 of file cl_movegroup.cpp.
{
}
Member Function Documentation
onMotionExecutionFailed()
template<typename TCallback , typename T > boost::signals2::connection cl_move_group_interface::ClMoveGroup::onMotionExecutionFailed (TCallback callback, T * object) inline
Definition at line 106 of file cl_movegroup.h.
  {
    return this->getStateMachine()->createSignalConnection(onFailed_, callback, object);
  }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onMotionExecutionSuccedded()
template<typename TCallback , typename T > boost::signals2::connection cl_move_group_interface::ClMoveGroup::onMotionExecutionSuccedded (TCallback callback, T * object) inline
Definition at line 100 of file cl_movegroup.h.
  {
    return this->getStateMachine()->createSignalConnection(onSucceded_, callback, object);
  }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_move_group_interface::ClMoveGroup::onOrthogonalAllocation () inline
Definition at line 86 of file cl_movegroup.h.
  {
    postEventMotionExecutionSucceded_ = [=]() {
      this->onSucceded_();
      this->postEvent<EvMoveGroupMotionExecutionSucceded<TSourceObject, TOrthogonal>>();
    };
    postEventMotionExecutionFailed_ = [=]() {
      this->onFailed_();
      this->postEvent<EvMoveGroupMotionExecutionFailed<TSourceObject, TOrthogonal>>();
    };
  }
References onFailed_, onSucceded_, postEventMotionExecutionFailed_, and postEventMotionExecutionSucceded_.
postEventMotionExecutionFailed()
void cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed ()
Definition at line 27 of file cl_movegroup.cpp.
{
    ROS_INFO("[ClMoveGroup] Post Motion Failure Event");
    postEventMotionExecutionFailed_();
}
References postEventMotionExecutionFailed_.
Referenced by cl_move_group_interface::CbMoveJoints::moveJoints(), cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative(), cl_move_group_interface::CbMoveCartesianRelative::moveRelativeCartesian(), cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), and cl_move_group_interface::CbMoveEndEffectorTrajectory::onOrthogonalAllocation().
postEventMotionExecutionSucceded()
void cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded ()
Definition at line 21 of file cl_movegroup.cpp.
{
    ROS_INFO("[ClMoveGroup] Post Motion Success Event");
    postEventMotionExecutionSucceded_();
}
References postEventMotionExecutionSucceded_.
Referenced by cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_move_group_interface::CbMoveJoints::moveJoints(), cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative(), cl_move_group_interface::CbMoveCartesianRelative::moveRelativeCartesian(), and cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose().
Member Data Documentation
moveGroupClientInterface
moveit::planning_interface::MoveGroupInterface cl_move_group_interface::ClMoveGroup::moveGroupClientInterface
Definition at line 74 of file cl_movegroup.h.
Referenced by cl_move_group_interface::CbCircularPivotMotion::computeCurrentEndEffectorPoseRelativeToPivot(), cl_move_group_interface::CbMoveEndEffectorTrajectory::computeJointSpaceTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::getCurrentEndEffectorPose(), cl_move_group_interface::CbMoveNamedTarget::getNamedTargetValues(), cl_move_group_interface::CbAttachObject::onEntry(), cl_move_group_interface::CbDetachObject::onEntry(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_move_group_interface::CbMoveCartesianRelative::onEntry(), cl_move_group_interface::CbMoveEndEffector::onEntry(), cl_move_group_interface::CbMoveEndEffectorRelative::onEntry(), cl_move_group_interface::CbMoveJoints::onEntry(), and cl_move_group_interface::CbMoveNamedTarget::onEntry().
onFailed_
smacc::SmaccSignal<void()> cl_move_group_interface::ClMoveGroup::onFailed_ private
Definition at line 68 of file cl_movegroup.h.
Referenced by onOrthogonalAllocation().
onSucceded_
smacc::SmaccSignal<void()> cl_move_group_interface::ClMoveGroup::onSucceded_ private
Definition at line 67 of file cl_movegroup.h.
Referenced by onOrthogonalAllocation().
planningSceneInterface
moveit::planning_interface::PlanningSceneInterface cl_move_group_interface::ClMoveGroup::planningSceneInterface
Definition at line 76 of file cl_movegroup.h.
Referenced by cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose(), cl_move_group_interface::CbAttachObject::onEntry(), and cl_move_group_interface::CbDetachObject::onEntry().
postEventMotionExecutionFailed_
std::function<void()> cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed_ private
Definition at line 65 of file cl_movegroup.h.
Referenced by onOrthogonalAllocation(), and postEventMotionExecutionFailed().
postEventMotionExecutionSucceded_
std::function<void()> cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded_ private
Definition at line 64 of file cl_movegroup.h.
Referenced by onOrthogonalAllocation(), and postEventMotionExecutionSucceded().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/cl_movegroup.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/cl_movegroup.cpp