SMACC: cl_move_base_z::CbMoveBaseClientBehaviorBase Class Reference
cl_move_base_z::CbMoveBaseClientBehaviorBase Class Reference
#include <cb_move_base_client_behavior_base.h>
Public Member Functions
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Protected Attributes
ClMoveBaseZ * moveBaseClient_
ros::Publisher visualizationMarkersPub_
Private Member Functions
void propagateSuccessEvent (ClMoveBaseZ::ResultConstPtr &r)
void propagateFailureEvent (ClMoveBaseZ::ResultConstPtr &r)
Additional Inherited Members
Protected Member Functions inherited from smacc::SmaccAsyncClientBehavior
virtual void executeOnEntry () override
virtual void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Detailed Description
Definition at line 17 of file cb_move_base_client_behavior_base.h.
Member Function Documentation
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_move_base_z::CbMoveBaseClientBehaviorBase::onOrthogonalAllocation () inline
Definition at line 21 of file cb_move_base_client_behavior_base.h.
  {
    smacc::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
    this->requiresClient(moveBaseClient_);
    moveBaseClient_->onSucceeded(&CbMoveBaseClientBehaviorBase::propagateSuccessEvent, this);
    moveBaseClient_->onAborted(&CbMoveBaseClientBehaviorBase::propagateFailureEvent, this);
    ros::NodeHandle nh;
    visualizationMarkersPub_ = nh.advertise<visualization_msgs::MarkerArray>("move_base_z/visualization_markers", 1);
  }
References moveBaseClient_, smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted(), smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), propagateFailureEvent(), propagateSuccessEvent(), smacc::ISmaccClientBehavior::requiresClient(), and visualizationMarkersPub_.
propagateFailureEvent()
void cl_move_base_z::CbMoveBaseClientBehaviorBase::propagateFailureEvent (ClMoveBaseZ::ResultConstPtr & r) private
Definition at line 14 of file cb_move_base_client_behavior_base.cpp.
{
  this->postFailureEvent();
}
References smacc::SmaccAsyncClientBehavior::postFailureEvent().
Referenced by onOrthogonalAllocation().
propagateSuccessEvent()
void cl_move_base_z::CbMoveBaseClientBehaviorBase::propagateSuccessEvent (ClMoveBaseZ::ResultConstPtr & r) private
Definition at line 10 of file cb_move_base_client_behavior_base.cpp.
{
  this->postSuccessEvent();
}
References smacc::SmaccAsyncClientBehavior::postSuccessEvent().
Referenced by onOrthogonalAllocation().
Member Data Documentation
moveBaseClient_
ClMoveBaseZ* cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_ protected
Definition at line 33 of file cb_move_base_client_behavior_base.h.
Referenced by cl_move_base_z::CbNavigateGlobalPosition::execute(), cl_move_base_z::CbNavigateGlobalPosition::onEntry(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_move_base_z::CbNavigateNextWaypoint::onEntry(), cl_move_base_z::CbRotate::onEntry(), cl_move_base_z::CbUndoPathBackwards::onEntry(), cl_move_base_z::CbUndoPathBackwards2::onEntry(), cl_move_base_z::CbUndoPathBackwards::onExit(), cl_move_base_z::CbUndoPathBackwards2::onExit(), onOrthogonalAllocation(), and cl_move_base_z::CbUndoPathBackwards2::update().
visualizationMarkersPub_
ros::Publisher cl_move_base_z::CbMoveBaseClientBehaviorBase::visualizationMarkersPub_ protected
Definition at line 34 of file cb_move_base_client_behavior_base.h.
Referenced by onOrthogonalAllocation(), and cl_move_base_z::CbUndoPathBackwards2::publishMarkers().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_move_base_client_behavior_base.h
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/client_behaviors/cb_move_base_client_behavior_base.cpp