SMACC: smacc::client_bases::SmaccActionClientBase< ActionType > Class Template Reference
smacc::client_bases::SmaccActionClientBase< ActionType > Class Template Reference
#include <smacc_action_client_base.h>
Public Types
typedef actionlib::SimpleActionClient< ActionType > ActionClient
typedef actionlib::SimpleActionClient< ActionType > GoalHandle
typedef ActionClient::SimpleDoneCallback SimpleDoneCallback
typedef ActionClient::SimpleActiveCallback SimpleActiveCallback
typedef ActionClient::SimpleFeedbackCallback SimpleFeedbackCallback
Public Member Functions
ACTION_DEFINITION (ActionType)
SmaccActionClientBase (std::string actionServerName)
SmaccActionClientBase ()
virtual ~SmaccActionClientBase ()
virtual void initialize () override
template<typename EvType >
void postResultEvent (ResultConstPtr result)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename T >
boost::signals2::connection onSucceeded (void(T::*callback)(ResultConstPtr &), T *object)
template<typename T >
boost::signals2::connection onSucceeded (std::function< void(ResultConstPtr &)> callback)
template<typename T >
boost::signals2::connection onAborted (void(T::*callback)(ResultConstPtr &), T *object)
template<typename T >
boost::signals2::connection onAborted (std::function< void(ResultConstPtr &)> callback)
template<typename T >
boost::signals2::connection onPreempted (void(T::*callback)(ResultConstPtr &), T *object)
template<typename T >
boost::signals2::connection onPreempted (std::function< void(ResultConstPtr &)> callback)
template<typename T >
boost::signals2::connection onRejected (void(T::*callback)(ResultConstPtr &), T *object)
template<typename T >
boost::signals2::connection onRejected (std::function< void(ResultConstPtr &)> callback)
virtual void cancelGoal () override
virtual SimpleClientGoalState getState () override
void sendGoal (Goal &goal)
Public Member Functions inherited from smacc::client_bases::ISmaccActionClient
ISmaccActionClient ()
virtual ~ISmaccActionClient ()
std::string getNamespace () const
virtual void cancelGoal ()=0
virtual SimpleClientGoalState getState ()=0
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Static Public Member Functions
static std::string getEventLabel ()
Public Attributes
std::string name_
rosnamespace path
smacc::SmaccSignal< void(const ResultConstPtr &)> onSucceeded_
smacc::SmaccSignal< void(const ResultConstPtr &)> onAborted_
smacc::SmaccSignal< void(const ResultConstPtr &)> onPreempted_
smacc::SmaccSignal< void(const ResultConstPtr &)> onRejected_
std::function< void(ResultConstPtr)> postSuccessEvent
std::function< void(ResultConstPtr)> postAbortedEvent
std::function< void(ResultConstPtr)> postPreemptedEvent
std::function< void(ResultConstPtr)> postRejectedEvent
std::function< void(FeedbackConstPtr)> postFeedbackEvent
SimpleDoneCallback done_cb
SimpleActiveCallback active_cb
SimpleFeedbackCallback feedback_cb
Protected Member Functions
void onFeedback (const FeedbackConstPtr &feedback_msg)
void onResult (const SimpleClientGoalState &state, const ResultConstPtr &result_msg)
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Protected Attributes
std::shared_ptr< ActionClient > client_
Protected Attributes inherited from smacc::client_bases::ISmaccActionClient
std::string name_
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Detailed Description
template<typename ActionType>
class smacc::client_bases::SmaccActionClientBase< ActionType >
Definition at line 21 of file smacc_action_client_base.h.
Member Typedef Documentation
ActionClient
template<typename ActionType > typedef actionlib::SimpleActionClient<ActionType> smacc::client_bases::SmaccActionClientBase< ActionType >::ActionClient
Definition at line 26 of file smacc_action_client_base.h.
GoalHandle
template<typename ActionType > typedef actionlib::SimpleActionClient<ActionType> smacc::client_bases::SmaccActionClientBase< ActionType >::GoalHandle
Definition at line 27 of file smacc_action_client_base.h.
SimpleActiveCallback
template<typename ActionType > typedef ActionClient::SimpleActiveCallback smacc::client_bases::SmaccActionClientBase< ActionType >::SimpleActiveCallback
Definition at line 30 of file smacc_action_client_base.h.
SimpleDoneCallback
template<typename ActionType > typedef ActionClient::SimpleDoneCallback smacc::client_bases::SmaccActionClientBase< ActionType >::SimpleDoneCallback
Definition at line 29 of file smacc_action_client_base.h.
SimpleFeedbackCallback
template<typename ActionType > typedef ActionClient::SimpleFeedbackCallback smacc::client_bases::SmaccActionClientBase< ActionType >::SimpleFeedbackCallback
Definition at line 31 of file smacc_action_client_base.h.
Constructor & Destructor Documentation
SmaccActionClientBase() [1/2]
template<typename ActionType > smacc::client_bases::SmaccActionClientBase< ActionType >::SmaccActionClientBase (std::string actionServerName) inline
Definition at line 33 of file smacc_action_client_base.h.
        : ISmaccActionClient(),
          name_(actionServerName)
    {
    }
SmaccActionClientBase() [2/2]
template<typename ActionType > smacc::client_bases::SmaccActionClientBase< ActionType >::SmaccActionClientBase () inline
Definition at line 39 of file smacc_action_client_base.h.
        : ISmaccActionClient(),
          name_("")
    {
    }
~SmaccActionClientBase()
template<typename ActionType > virtual smacc::client_bases::SmaccActionClientBase< ActionType >::~SmaccActionClientBase () inline virtual
Definition at line 51 of file smacc_action_client_base.h.
    {
    }
Member Function Documentation
ACTION_DEFINITION()
template<typename ActionType > smacc::client_bases::SmaccActionClientBase< ActionType >::ACTION_DEFINITION (ActionType)
cancelGoal()
template<typename ActionType > virtual void smacc::client_bases::SmaccActionClientBase< ActionType >::cancelGoal () inline override virtual
Implements smacc::client_bases::ISmaccActionClient.
Definition at line 159 of file smacc_action_client_base.h.
    {
        if (client_->isServerConnected())
        {
            ROS_INFO("Cancelling goal of %s", this->getName().c_str());
            client_->cancelGoal();
        }
        else
        {
            ROS_ERROR("%s [at %s]: not connected with actionserver, skipping cancel goal ...", getName().c_str(), getNamespace().c_str());
        }
    }
References smacc::client_bases::SmaccActionClientBase< ActionType >::client_, smacc::ISmaccClient::getName(), and smacc::client_bases::ISmaccActionClient::getNamespace().
Referenced by cl_move_base_z::CbUndoPathBackwards2::update().
getEventLabel()
template<typename ActionType > static std::string smacc::client_bases::SmaccActionClientBase< ActionType >::getEventLabel () inline static
Definition at line 45 of file smacc_action_client_base.h.
    {
        auto type = TypeInfo::getTypeInfoFromType<ActionType>();
        return type->getNonTemplatedTypeName();
    }
References generate_debs::type.
getState()
template<typename ActionType > virtual SimpleClientGoalState smacc::client_bases::SmaccActionClientBase< ActionType >::getState () inline override virtual
Implements smacc::client_bases::ISmaccActionClient.
Definition at line 172 of file smacc_action_client_base.h.
    {
        return client_->getState();
    }
References smacc::client_bases::SmaccActionClientBase< ActionType >::client_.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
initialize()
template<typename ActionType > virtual void smacc::client_bases::SmaccActionClientBase< ActionType >::initialize () inline override virtual
Reimplemented from smacc::ISmaccClient.
Reimplemented in cl_move_base_z::ClMoveBaseZ.
Definition at line 58 of file smacc_action_client_base.h.
    {
        client_ = std::make_shared<ActionClient>(name_);
    }
References smacc::client_bases::SmaccActionClientBase< ActionType >::client_, and smacc::client_bases::SmaccActionClientBase< ActionType >::name_.
onAborted() [1/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted (std::function< void(ResultConstPtr &)> callback) inline
Definition at line 130 of file smacc_action_client_base.h.
    {
        return this->getStateMachine()->createSignalConnection(onAborted_, callback);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onAborted() [2/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted (void(T::*)(ResultConstPtr &) callback, T * object) inline
Definition at line 124 of file smacc_action_client_base.h.
    {
        return this->getStateMachine()->createSignalConnection(onAborted_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
Referenced by cl_move_base_z::CbMoveBaseClientBehaviorBase::onOrthogonalAllocation().
onFeedback()
template<typename ActionType > void smacc::client_bases::SmaccActionClientBase< ActionType >::onFeedback (const FeedbackConstPtr & feedback_msg) inline protected
Definition at line 197 of file smacc_action_client_base.h.
    {
        postFeedbackEvent(feedback_msg);
    }
References smacc::client_bases::SmaccActionClientBase< ActionType >::postFeedbackEvent.
onOrthogonalAllocation()
template<typename ActionType > template<typename TOrthogonal , typename TSourceObject > void smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation () inline
Definition at line 91 of file smacc_action_client_base.h.
    {
        // we create here all the event factory functions capturing the TOrthogonal
        postSuccessEvent = [=](auto msg) { this->postResultEvent<EvActionSucceeded<TSourceObject, TOrthogonal>>(msg); };
        postAbortedEvent = [=](auto msg) { this->postResultEvent<EvActionAborted<TSourceObject, TOrthogonal>>(msg); };
        postPreemptedEvent = [=](auto msg) { this->postResultEvent<EvActionPreempted<TSourceObject, TOrthogonal>>(msg); };
        postRejectedEvent = [=](auto msg) { this->postResultEvent<EvActionRejected<TSourceObject, TOrthogonal>>(msg); };
        postFeedbackEvent = [=](auto msg) {
            auto actionFeedbackEvent = new EvActionFeedback<Feedback, TOrthogonal>();
            actionFeedbackEvent->client = this;
            actionFeedbackEvent->feedbackMessage = *msg;
            this->postEvent(actionFeedbackEvent);
            ROS_DEBUG("[%s] FEEDBACK EVENT", demangleType(typeid(*this)).c_str());
        };
        done_cb = boost::bind(&SmaccActionClientBase<ActionType>::onResult, this, _1, _2);
        //active_cb;
        feedback_cb = boost::bind(&SmaccActionClientBase<ActionType>::onFeedback, this, _1);
    }
References smacc::introspection::demangleType(), smacc::client_bases::SmaccActionClientBase< ActionType >::done_cb, smacc::client_bases::SmaccActionClientBase< ActionType >::feedback_cb, battery_monitor_node::msg, smacc::client_bases::SmaccActionClientBase< ActionType >::postAbortedEvent, smacc::ISmaccClient::postEvent(), smacc::client_bases::SmaccActionClientBase< ActionType >::postFeedbackEvent, smacc::client_bases::SmaccActionClientBase< ActionType >::postPreemptedEvent, smacc::client_bases::SmaccActionClientBase< ActionType >::postRejectedEvent, and smacc::client_bases::SmaccActionClientBase< ActionType >::postSuccessEvent.
onPreempted() [1/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onPreempted (std::function< void(ResultConstPtr &)> callback) inline
Definition at line 142 of file smacc_action_client_base.h.
    {
        return this->getStateMachine()->createSignalConnection(onPreempted_, callback);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onPreempted() [2/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onPreempted (void(T::*)(ResultConstPtr &) callback, T * object) inline
Definition at line 136 of file smacc_action_client_base.h.
    {
        return this->getStateMachine()->createSignalConnection(onPreempted_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onRejected() [1/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onRejected (std::function< void(ResultConstPtr &)> callback) inline
Definition at line 154 of file smacc_action_client_base.h.
    {
        return this->getStateMachine()->createSignalConnection(onRejected_, callback);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onRejected() [2/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onRejected (void(T::*)(ResultConstPtr &) callback, T * object) inline
Definition at line 148 of file smacc_action_client_base.h.
    {
        return this->getStateMachine()->createSignalConnection(onRejected_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onResult()
template<typename ActionType > void smacc::client_bases::SmaccActionClientBase< ActionType >::onResult (const SimpleClientGoalState & state, const ResultConstPtr & result_msg) inline protected
Definition at line 202 of file smacc_action_client_base.h.
    {
        // auto *actionResultEvent = new EvActionResult<TDerived>();
        // actionResultEvent->client = this;
        // actionResultEvent->resultMessage = *result_msg;
        const auto &resultType = this->getState();
        ROS_INFO("[%s] request result: %s", this->getName().c_str(), resultType.toString().c_str());
        if (resultType == actionlib::SimpleClientGoalState::SUCCEEDED)
        {
            ROS_INFO("[%s] request result: Success", this->getName().c_str());
            onSucceeded_(result_msg);
            postSuccessEvent(result_msg);
        }
        else if (resultType == actionlib::SimpleClientGoalState::ABORTED)
        {
            ROS_INFO("[%s] request result: Aborted", this->getName().c_str());
            onAborted_(result_msg);
            postAbortedEvent(result_msg);
        }
        else if (resultType == actionlib::SimpleClientGoalState::REJECTED)
        {
            ROS_INFO("[%s] request result: Rejected", this->getName().c_str());
            onRejected_(result_msg);
            postRejectedEvent(result_msg);
        }
        else if (resultType == actionlib::SimpleClientGoalState::PREEMPTED)
        {
            ROS_INFO("[%s] request result: Preempted", this->getName().c_str());
            onPreempted_(result_msg);
            postPreemptedEvent(result_msg);
        }
        else
        {
            ROS_INFO("[%s] request result: NOT HANDLED TYPE: %s", this->getName().c_str(), resultType.toString().c_str());
        }
    }
References smacc::ISmaccClient::getName(), smacc::client_bases::SmaccActionClientBase< ActionType >::getState(), smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted_, smacc::client_bases::SmaccActionClientBase< ActionType >::onPreempted_, smacc::client_bases::SmaccActionClientBase< ActionType >::onRejected_, smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded_, smacc::client_bases::SmaccActionClientBase< ActionType >::postAbortedEvent, smacc::client_bases::SmaccActionClientBase< ActionType >::postPreemptedEvent, smacc::client_bases::SmaccActionClientBase< ActionType >::postRejectedEvent, and smacc::client_bases::SmaccActionClientBase< ActionType >::postSuccessEvent.
onSucceeded() [1/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded (std::function< void(ResultConstPtr &)> callback) inline
Definition at line 118 of file smacc_action_client_base.h.
    {
        return this->getStateMachine()->createSignalConnection(onSucceeded_, callback);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onSucceeded() [2/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded (void(T::*)(ResultConstPtr &) callback, T * object) inline
Definition at line 112 of file smacc_action_client_base.h.
    {
        return this->getStateMachine()->createSignalConnection(onSucceeded_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
Referenced by cl_move_base_z::CbMoveBaseClientBehaviorBase::onOrthogonalAllocation(), and cl_move_base_z::WaypointNavigator::sendNextGoal().
postResultEvent()
template<typename ActionType > template<typename EvType > void smacc::client_bases::SmaccActionClientBase< ActionType >::postResultEvent (ResultConstPtr result) inline
Definition at line 81 of file smacc_action_client_base.h.
    {
        auto *ev = new EvType();
        //ev->client = this;
        ev->resultMessage = *result;
        ROS_INFO("Posting EVENT %s", demangleSymbol(typeid(ev).name()).c_str());
        this->postEvent(ev);
    }
References smacc::introspection::demangleSymbol(), and smacc::ISmaccClient::postEvent().
sendGoal()
template<typename ActionType > void smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal (Goal & goal) inline
Definition at line 177 of file smacc_action_client_base.h.
    {
        ROS_INFO_STREAM("[ActionClient<"<< demangledTypeName<ActionType>() <<">] Sending goal to actionserver located in " << this->name_ << "\"");
        if (client_->isServerConnected())
        {
            ROS_INFO_STREAM(getName() << ": Goal Value: " << std::endl
                                      << goal);
            client_->sendGoal(goal, done_cb, active_cb, feedback_cb);
        }
        else
        {
            ROS_ERROR("%s [at %s]: not connected with actionserver, skipping goal request ...", getName().c_str(), getNamespace().c_str());
            //client_->waitForServer();
        }
    }
References smacc::client_bases::SmaccActionClientBase< ActionType >::active_cb, smacc::client_bases::SmaccActionClientBase< ActionType >::client_, smacc::client_bases::SmaccActionClientBase< ActionType >::done_cb, smacc::client_bases::SmaccActionClientBase< ActionType >::feedback_cb, smacc::ISmaccClient::getName(), and smacc::client_bases::ISmaccActionClient::getNamespace().
Referenced by cl_move_base_z::CbNavigateGlobalPosition::execute(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_move_base_z::CbRotate::onEntry(), cl_move_base_z::CbUndoPathBackwards::onEntry(), cl_move_base_z::CbUndoPathBackwards2::onEntry(), and cl_move_base_z::WaypointNavigator::sendNextGoal().
Member Data Documentation
active_cb
template<typename ActionType > SimpleActiveCallback smacc::client_bases::SmaccActionClientBase< ActionType >::active_cb
Definition at line 77 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
client_
template<typename ActionType > std::shared_ptr<ActionClient> smacc::client_bases::SmaccActionClientBase< ActionType >::client_ protected
Definition at line 195 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::cancelGoal(), smacc::client_bases::SmaccActionClientBase< ActionType >::getState(), smacc::client_bases::SmaccActionClientBase< ActionType >::initialize(), and smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
done_cb
template<typename ActionType > SimpleDoneCallback smacc::client_bases::SmaccActionClientBase< ActionType >::done_cb
Definition at line 76 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), and smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
feedback_cb
template<typename ActionType > SimpleFeedbackCallback smacc::client_bases::SmaccActionClientBase< ActionType >::feedback_cb
Definition at line 78 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), and smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
name_
template<typename ActionType > std::string smacc::client_bases::SmaccActionClientBase< ActionType >::name_
rosnamespace path
Definition at line 56 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::initialize(), and cl_move_base_z::CostmapSwitch::registerProxyFromDynamicReconfigureServer().
onAborted_
template<typename ActionType > smacc::SmaccSignal<void(const ResultConstPtr &)> smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted_
Definition at line 64 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
onPreempted_
template<typename ActionType > smacc::SmaccSignal<void(const ResultConstPtr &)> smacc::client_bases::SmaccActionClientBase< ActionType >::onPreempted_
Definition at line 65 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
onRejected_
template<typename ActionType > smacc::SmaccSignal<void(const ResultConstPtr &)> smacc::client_bases::SmaccActionClientBase< ActionType >::onRejected_
Definition at line 66 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
onSucceeded_
template<typename ActionType > smacc::SmaccSignal<void(const ResultConstPtr &)> smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded_
Definition at line 63 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
postAbortedEvent
template<typename ActionType > std::function<void(ResultConstPtr)> smacc::client_bases::SmaccActionClientBase< ActionType >::postAbortedEvent
Definition at line 70 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), and smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
postFeedbackEvent
template<typename ActionType > std::function<void(FeedbackConstPtr)> smacc::client_bases::SmaccActionClientBase< ActionType >::postFeedbackEvent
Definition at line 74 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onFeedback(), and smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation().
postPreemptedEvent
template<typename ActionType > std::function<void(ResultConstPtr)> smacc::client_bases::SmaccActionClientBase< ActionType >::postPreemptedEvent
Definition at line 71 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), and smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
postRejectedEvent
template<typename ActionType > std::function<void(ResultConstPtr)> smacc::client_bases::SmaccActionClientBase< ActionType >::postRejectedEvent
Definition at line 72 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), and smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
postSuccessEvent
template<typename ActionType > std::function<void(ResultConstPtr)> smacc::client_bases::SmaccActionClientBase< ActionType >::postSuccessEvent
Definition at line 69 of file smacc_action_client_base.h.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), and smacc::client_bases::SmaccActionClientBase< ActionType >::onResult().
The documentation for this class was generated from the following file:
smacc/include/smacc/client_bases/smacc_action_client_base.h