SMACC: sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData Class Reference
sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData Class Reference
#include <cp_lidar_data.h>
Public Member Functions
virtual void onInitialize () override
void MessageCallbackStoreDistanceToWall (const sensor_msgs::LaserScan &scanmsg)
Public Member Functions inherited from smacc::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Attributes
sensor_msgs::LaserScan lastMessage_
float forwardObstacleDistance
const float SECURITY_DISTANCE = 1
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccComponent
virtual void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
virtual void onInitialize ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
Protected Attributes inherited from smacc::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 8 of file cp_lidar_data.h.
Member Function Documentation
MessageCallbackStoreDistanceToWall()
void sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::MessageCallbackStoreDistanceToWall (const sensor_msgs::LaserScan & scanmsg) inline
Definition at line 22 of file cp_lidar_data.h.
  {
    this->lastMessage_ = scanmsg;
    auto fwdist = scanmsg.ranges[scanmsg.ranges.size() / 2] /*meter*/;
    /*if the distance is infinity or nan, use max range distance*/
    if (fwdist == std::numeric_limits<float>::infinity() || fwdist != fwdist)
    {
      this->forwardObstacleDistance = scanmsg.range_max - SECURITY_DISTANCE /*meters*/;
      ROS_INFO_THROTTLE(1.0, "[CpLidarSensorData] Distance to forward obstacle is not a number, setting default value to: %lf", scanmsg.range_max);
    }
    else
    {
      this->forwardObstacleDistance = std::max(fwdist - SECURITY_DISTANCE, 0.0F);
    }
  }
References SECURITY_DISTANCE.
Referenced by onInitialize().
onInitialize()
virtual void sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::onInitialize () inline override virtual
Reimplemented from smacc::ISmaccComponent.
Definition at line 16 of file cp_lidar_data.h.
  {
    auto client_ = dynamic_cast<smacc::client_bases::SmaccSubscriberClient<sensor_msgs::LaserScan> *>(owner_);
    client_->onMessageReceived(&CpLidarSensorData::MessageCallbackStoreDistanceToWall, this);
  }
References MessageCallbackStoreDistanceToWall(), smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), and smacc::ISmaccComponent::owner_.
Member Data Documentation
forwardObstacleDistance
float sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::forwardObstacleDistance
Definition at line 12 of file cp_lidar_data.h.
lastMessage_
sensor_msgs::LaserScan sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::lastMessage_
Definition at line 11 of file cp_lidar_data.h.
SECURITY_DISTANCE
const float sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::SECURITY_DISTANCE = 1
Definition at line 14 of file cp_lidar_data.h.
Referenced by MessageCallbackStoreDistanceToWall().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_strikes_back/include/sm_dance_bot_strikes_back/clients/cl_lidar/components/cp_lidar_data.h