SMACC: cl_ros_timer::CbTimerCountdownLoop Class Reference
cl_ros_timer::CbTimerCountdownLoop Class Reference
#include <cb_timer_countdown_loop.h>
Public Member Functions
CbTimerCountdownLoop (uint64_t triggerTickCount)
virtual void onEntry () override
virtual void onExit () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Private Member Functions
void onClientTimerTickCallback ()
Private Attributes
uint64_t tickCounter_
uint64_t tickTriggerCount_
ClRosTimer * timerClient_
std::function< void()> postCountDownEvent_
smacc::SmaccSignal< void()> onTimerTick_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Detailed Description
Definition at line 9 of file cb_timer_countdown_loop.h.
Constructor & Destructor Documentation
CbTimerCountdownLoop()
cl_ros_timer::CbTimerCountdownLoop::CbTimerCountdownLoop (uint64_t triggerTickCount)
Definition at line 6 of file cb_timer_countdown_loop.cpp.
    : tickTriggerCount_(triggerTickCount),
      tickCounter_(0)
{
}
Member Function Documentation
onClientTimerTickCallback()
void cl_ros_timer::CbTimerCountdownLoop::onClientTimerTickCallback () private
Definition at line 12 of file cb_timer_countdown_loop.cpp.
{
    tickCounter_++;
    if (tickCounter_ % tickTriggerCount_ == 0)
    {
        onTimerTick_();
        postCountDownEvent_();
    }
}
References onTimerTick_, postCountDownEvent_, tickCounter_, and tickTriggerCount_.
Referenced by onEntry().
onEntry()
void cl_ros_timer::CbTimerCountdownLoop::onEntry () override virtual
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 23 of file cb_timer_countdown_loop.cpp.
{
    this->requiresClient(timerClient_);
    timerClient_->onTimerTick(&CbTimerCountdownLoop::onClientTimerTickCallback, this);
}
References onClientTimerTickCallback(), cl_ros_timer::ClRosTimer::onTimerTick(), smacc::ISmaccClientBehavior::requiresClient(), and timerClient_.
onExit()
void cl_ros_timer::CbTimerCountdownLoop::onExit () override virtual
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 29 of file cb_timer_countdown_loop.cpp.
{
}
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_ros_timer::CbTimerCountdownLoop::onOrthogonalAllocation () inline
Definition at line 18 of file cb_timer_countdown_loop.h.
    {
        this->postCountDownEvent_ = [=]() {
            this->template postEvent<EvTimer<TSourceObject, TOrthogonal>>();
        };
    }
References postCountDownEvent_.
onTimerTick()
template<typename T > boost::signals2::connection cl_ros_timer::CbTimerCountdownLoop::onTimerTick (void(T::*)() callback, T * object) inline
Definition at line 26 of file cb_timer_countdown_loop.h.
    {
        return this->getStateMachine()->createSignalConnection(onTimerTick_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), smacc::ISmaccClientBehavior::getStateMachine(), and onTimerTick_.
Member Data Documentation
onTimerTick_
smacc::SmaccSignal<void()> cl_ros_timer::CbTimerCountdownLoop::onTimerTick_ private
Definition at line 37 of file cb_timer_countdown_loop.h.
Referenced by onClientTimerTickCallback(), and onTimerTick().
postCountDownEvent_
std::function<void()> cl_ros_timer::CbTimerCountdownLoop::postCountDownEvent_ private
Definition at line 36 of file cb_timer_countdown_loop.h.
Referenced by onClientTimerTickCallback(), and onOrthogonalAllocation().
tickCounter_
uint64_t cl_ros_timer::CbTimerCountdownLoop::tickCounter_ private
Definition at line 32 of file cb_timer_countdown_loop.h.
Referenced by onClientTimerTickCallback().
tickTriggerCount_
uint64_t cl_ros_timer::CbTimerCountdownLoop::tickTriggerCount_ private
Definition at line 33 of file cb_timer_countdown_loop.h.
Referenced by onClientTimerTickCallback().
timerClient_
ClRosTimer* cl_ros_timer::CbTimerCountdownLoop::timerClient_ private
Definition at line 35 of file cb_timer_countdown_loop.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/client_behaviors/cb_timer_countdown_loop.h
smacc_client_library/ros_timer_client/src/ros_timer_client/cb_timer_countdown_loop.cpp