SMACC: cl_move_group_interface::CpTrajectoryHistory Class Reference
cl_move_group_interface::CpTrajectoryHistory Class Reference
#include <cp_trajectory_history.h>
Public Member Functions
bool getLastTrajectory (int backIndex, moveit_msgs::RobotTrajectory &trajectory)
bool getLastTrajectory (moveit_msgs::RobotTrajectory &trajectory)
void pushTrajectory (std::string name, const moveit_msgs::RobotTrajectory &trajectory, moveit_msgs::MoveItErrorCodes result)
Public Member Functions inherited from smacc::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Private Attributes
std::vector< TrajectoryHistoryEntry > trajectoryHistory_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccComponent
virtual void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
virtual void onInitialize ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
Protected Attributes inherited from smacc::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 23 of file cp_trajectory_history.h.
Member Function Documentation
getLastTrajectory() [1/2]
bool cl_move_group_interface::CpTrajectoryHistory::getLastTrajectory (int backIndex, moveit_msgs::RobotTrajectory & trajectory)
Definition at line 12 of file cp_trajectory_history.cpp.
    {
        if (trajectoryHistory_.size() == 0 )
        {
            return false;
        }
        if (backIndex < 0)
        {
            backIndex = 0;
        }
        else if(backIndex >= this->trajectoryHistory_.size())
        {
            return false;
        }
        trajectory = this->trajectoryHistory_[this->trajectoryHistory_.size() - 1 - backIndex].trajectory;
        return true;
    }
References trajectoryHistory_.
Referenced by getLastTrajectory(), cl_move_group_interface::CbExecuteLastTrajectory::onEntry(), cl_move_group_interface::CbMoveLastTrajectoryInitialState::onEntry(), and cl_move_group_interface::CbUndoLastTrajectory::onEntry().
getLastTrajectory() [2/2]
bool cl_move_group_interface::CpTrajectoryHistory::getLastTrajectory (moveit_msgs::RobotTrajectory & trajectory)
Definition at line 32 of file cp_trajectory_history.cpp.
    {
        return getLastTrajectory(-1, trajectory);
    }
References getLastTrajectory().
pushTrajectory()
void cl_move_group_interface::CpTrajectoryHistory::pushTrajectory (std::string name, const moveit_msgs::RobotTrajectory & trajectory, moveit_msgs::MoveItErrorCodes result)
Definition at line 37 of file cp_trajectory_history.cpp.
    {
        TrajectoryHistoryEntry entry;
        this->trajectoryHistory_.push_back(entry);
        auto &last = this->trajectoryHistory_.back();
        last.trajectory = trajectory;
        last.result = result;
        last.name = name;
    }
References trajectoryHistory_.
Referenced by cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry().
Member Data Documentation
trajectoryHistory_
std::vector<TrajectoryHistoryEntry> cl_move_group_interface::CpTrajectoryHistory::trajectoryHistory_ private
Definition at line 34 of file cp_trajectory_history.h.
Referenced by getLastTrajectory(), and pushTrajectory().
The documentation for this class was generated from the following files:
smacc_client_library/move_group_interface_client/include/move_group_interface_client/components/cp_trajectory_history.h
smacc_client_library/move_group_interface_client/src/move_group_interface_client/components/cp_trajectory_history.cpp