SMACC: smacc::client_bases::SmaccServiceServerClient< TService > Class Template Reference
smacc::client_bases::SmaccServiceServerClient< TService > Class Template Reference
#include <smacc_service_server_client.h>
Public Member Functions
SmaccServiceServerClient ()
SmaccServiceServerClient (std::string service_name)
virtual ~SmaccServiceServerClient ()
template<typename T >
boost::signals2::connection onServiceRequestReceived (bool(T::*callback)(TServiceRequest &, std::shared_ptr< TServiceResponse >), T *object)
virtual void initialize () override
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Public Attributes
boost::optional< std::string > serviceName_
smacc::SmaccSignal< bool(TServiceRequest &, std::shared_ptr< TServiceResponse >)> onServiceRequestReceived_
Protected Attributes
ros::NodeHandle nh_
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Private Types
using TServiceRequest = typename TService::Request
using TServiceResponse = typename TService::Response
Private Member Functions
bool serviceCallback (TServiceRequest &req, TServiceResponse &res)
Private Attributes
ros::ServiceServer server_
bool initialized_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Detailed Description
template<typename TService>
class smacc::client_bases::SmaccServiceServerClient< TService >
Definition at line 12 of file smacc_service_server_client.h.
Member Typedef Documentation
TServiceRequest
template<typename TService > using smacc::client_bases::SmaccServiceServerClient< TService >::TServiceRequest = typename TService::Request private
Definition at line 13 of file smacc_service_server_client.h.
TServiceResponse
template<typename TService > using smacc::client_bases::SmaccServiceServerClient< TService >::TServiceResponse = typename TService::Response private
Definition at line 14 of file smacc_service_server_client.h.
Constructor & Destructor Documentation
SmaccServiceServerClient() [1/2]
template<typename TService > smacc::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient () inline
Definition at line 18 of file smacc_service_server_client.h.
{ initialized_ = false; }
References smacc::client_bases::SmaccServiceServerClient< TService >::initialized_.
SmaccServiceServerClient() [2/2]
template<typename TService > smacc::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient (std::string service_name) inline
Definition at line 19 of file smacc_service_server_client.h.
{
    serviceName_ = service_name;
    initialized_ = false;
  }
References smacc::client_bases::SmaccServiceServerClient< TService >::initialized_, and smacc::client_bases::SmaccServiceServerClient< TService >::serviceName_.
~SmaccServiceServerClient()
template<typename TService > virtual smacc::client_bases::SmaccServiceServerClient< TService >::~SmaccServiceServerClient () inline virtual
Definition at line 24 of file smacc_service_server_client.h.
{ server_.shutdown(); }
References smacc::client_bases::SmaccServiceServerClient< TService >::server_.
Member Function Documentation
initialize()
template<typename TService > virtual void smacc::client_bases::SmaccServiceServerClient< TService >::initialize () inline override virtual
Reimplemented from smacc::ISmaccClient.
Definition at line 37 of file smacc_service_server_client.h.
{
    if (!initialized_) {
      if (!serviceName_) {
        ROS_ERROR("service server with no service name set. Skipping.");
      } else {
        ROS_INFO_STREAM("[" << this->getName()
                            << "] Client Service: " << serviceName_);
        server_ = nh_.advertiseService(
            *serviceName_, &SmaccServiceServerClient<TService>::serviceCallback,
            this);
        this->initialized_ = true;
      }
    }
  }
References smacc::ISmaccClient::getName(), smacc::client_bases::SmaccServiceServerClient< TService >::initialized_, smacc::client_bases::SmaccServiceServerClient< TService >::nh_, smacc::client_bases::SmaccServiceServerClient< TService >::server_, and smacc::client_bases::SmaccServiceServerClient< TService >::serviceName_.
onServiceRequestReceived()
template<typename TService > template<typename T > boost::signals2::connection smacc::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived (bool(T::*)(TServiceRequest &, std::shared_ptr< TServiceResponse >) callback, T * object) inline
Definition at line 30 of file smacc_service_server_client.h.
                 {
    return this->getStateMachine()->createSignalConnection(
        onServiceRequestReceived_, callback, object);
  }
References smacc::ISmaccStateMachine::createSignalConnection(), smacc::ISmaccClient::getStateMachine(), and smacc::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived_.
serviceCallback()
template<typename TService > bool smacc::client_bases::SmaccServiceServerClient< TService >::serviceCallback (TServiceRequest & req, TServiceResponse & res) inline private
Definition at line 57 of file smacc_service_server_client.h.
{
    std::shared_ptr<TServiceResponse> response{new TServiceResponse};
    auto ret_val = onServiceRequestReceived_(req, response);
    if (!ret_val)  // Check if response is empty
    {
      ROS_WARN(
          "No return value received from service call. Are you returning a "
          "value?");
      return false;
    }
    res = *response;
    return *ret_val;
  }
References smacc::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived_.
Member Data Documentation
initialized_
template<typename TService > bool smacc::client_bases::SmaccServiceServerClient< TService >::initialized_ private
Definition at line 71 of file smacc_service_server_client.h.
Referenced by smacc::client_bases::SmaccServiceServerClient< TService >::initialize(), and smacc::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient().
nh_
template<typename TService > ros::NodeHandle smacc::client_bases::SmaccServiceServerClient< TService >::nh_ protected
Definition at line 54 of file smacc_service_server_client.h.
Referenced by smacc::client_bases::SmaccServiceServerClient< TService >::initialize().
onServiceRequestReceived_
template<typename TService > smacc::SmaccSignal<bool(TServiceRequest&, std::shared_ptr<TServiceResponse>)> smacc::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived_
Definition at line 27 of file smacc_service_server_client.h.
Referenced by smacc::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived(), and smacc::client_bases::SmaccServiceServerClient< TService >::serviceCallback().
server_
template<typename TService > ros::ServiceServer smacc::client_bases::SmaccServiceServerClient< TService >::server_ private
Definition at line 70 of file smacc_service_server_client.h.
Referenced by smacc::client_bases::SmaccServiceServerClient< TService >::initialize(), and smacc::client_bases::SmaccServiceServerClient< TService >::~SmaccServiceServerClient().
serviceName_
template<typename TService > boost::optional<std::string> smacc::client_bases::SmaccServiceServerClient< TService >::serviceName_
Definition at line 17 of file smacc_service_server_client.h.
Referenced by smacc::client_bases::SmaccServiceServerClient< TService >::initialize(), and smacc::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient().
The documentation for this class was generated from the following file:
smacc/include/smacc/client_bases/smacc_service_server_client.h