SMACC: smacc::SmaccAsyncClientBehavior Class Reference
smacc::SmaccAsyncClientBehavior Class Reference
#include <smacc_asynchronous_client_behavior.h>
Public Member Functions
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Protected Member Functions
virtual void executeOnEntry () override
virtual void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Private Attributes
std::future< int > onEntryThread_
std::future< int > onExitThread_
std::function< void()> postFinishEventFn_
std::function< void()> postSuccessEventFn_
std::function< void()> postFailureEventFn_
SmaccSignal< void()> onFinished_
SmaccSignal< void()> onSuccess_
SmaccSignal< void()> onFailure_
Detailed Description
Definition at line 42 of file smacc_asynchronous_client_behavior.h.
Constructor & Destructor Documentation
~SmaccAsyncClientBehavior()
smacc::SmaccAsyncClientBehavior::~SmaccAsyncClientBehavior () virtual
Definition at line 69 of file smacc_client_async_behavior.cpp.
    {
    }
Member Function Documentation
dispose()
void smacc::SmaccAsyncClientBehavior::dispose () override protected virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 54 of file smacc_client_async_behavior.cpp.
    {
        ROS_DEBUG_STREAM("[" << getName() << "] Destroying client behavior- Waiting finishing of asynchronous onExit thread");
        try
        {
            this->onExitThread_.get();
        }
        catch (...)
        {
            ROS_DEBUG("[SmaccAsyncClientBehavior] trying to Join onExit function, but it was already finished.");
        }
        ROS_DEBUG_STREAM("[" << getName() << "] Destroying client behavior-  onExit thread finished. Proccedding destruction.");
    }
References smacc::ISmaccClientBehavior::getName(), and onExitThread_.
executeOnEntry()
void smacc::SmaccAsyncClientBehavior::executeOnEntry () override protected virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 5 of file smacc_client_async_behavior.cpp.
    {
        ROS_INFO_STREAM("[" << getName() << "] Creating asynchronous onEntry thread");
        this->onEntryThread_ = std::async(std::launch::async,
                                          [=] {
                                              this->onEntry();
                                              this->postFinishEventFn_();
                                              return 0;
                                          });
    }
References smacc::ISmaccClientBehavior::getName(), smacc::ISmaccClientBehavior::onEntry(), onEntryThread_, and postFinishEventFn_.
executeOnExit()
void smacc::SmaccAsyncClientBehavior::executeOnExit () override protected virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 16 of file smacc_client_async_behavior.cpp.
    {
        ROS_INFO_STREAM("[" << getName() << "] onExit - join async onEntry thread");
        try
        {
            ros::Rate r(200);
            while (ros::ok())
            {
                bool valid = this->onEntryThread_.valid();
                if (valid)
                {
                    auto status = this->onEntryThread_.wait_for(std::chrono::milliseconds(20));
                    if (status == std::future_status::ready)
                    {
                        this->onEntryThread_.get();
                        break;
                    }
                }
                r.sleep();
                ros::spinOnce();
                ROS_DEBUG("waiting for finishing client behavior");
            }
        }
        catch (const std::exception &e)
        {
            ROS_DEBUG("[SmaccAsyncClientBehavior] trying to Join onEntry function, but it was already finished.");
        }
        ROS_INFO_STREAM("[" << getName() << "] onExit - Creating asynchronous onExit thread");
        this->onExitThread_ = std::async(std::launch::async,
                                         [=] {
                                             this->onExit();
                                             return 0;
                                         });
    }
References smacc::ISmaccClientBehavior::getName(), onEntryThread_, smacc::ISmaccClientBehavior::onExit(), and onExitThread_.
onFailure()
template<typename TCallback , typename T > boost::signals2::connection smacc::SmaccAsyncClientBehavior::onFailure (TCallback callback, T * object)
Definition at line 46 of file smacc_asynchronous_client_behavior_impl.h.
    {
        return this->getStateMachine()->createSignalConnection(onFailure_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), smacc::ISmaccClientBehavior::getStateMachine(), and onFailure_.
onFinished()
template<typename TCallback , typename T > boost::signals2::connection smacc::SmaccAsyncClientBehavior::onFinished (TCallback callback, T * object)
Definition at line 40 of file smacc_asynchronous_client_behavior_impl.h.
    {
        return this->getStateMachine()->createSignalConnection(onFinished_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), smacc::ISmaccClientBehavior::getStateMachine(), and onFinished_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc::SmaccAsyncClientBehavior::onOrthogonalAllocation
Definition at line 15 of file smacc_asynchronous_client_behavior_impl.h.
    {
        postFinishEventFn_ = [=] {
            this->onFinished_();
            this->postEvent<EvCbFinished<TSourceObject, TOrthogonal>>();
        };
        postSuccessEventFn_ = [=] {
            this->onSuccess_();
            this->postEvent<EvCbSuccess<TSourceObject, TOrthogonal>>();
        };
        postFailureEventFn_ = [=] {
            this->onFailure_();
            this->postEvent<EvCbFailure<TSourceObject, TOrthogonal>>();
        };
    }
References onFailure_, onFinished_, onSuccess_, postFailureEventFn_, postFinishEventFn_, and postSuccessEventFn_.
onSuccess()
template<typename TCallback , typename T > boost::signals2::connection smacc::SmaccAsyncClientBehavior::onSuccess (TCallback callback, T * object)
Definition at line 34 of file smacc_asynchronous_client_behavior_impl.h.
    {
        return this->getStateMachine()->createSignalConnection(onSuccess_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), smacc::ISmaccClientBehavior::getStateMachine(), and onSuccess_.
postFailureEvent()
void smacc::SmaccAsyncClientBehavior::postFailureEvent () protected
Definition at line 78 of file smacc_client_async_behavior.cpp.
    {
        postFailureEventFn_();
    }
References postFailureEventFn_.
Referenced by cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_move_group_interface::CbMoveJoints::moveJoints(), cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative(), cl_move_group_interface::CbMoveCartesianRelative::moveRelativeCartesian(), cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), and cl_move_base_z::CbMoveBaseClientBehaviorBase::propagateFailureEvent().
postSuccessEvent()
void smacc::SmaccAsyncClientBehavior::postSuccessEvent () protected
Definition at line 73 of file smacc_client_async_behavior.cpp.
    {
        postSuccessEventFn_();
    }
References postSuccessEventFn_.
Referenced by cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_move_group_interface::CbMoveJoints::moveJoints(), cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative(), cl_move_group_interface::CbMoveCartesianRelative::moveRelativeCartesian(), cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose(), and cl_move_base_z::CbMoveBaseClientBehaviorBase::propagateSuccessEvent().
Member Data Documentation
onEntryThread_
std::future<int> smacc::SmaccAsyncClientBehavior::onEntryThread_ private
Definition at line 69 of file smacc_asynchronous_client_behavior.h.
Referenced by executeOnEntry(), and executeOnExit().
onExitThread_
std::future<int> smacc::SmaccAsyncClientBehavior::onExitThread_ private
Definition at line 70 of file smacc_asynchronous_client_behavior.h.
Referenced by dispose(), and executeOnExit().
onFailure_
SmaccSignal<void()> smacc::SmaccAsyncClientBehavior::onFailure_ private
Definition at line 78 of file smacc_asynchronous_client_behavior.h.
Referenced by onFailure(), and onOrthogonalAllocation().
onFinished_
SmaccSignal<void()> smacc::SmaccAsyncClientBehavior::onFinished_ private
Definition at line 76 of file smacc_asynchronous_client_behavior.h.
Referenced by onFinished(), and onOrthogonalAllocation().
onSuccess_
SmaccSignal<void()> smacc::SmaccAsyncClientBehavior::onSuccess_ private
Definition at line 77 of file smacc_asynchronous_client_behavior.h.
Referenced by onOrthogonalAllocation(), and onSuccess().
postFailureEventFn_
std::function<void()> smacc::SmaccAsyncClientBehavior::postFailureEventFn_ private
Definition at line 74 of file smacc_asynchronous_client_behavior.h.
Referenced by onOrthogonalAllocation(), and postFailureEvent().
postFinishEventFn_
std::function<void()> smacc::SmaccAsyncClientBehavior::postFinishEventFn_ private
Definition at line 72 of file smacc_asynchronous_client_behavior.h.
Referenced by executeOnEntry(), and onOrthogonalAllocation().
postSuccessEventFn_
std::function<void()> smacc::SmaccAsyncClientBehavior::postSuccessEventFn_ private
Definition at line 73 of file smacc_asynchronous_client_behavior.h.
Referenced by onOrthogonalAllocation(), and postSuccessEvent().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_asynchronous_client_behavior.h
smacc/include/smacc/impl/smacc_asynchronous_client_behavior_impl.h
smacc/src/smacc/smacc_client_async_behavior.cpp