SMACC: smacc::components::CpTopicSubscriber< MessageType > Class Template Reference
smacc::components::CpTopicSubscriber< MessageType > Class Template Reference
#include <cp_topic_subscriber.h>
Public Types
typedef MessageType TMessageType
Public Member Functions
CpTopicSubscriber ()
CpTopicSubscriber (std::string topicname)
virtual ~CpTopicSubscriber ()
template<typename T >
boost::signals2::connection onMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename T >
boost::signals2::connection onFirstMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void initialize ()
Public Member Functions inherited from smacc::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Attributes
boost::optional< std::string > topicName
boost::optional< int > queueSize
smacc::SmaccSignal< void(const MessageType &)> onFirstMessageReceived_
smacc::SmaccSignal< void(const MessageType &)> onMessageReceived_
std::function< void(const MessageType &)> postMessageEvent
std::function< void(const MessageType &)> postInitialMessageEvent
Protected Attributes
ros::NodeHandle nh_
Protected Attributes inherited from smacc::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Private Member Functions
void messageCallback (const MessageType &msg)
Private Attributes
ros::Subscriber sub_
bool firstMessage_
bool initialized_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccComponent
virtual void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
virtual void onInitialize ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
Detailed Description
template<typename MessageType>
class smacc::components::CpTopicSubscriber< MessageType >
Definition at line 15 of file cp_topic_subscriber.h.
Member Typedef Documentation
TMessageType
template<typename MessageType > typedef MessageType smacc::components::CpTopicSubscriber< MessageType >::TMessageType
Definition at line 21 of file cp_topic_subscriber.h.
Constructor & Destructor Documentation
CpTopicSubscriber() [1/2]
template<typename MessageType > smacc::components::CpTopicSubscriber< MessageType >::CpTopicSubscriber () inline
Definition at line 23 of file cp_topic_subscriber.h.
    {
        initialized_ = false;
    }
References smacc::components::CpTopicSubscriber< MessageType >::initialized_.
CpTopicSubscriber() [2/2]
template<typename MessageType > smacc::components::CpTopicSubscriber< MessageType >::CpTopicSubscriber (std::string topicname) inline
Definition at line 28 of file cp_topic_subscriber.h.
    {
        topicName = topicname;
    }
References smacc::components::CpTopicSubscriber< MessageType >::topicName.
~CpTopicSubscriber()
template<typename MessageType > virtual smacc::components::CpTopicSubscriber< MessageType >::~CpTopicSubscriber () inline virtual
Definition at line 33 of file cp_topic_subscriber.h.
    {
        sub_.shutdown();
    }
References smacc::components::CpTopicSubscriber< MessageType >::sub_.
Member Function Documentation
initialize()
template<typename MessageType > virtual void smacc::components::CpTopicSubscriber< MessageType >::initialize () inline virtual
Definition at line 72 of file cp_topic_subscriber.h.
    {
        if (!initialized_)
        {
            firstMessage_ = true;
            if (!queueSize)
                queueSize = 1;
            if (!topicName)
            {
                ROS_ERROR("topic client with no topic name set. Skipping subscribing");
            }
            else
            {
                ROS_INFO_STREAM("[" << this->getName() << "] Subscribing to topic: " << topicName);
                sub_ = nh_.subscribe(*topicName, *queueSize, &CpTopicSubscriber<MessageType>::messageCallback, this);
                this->initialized_ = true;
            }
        }
    }
References smacc::components::CpTopicSubscriber< MessageType >::firstMessage_, smacc::ISmaccComponent::getName(), smacc::components::CpTopicSubscriber< MessageType >::initialized_, smacc::components::CpTopicSubscriber< MessageType >::nh_, smacc::components::CpTopicSubscriber< MessageType >::queueSize, smacc::components::CpTopicSubscriber< MessageType >::sub_, and smacc::components::CpTopicSubscriber< MessageType >::topicName.
messageCallback()
template<typename MessageType > void smacc::components::CpTopicSubscriber< MessageType >::messageCallback (const MessageType & msg) inline private
Definition at line 103 of file cp_topic_subscriber.h.
    {
        if (firstMessage_)
        {
            postInitialMessageEvent(msg);
            onFirstMessageReceived_(msg);
            firstMessage_ = false;
        }
        postMessageEvent(msg);
        onMessageReceived_(msg);
    }
References smacc::components::CpTopicSubscriber< MessageType >::firstMessage_, battery_monitor_node::msg, smacc::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived_, smacc::components::CpTopicSubscriber< MessageType >::onMessageReceived_, smacc::components::CpTopicSubscriber< MessageType >::postInitialMessageEvent, and smacc::components::CpTopicSubscriber< MessageType >::postMessageEvent.
onFirstMessageReceived()
template<typename MessageType > template<typename T > boost::signals2::connection smacc::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived (void(T::*)(const MessageType &) callback, T * object) inline
Definition at line 51 of file cp_topic_subscriber.h.
    {
        return this->getStateMachine()->createSignalConnection(onFirstMessageReceived_, callback, object);
    }
References smacc::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived_.
onMessageReceived()
template<typename MessageType > template<typename T > boost::signals2::connection smacc::components::CpTopicSubscriber< MessageType >::onMessageReceived (void(T::*)(const MessageType &) callback, T * object) inline
Definition at line 45 of file cp_topic_subscriber.h.
    {
        return this->getStateMachine()->createSignalConnection(onMessageReceived_, callback, object);
    }
References smacc::components::CpTopicSubscriber< MessageType >::onMessageReceived_.
onOrthogonalAllocation()
template<typename MessageType > template<typename TOrthogonal , typename TSourceObject > void smacc::components::CpTopicSubscriber< MessageType >::onOrthogonalAllocation () inline
Definition at line 57 of file cp_topic_subscriber.h.
    {
        this->postMessageEvent = [=](auto msg) {
            auto event = new EvTopicMessage<TSourceObject, TOrthogonal>();
            event->msgData = msg;
            this->postEvent(event);
        };
        this->postInitialMessageEvent = [=](auto msg) {
            auto event = new EvTopicInitialMessage<TSourceObject, TOrthogonal>();
            event->msgData = msg;
            this->postEvent(event);
        };
    }
References battery_monitor_node::msg, and smacc::ISmaccComponent::postEvent().
Member Data Documentation
firstMessage_
template<typename MessageType > bool smacc::components::CpTopicSubscriber< MessageType >::firstMessage_ private
Definition at line 100 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::initialize(), and smacc::components::CpTopicSubscriber< MessageType >::messageCallback().
initialized_
template<typename MessageType > bool smacc::components::CpTopicSubscriber< MessageType >::initialized_ private
Definition at line 101 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::CpTopicSubscriber(), and smacc::components::CpTopicSubscriber< MessageType >::initialize().
nh_
template<typename MessageType > ros::NodeHandle smacc::components::CpTopicSubscriber< MessageType >::nh_ protected
Definition at line 96 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::initialize().
onFirstMessageReceived_
template<typename MessageType > smacc::SmaccSignal<void(const MessageType &)> smacc::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived_
Definition at line 38 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::messageCallback(), and smacc::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived().
onMessageReceived_
template<typename MessageType > smacc::SmaccSignal<void(const MessageType &)> smacc::components::CpTopicSubscriber< MessageType >::onMessageReceived_
Definition at line 39 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::messageCallback(), and smacc::components::CpTopicSubscriber< MessageType >::onMessageReceived().
postInitialMessageEvent
template<typename MessageType > std::function<void(const MessageType &)> smacc::components::CpTopicSubscriber< MessageType >::postInitialMessageEvent
Definition at line 42 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::messageCallback().
postMessageEvent
template<typename MessageType > std::function<void(const MessageType &)> smacc::components::CpTopicSubscriber< MessageType >::postMessageEvent
Definition at line 41 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::messageCallback().
queueSize
template<typename MessageType > boost::optional<int> smacc::components::CpTopicSubscriber< MessageType >::queueSize
Definition at line 19 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::initialize().
sub_
template<typename MessageType > ros::Subscriber smacc::components::CpTopicSubscriber< MessageType >::sub_ private
Definition at line 99 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::initialize(), and smacc::components::CpTopicSubscriber< MessageType >::~CpTopicSubscriber().
topicName
template<typename MessageType > boost::optional<std::string> smacc::components::CpTopicSubscriber< MessageType >::topicName
Definition at line 18 of file cp_topic_subscriber.h.
Referenced by smacc::components::CpTopicSubscriber< MessageType >::CpTopicSubscriber(), and smacc::components::CpTopicSubscriber< MessageType >::initialize().
The documentation for this class was generated from the following file:
smacc/include/smacc/client_base_components/cp_topic_subscriber.h