SMACC: smacc_rviz_plugin::SmaccRvizDisplay Class Reference
smacc_rviz_plugin::SmaccRvizDisplay Class Reference
#include <smacc_rviz_display.h>
Public Member Functions
SmaccRvizDisplay ()
virtual ~SmaccRvizDisplay ()
virtual void subscribe ()
virtual void unsubscribe ()
Protected Member Functions
virtual void onInitialize ()
virtual void reset ()
Private Slots
void updateCurrentState ()
void updateTopic ()
Private Member Functions
void processMessage (const smacc_msgs::SmaccStatus::ConstPtr &msg)
Private Attributes
rviz::StringProperty * current_state_
rviz::RosTopicProperty * topic_property_
ros::NodeHandle nh_
ros::Subscriber sub_
Detailed Description
Definition at line 72 of file smacc_rviz_display.h.
Constructor & Destructor Documentation
SmaccRvizDisplay()
smacc_rviz_plugin::SmaccRvizDisplay::SmaccRvizDisplay ()
Definition at line 51 of file smacc_rviz_display.cpp.
{
  /*
  color_property_ = new rviz::ColorProperty( "Color", QColor( 204, 51, 204 ),
                                             "Color to draw the acceleration arrows.",
                                             this, SLOT( updateColorAndAlpha() ));
  alpha_property_ = new rviz::FloatProperty( "Alpha", 1.0,
                                             "0 is fully transparent, 1.0 is fully opaque.",
                                             this, SLOT( updateColorAndAlpha() ));
  history_length_property_ = new rviz::IntProperty( "History length", 1,
                                                    "Number of prior measurements to display.",
                                                    this, SLOT( updateHistoryLength() ));
                                                    */
  current_state_ = new rviz::StringProperty( "CurrentState", "",
                                                    "current smacc state",
                                                    this, SLOT( updateCurrentState() ));
  topic_property_ = new rviz::RosTopicProperty( "Topic", "",
                                            "", "",
                                            this, SLOT( updateTopic() ));
  QString message_type = QString::fromStdString( ros::message_traits::datatype<smacc_msgs::SmaccStatus>() );
      topic_property_->setMessageType( message_type );
      topic_property_->setDescription( message_type + " topic to subscribe to." );
  //history_length_property_->setMin( 1 );
  //history_length_property_->setMax( 100000 );
}
References current_state_, topic_property_, updateCurrentState(), and updateTopic().
~SmaccRvizDisplay()
smacc_rviz_plugin::SmaccRvizDisplay::~SmaccRvizDisplay () virtual
Definition at line 122 of file smacc_rviz_display.cpp.
{
}
Member Function Documentation
onInitialize()
void smacc_rviz_plugin::SmaccRvizDisplay::onInitialize () protected virtual
Definition at line 116 of file smacc_rviz_display.cpp.
{
  //MFDClass::onInitialize();
  current_state_->setValue(QString(""));
}
References current_state_.
processMessage()
void smacc_rviz_plugin::SmaccRvizDisplay::processMessage (const smacc_msgs::SmaccStatus::ConstPtr & msg) private
Definition at line 139 of file smacc_rviz_display.cpp.
{
  std::string concatenated;
  for(auto& state: msg->current_states)
  {
    concatenated = concatenated + std::string("/")+ state;
  }
  ROS_DEBUG("current state: %s", concatenated.c_str());
  current_state_->setValue(QString(concatenated.c_str()));
  // Here we call the rviz::FrameManager to get the transform from the
  // fixed frame to the frame in the header of this Imu message.  If
  // it fails, we can't do anything else so we return.
  /*
  Ogre::Quaternion orientation;
  Ogre::Vector3 position;
  if( !context_->getFrameManager()->getTransform( msg->header.frame_id,
                                                  msg->header.stamp,
                                                  position, orientation ))
  {
    ROS_DEBUG( "Error transforming from frame '%s' to frame '%s'",
               msg->header.frame_id.c_str(), qPrintable( fixed_frame_ ));
    return;
  }
  // We are keeping a circular buffer of visual pointers.  This gets
  // the next one, or creates and stores it if the buffer is not full
  boost::shared_ptr<ImuVisual> visual;
  if( visuals_.full() )
  {
    visual = visuals_.front();
  }
  else
  {
    visual.reset(new ImuVisual( context_->getSceneManager(), scene_node_ ));
  }*/
  // Now set or update the contents of the chosen visual.
  //visual->setMessage( msg );
  //visual->setFramePosition( position );
  //visual->setFrameOrientation( orientation );
  /*
  float alpha = alpha_property_->getFloat();
  Ogre::ColourValue color = color_property_->getOgreColor();
  visual->setColor( color.r, color.g, color.b, alpha );
  // And send it to the end of the circular buffer
  visuals_.push_back(visual);
  */
}
References current_state_, and battery_monitor_node::msg.
Referenced by subscribe().
reset()
void smacc_rviz_plugin::SmaccRvizDisplay::reset () protected virtual
Definition at line 127 of file smacc_rviz_display.cpp.
{
  //MFDClass::reset();
  //visuals_.clear();
  current_state_->setValue(QString(""));
}
References current_state_.
Referenced by updateTopic().
subscribe()
void smacc_rviz_plugin::SmaccRvizDisplay::subscribe () virtual
Definition at line 94 of file smacc_rviz_display.cpp.
  {
      current_state_->setValue(QString(""));
      sub_ = nh_.subscribe<smacc_msgs::SmaccStatus>(topic_property_->getTopic().toStdString(), 1, &SmaccRvizDisplay::processMessage , this);
  }
References current_state_, nh_, processMessage(), sub_, and topic_property_.
Referenced by updateTopic().
unsubscribe()
void smacc_rviz_plugin::SmaccRvizDisplay::unsubscribe () virtual
Definition at line 100 of file smacc_rviz_display.cpp.
  {
    current_state_->setValue(QString(""));
    sub_.shutdown();
  }
References current_state_, and sub_.
Referenced by updateTopic().
updateCurrentState
void smacc_rviz_plugin::SmaccRvizDisplay::updateCurrentState () private slot
Definition at line 134 of file smacc_rviz_display.cpp.
{
}
Referenced by SmaccRvizDisplay().
updateTopic
void smacc_rviz_plugin::SmaccRvizDisplay::updateTopic () private slot
Definition at line 86 of file smacc_rviz_display.cpp.
  {
    unsubscribe();
    reset();
    subscribe();
    context_->queueRender();
  }
References reset(), subscribe(), and unsubscribe().
Referenced by SmaccRvizDisplay().
Member Data Documentation
current_state_
rviz::StringProperty* smacc_rviz_plugin::SmaccRvizDisplay::current_state_ private
Definition at line 116 of file smacc_rviz_display.h.
Referenced by onInitialize(), processMessage(), reset(), SmaccRvizDisplay(), subscribe(), and unsubscribe().
nh_
ros::NodeHandle smacc_rviz_plugin::SmaccRvizDisplay::nh_ private
Definition at line 118 of file smacc_rviz_display.h.
Referenced by subscribe().
sub_
ros::Subscriber smacc_rviz_plugin::SmaccRvizDisplay::sub_ private
Definition at line 119 of file smacc_rviz_display.h.
Referenced by subscribe(), and unsubscribe().
topic_property_
rviz::RosTopicProperty* smacc_rviz_plugin::SmaccRvizDisplay::topic_property_ private
Definition at line 117 of file smacc_rviz_display.h.
Referenced by SmaccRvizDisplay(), and subscribe().
The documentation for this class was generated from the following files:
smacc_diagnostics/smacc_rviz_plugin/src/smacc_rviz_display.h
smacc_diagnostics/smacc_rviz_plugin/src/smacc_rviz_display.cpp