SMACC: cl_ros_timer::ClRosTimer Class Reference
cl_ros_timer::ClRosTimer Class Reference
#include <cl_ros_timer.h>
Public Member Functions
ClRosTimer (ros::Duration duration, bool oneshot=false)
virtual ~ClRosTimer ()
virtual void initialize ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Protected Member Functions
void timerCallback (const ros::TimerEvent &timedata)
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Protected Attributes
ros::NodeHandle nh_
ros::Timer timer
ros::Duration duration
bool oneshot
std::function< void()> postTimerEvent_
smacc::SmaccSignal< void()> onTimerTick_
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Detailed Description
Definition at line 24 of file cl_ros_timer.h.
Constructor & Destructor Documentation
ClRosTimer()
cl_ros_timer::ClRosTimer::ClRosTimer (ros::Duration duration, bool oneshot = false)
Definition at line 6 of file timer_client.cpp.
{
    this->duration = duration;
    this->oneshot = oneshot;
}
References duration, and oneshot.
~ClRosTimer()
cl_ros_timer::ClRosTimer::~ClRosTimer () virtual
Definition at line 12 of file timer_client.cpp.
{
    timer.stop();
}
References timer.
Member Function Documentation
initialize()
void cl_ros_timer::ClRosTimer::initialize () virtual
Reimplemented from smacc::ISmaccClient.
Definition at line 17 of file timer_client.cpp.
{
    timer = nh_.createTimer(duration, boost::bind(&ClRosTimer::timerCallback, this, _1), oneshot);
}
References duration, nh_, oneshot, timer, and timerCallback().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_ros_timer::ClRosTimer::onOrthogonalAllocation () inline
Definition at line 40 of file cl_ros_timer.h.
    {
        this->postTimerEvent_ = [=]() {
            this->postEvent<EvTimer<TSourceObject, TOrthogonal>>();
        };
    }
References postTimerEvent_.
onTimerTick()
template<typename T > boost::signals2::connection cl_ros_timer::ClRosTimer::onTimerTick (void(T::*)() callback, T * object) inline
Definition at line 34 of file cl_ros_timer.h.
    {
        return this->getStateMachine()->createSignalConnection(onTimerTick_, callback, object);
    }
References smacc::ISmaccStateMachine::createSignalConnection(), smacc::ISmaccClient::getStateMachine(), and onTimerTick_.
Referenced by cl_ros_timer::CbTimer::onEntry(), cl_ros_timer::CbTimerCountdownLoop::onEntry(), cl_ros_timer::CbTimerCountdownOnce::onEntry(), sm_atomic_cb::State1::runtimeConfigure(), and sm_atomic_cb::State2::runtimeConfigure().
timerCallback()
void cl_ros_timer::ClRosTimer::timerCallback (const ros::TimerEvent & timedata) protected
Definition at line 22 of file timer_client.cpp.
{
    if (!onTimerTick_.empty())
    {
        this->onTimerTick_();
    }
    postTimerEvent_();
}
References onTimerTick_, and postTimerEvent_.
Referenced by initialize().
Member Data Documentation
duration
ros::Duration cl_ros_timer::ClRosTimer::duration protected
Definition at line 51 of file cl_ros_timer.h.
Referenced by ClRosTimer(), and initialize().
nh_
ros::NodeHandle cl_ros_timer::ClRosTimer::nh_ protected
Definition at line 48 of file cl_ros_timer.h.
Referenced by initialize().
oneshot
bool cl_ros_timer::ClRosTimer::oneshot protected
Definition at line 52 of file cl_ros_timer.h.
Referenced by ClRosTimer(), and initialize().
onTimerTick_
smacc::SmaccSignal<void()> cl_ros_timer::ClRosTimer::onTimerTick_ protected
Definition at line 56 of file cl_ros_timer.h.
Referenced by onTimerTick(), and timerCallback().
postTimerEvent_
std::function<void()> cl_ros_timer::ClRosTimer::postTimerEvent_ protected
Definition at line 55 of file cl_ros_timer.h.
Referenced by onOrthogonalAllocation(), and timerCallback().
timer
ros::Timer cl_ros_timer::ClRosTimer::timer protected
Definition at line 50 of file cl_ros_timer.h.
Referenced by initialize(), and ~ClRosTimer().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/cl_ros_timer.h
smacc_client_library/ros_timer_client/src/ros_timer_client/timer_client.cpp