SMACC: cl_keyboard::ClKeyboard Class Reference
cl_keyboard::ClKeyboard Class Reference
#include <cl_keyboard.h>
Public Member Functions
template<typename T >
void OnKeyPress (void(T::*callback)(char keypress), T *object)
ClKeyboard ()
virtual ~ClKeyboard ()
virtual void initialize () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onKeyboardMessage (const std_msgs::UInt16 &unicode_keychar)
template<typename TEv >
void postKeyEvent ()
Public Member Functions inherited from smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >
SmaccSubscriberClient ()
SmaccSubscriberClient (std::string topicname)
virtual ~SmaccSubscriberClient ()
boost::signals2::connection onMessageReceived (void(T::*callback)(const std_msgs::UInt16 &), T *object)
boost::signals2::connection onFirstMessageReceived (void(T::*callback)(const std_msgs::UInt16 &), T *object)
void onOrthogonalAllocation ()
virtual void initialize ()
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Public Attributes
smacc::SmaccSignal< void(char keypress)> OnKeyPress_
std::function< void(std_msgs::UInt16)> postEventKeyPress
Public Attributes inherited from smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >
boost::optional< std::string > topicName
boost::optional< int > queueSize
smacc::SmaccSignal< void(const std_msgs::UInt16 &)> onFirstMessageReceived_
smacc::SmaccSignal< void(const std_msgs::UInt16 &)> onMessageReceived_
std::function< void(const std_msgs::UInt16 &)> postMessageEvent
std::function< void(const std_msgs::UInt16 &)> postInitialMessageEvent
Private Attributes
bool initialized_
Additional Inherited Members
Public Types inherited from smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >
typedef std_msgs::UInt16 TMessageType
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Protected Attributes inherited from smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >
ros::NodeHandle nh_
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Detailed Description
Definition at line 148 of file cl_keyboard.h.
Constructor & Destructor Documentation
ClKeyboard()
cl_keyboard::ClKeyboard::ClKeyboard ()
Definition at line 4 of file cl_keyboard.cpp.
                       {
  initialized_ = false;
  topicName = "/keyboard_unicode";
}
References initialized_, and smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >::topicName.
~ClKeyboard()
cl_keyboard::ClKeyboard::~ClKeyboard () virtual
Definition at line 9 of file cl_keyboard.cpp.
{
}
Member Function Documentation
initialize()
void cl_keyboard::ClKeyboard::initialize () override virtual
Reimplemented from smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >.
Definition at line 14 of file cl_keyboard.cpp.
{
  SmaccSubscriberClient<std_msgs::UInt16>::initialize();
  if (!this->initialized_) {
    this->onMessageReceived(&ClKeyboard::onKeyboardMessage, this);
    this->initialized_ = true;
  }
}
References smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >::initialize(), initialized_, onKeyboardMessage(), and smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >::onMessageReceived().
onKeyboardMessage()
void cl_keyboard::ClKeyboard::onKeyboardMessage (const std_msgs::UInt16 & unicode_keychar)
Definition at line 24 of file cl_keyboard.cpp.
{
  postEventKeyPress(unicode_keychar);
}
References postEventKeyPress.
Referenced by initialize().
OnKeyPress()
template<typename T > void cl_keyboard::ClKeyboard::OnKeyPress (void(T::*)(char keypress) callback, T * object) inline
Definition at line 154 of file cl_keyboard.h.
        {
                //this->connectSignal(OnKeyPress_, callback, object);
                this->getStateMachine()->createSignalConnection(OnKeyPress_, callback, object);
        }
References smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
Referenced by cl_keyboard::CbDefaultKeyboardBehavior::onEntry().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_keyboard::ClKeyboard::onOrthogonalAllocation () inline
Definition at line 169 of file cl_keyboard.h.
        {
                // call to the base configuration to properly handling the message and initial message smacc events
                smacc::client_bases::SmaccSubscriberClient<std_msgs::UInt16>::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
                postEventKeyPress = [=](auto unicode_keychar) {
                        char character = (char)unicode_keychar.data;
                        ROS_WARN("detected keyboard: %c", character);
                        if (character == 'a')
                                this->postKeyEvent<EvKeyPressA<ClKeyboard, TOrthogonal>>();
                        else if (character == 'b')
                                this->postKeyEvent<EvKeyPressB<ClKeyboard, TOrthogonal>>();
                        else if (character == 'c')
                                this->postKeyEvent<EvKeyPressC<ClKeyboard, TOrthogonal>>();
                        else if (character == 'd')
                                this->postKeyEvent<EvKeyPressD<ClKeyboard, TOrthogonal>>();
                        else if (character == 'e')
                                this->postKeyEvent<EvKeyPressE<ClKeyboard, TOrthogonal>>();
                        else if (character == 'f')
                                this->postKeyEvent<EvKeyPressF<ClKeyboard, TOrthogonal>>();
                        else if (character == 'g')
                                this->postKeyEvent<EvKeyPressG<ClKeyboard, TOrthogonal>>();
                        else if (character == 'h')
                                this->postKeyEvent<EvKeyPressH<ClKeyboard, TOrthogonal>>();
                        else if (character == 'y')
                                this->postKeyEvent<EvKeyPressI<ClKeyboard, TOrthogonal>>();
                        else if (character == 'j')
                                this->postKeyEvent<EvKeyPressJ<ClKeyboard, TOrthogonal>>();
                        else if (character == 'k')
                                this->postKeyEvent<EvKeyPressK<ClKeyboard, TOrthogonal>>();
                        else if (character == 'l')
                                this->postKeyEvent<EvKeyPressL<ClKeyboard, TOrthogonal>>();
                        else if (character == 'm')
                                this->postKeyEvent<EvKeyPressM<ClKeyboard, TOrthogonal>>();
                        else if (character == 'n')
                                this->postKeyEvent<EvKeyPressN<ClKeyboard, TOrthogonal>>();
                        else if (character == 'o')
                                this->postKeyEvent<EvKeyPressO<ClKeyboard, TOrthogonal>>();
                        else if (character == 'p')
                                this->postKeyEvent<EvKeyPressP<ClKeyboard, TOrthogonal>>();
                        else if (character == 'q')
                                this->postKeyEvent<EvKeyPressQ<ClKeyboard, TOrthogonal>>();
                        else if (character == 'r')
                                this->postKeyEvent<EvKeyPressR<ClKeyboard, TOrthogonal>>();
                        else if (character == 's')
                                this->postKeyEvent<EvKeyPressS<ClKeyboard, TOrthogonal>>();
                        else if (character == 't')
                                this->postKeyEvent<EvKeyPressT<ClKeyboard, TOrthogonal>>();
                        else if (character == 'u')
                                this->postKeyEvent<EvKeyPressU<ClKeyboard, TOrthogonal>>();
                        else if (character == 'v')
                                this->postKeyEvent<EvKeyPressV<ClKeyboard, TOrthogonal>>();
                        else if (character == 'w')
                                this->postKeyEvent<EvKeyPressW<ClKeyboard, TOrthogonal>>();
                        else if (character == 'x')
                                this->postKeyEvent<EvKeyPressX<ClKeyboard, TOrthogonal>>();
                        else if (character == 'y')
                                this->postKeyEvent<EvKeyPressY<ClKeyboard, TOrthogonal>>();
                        else if (character == 'z')
                                this->postKeyEvent<EvKeyPressZ<ClKeyboard, TOrthogonal>>();
                        OnKeyPress_(character); /*  */
                };
        }
References OnKeyPress_, and postEventKeyPress.
postKeyEvent()
template<typename TEv > void cl_keyboard::ClKeyboard::postKeyEvent () inline
Definition at line 237 of file cl_keyboard.h.
        {
                ROS_WARN("ClKeyboard ev: %s", smacc::demangleSymbol(typeid(TEv).name()).c_str());
                this->postEvent<TEv>();
        }
References smacc::introspection::demangleSymbol().
Member Data Documentation
initialized_
bool cl_keyboard::ClKeyboard::initialized_ private
Definition at line 244 of file cl_keyboard.h.
Referenced by ClKeyboard(), and initialize().
OnKeyPress_
smacc::SmaccSignal<void(char keypress)> cl_keyboard::ClKeyboard::OnKeyPress_
Definition at line 151 of file cl_keyboard.h.
Referenced by onOrthogonalAllocation().
postEventKeyPress
std::function<void(std_msgs::UInt16)> cl_keyboard::ClKeyboard::postEventKeyPress
Definition at line 166 of file cl_keyboard.h.
Referenced by onKeyboardMessage(), and onOrthogonalAllocation().
The documentation for this class was generated from the following files:
smacc_client_library/keyboard_client/include/keyboard_client/cl_keyboard.h
smacc_client_library/keyboard_client/src/keyboard_client/cl_keyboard.cpp