SMACC: smacc::client_bases::SmaccSubscriberClient< MessageType > Class Template Reference
smacc::client_bases::SmaccSubscriberClient< MessageType > Class Template Reference
#include <smacc_subscriber_client.h>
Public Types
typedef MessageType TMessageType
Public Member Functions
SmaccSubscriberClient ()
SmaccSubscriberClient (std::string topicname)
virtual ~SmaccSubscriberClient ()
template<typename T >
boost::signals2::connection onMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename T >
boost::signals2::connection onFirstMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void initialize ()
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Public Attributes
boost::optional< std::string > topicName
boost::optional< int > queueSize
smacc::SmaccSignal< void(const MessageType &)> onFirstMessageReceived_
smacc::SmaccSignal< void(const MessageType &)> onMessageReceived_
std::function< void(const MessageType &)> postMessageEvent
std::function< void(const MessageType &)> postInitialMessageEvent
Protected Attributes
ros::NodeHandle nh_
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Private Member Functions
void messageCallback (const MessageType &msg)
Private Attributes
ros::Subscriber sub_
bool firstMessage_
bool initialized_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Detailed Description
template<typename MessageType>
class smacc::client_bases::SmaccSubscriberClient< MessageType >
Definition at line 22 of file smacc_subscriber_client.h.
Member Typedef Documentation
TMessageType
template<typename MessageType > typedef MessageType smacc::client_bases::SmaccSubscriberClient< MessageType >::TMessageType
Definition at line 28 of file smacc_subscriber_client.h.
Constructor & Destructor Documentation
SmaccSubscriberClient() [1/2]
template<typename MessageType > smacc::client_bases::SmaccSubscriberClient< MessageType >::SmaccSubscriberClient () inline
Definition at line 30 of file smacc_subscriber_client.h.
  {
    initialized_ = false;
  }
References smacc::client_bases::SmaccSubscriberClient< MessageType >::initialized_.
SmaccSubscriberClient() [2/2]
template<typename MessageType > smacc::client_bases::SmaccSubscriberClient< MessageType >::SmaccSubscriberClient (std::string topicname) inline
Definition at line 35 of file smacc_subscriber_client.h.
  {
    topicName = topicname;
  }
References smacc::client_bases::SmaccSubscriberClient< MessageType >::topicName.
~SmaccSubscriberClient()
template<typename MessageType > virtual smacc::client_bases::SmaccSubscriberClient< MessageType >::~SmaccSubscriberClient () inline virtual
Definition at line 40 of file smacc_subscriber_client.h.
  {
    sub_.shutdown();
  }
References smacc::client_bases::SmaccSubscriberClient< MessageType >::sub_.
Member Function Documentation
initialize()
template<typename MessageType > virtual void smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize () inline virtual
Reimplemented from smacc::ISmaccClient.
Reimplemented in cl_keyboard::ClKeyboard, cl_multirole_sensor::ClMultiroleSensor< MessageType >, cl_multirole_sensor::ClMultiroleSensor< sensor_msgs::LaserScan >, and cl_multirole_sensor::ClMultiroleSensor< sensor_msgs::Temperature >.
Definition at line 79 of file smacc_subscriber_client.h.
  {
    if (!initialized_)
    {
      firstMessage_ = true;
      if (!queueSize)
        queueSize = 1;
      if (!topicName)
      {
        ROS_ERROR("topic client with no topic name set. Skipping subscribing");
      }
      else
      {
        ROS_INFO_STREAM("[" << this->getName() << "] Subscribing to topic: " << topicName);
        sub_ = nh_.subscribe(*topicName, *queueSize, &SmaccSubscriberClient<MessageType>::messageCallback, this);
        this->initialized_ = true;
      }
    }
  }
References smacc::client_bases::SmaccSubscriberClient< MessageType >::firstMessage_, smacc::ISmaccClient::getName(), smacc::client_bases::SmaccSubscriberClient< MessageType >::initialized_, smacc::client_bases::SmaccSubscriberClient< MessageType >::nh_, smacc::client_bases::SmaccSubscriberClient< MessageType >::queueSize, smacc::client_bases::SmaccSubscriberClient< MessageType >::sub_, and smacc::client_bases::SmaccSubscriberClient< MessageType >::topicName.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialize().
messageCallback()
template<typename MessageType > void smacc::client_bases::SmaccSubscriberClient< MessageType >::messageCallback (const MessageType & msg) inline private
Definition at line 110 of file smacc_subscriber_client.h.
  {
    if (firstMessage_)
    {
      postInitialMessageEvent(msg);
      onFirstMessageReceived_(msg);
      firstMessage_ = false;
    }
    onMessageReceived_(msg);
    postMessageEvent(msg);
  }
References smacc::client_bases::SmaccSubscriberClient< MessageType >::firstMessage_, battery_monitor_node::msg, smacc::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived_, smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived_, smacc::client_bases::SmaccSubscriberClient< MessageType >::postInitialMessageEvent, and smacc::client_bases::SmaccSubscriberClient< MessageType >::postMessageEvent.
onFirstMessageReceived()
template<typename MessageType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived (void(T::*)(const MessageType &) callback, T * object) inline
Definition at line 58 of file smacc_subscriber_client.h.
  {
    return this->getStateMachine()->createSignalConnection(onFirstMessageReceived_, callback, object);
  }
References callback(), smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
onMessageReceived()
template<typename MessageType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived (void(T::*)(const MessageType &) callback, T * object) inline
Definition at line 52 of file smacc_subscriber_client.h.
  {
    return this->getStateMachine()->createSignalConnection(onMessageReceived_, callback, object);
  }
References callback(), smacc::ISmaccStateMachine::createSignalConnection(), and smacc::ISmaccClient::getStateMachine().
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialize(), sm_ferrari::cl_subscriber::CbMySubscriberBehavior::onEntry(), smacc::CbSubscriptionCallbackBase< TMsg >::onEntry(), and sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::onInitialize().
onOrthogonalAllocation()
template<typename MessageType > template<typename TOrthogonal , typename TSourceObject > void smacc::client_bases::SmaccSubscriberClient< MessageType >::onOrthogonalAllocation () inline
Definition at line 64 of file smacc_subscriber_client.h.
  {
    this->postMessageEvent = [=](auto msg) {
      auto event = new EvTopicMessage<TSourceObject, TOrthogonal>();
      event->msgData = msg;
      this->postEvent(event);
    };
    this->postInitialMessageEvent = [=](auto msg) {
      auto event = new EvTopicInitialMessage<TSourceObject, TOrthogonal>();
      event->msgData = msg;
      this->postEvent(event);
    };
  }
References battery_monitor_node::msg, and smacc::ISmaccClient::postEvent().
Member Data Documentation
firstMessage_
template<typename MessageType > bool smacc::client_bases::SmaccSubscriberClient< MessageType >::firstMessage_ private
Definition at line 107 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize(), and smacc::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
initialized_
template<typename MessageType > bool smacc::client_bases::SmaccSubscriberClient< MessageType >::initialized_ private
Definition at line 108 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize(), and smacc::client_bases::SmaccSubscriberClient< MessageType >::SmaccSubscriberClient().
nh_
template<typename MessageType > ros::NodeHandle smacc::client_bases::SmaccSubscriberClient< MessageType >::nh_ protected
Definition at line 103 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize(), and cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialize().
onFirstMessageReceived_
template<typename MessageType > smacc::SmaccSignal<void(const MessageType &)> smacc::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived_
Definition at line 45 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
onMessageReceived_
template<typename MessageType > smacc::SmaccSignal<void(const MessageType &)> smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived_
Definition at line 46 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
postInitialMessageEvent
template<typename MessageType > std::function<void(const MessageType &)> smacc::client_bases::SmaccSubscriberClient< MessageType >::postInitialMessageEvent
Definition at line 49 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
postMessageEvent
template<typename MessageType > std::function<void(const MessageType &)> smacc::client_bases::SmaccSubscriberClient< MessageType >::postMessageEvent
Definition at line 48 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
queueSize
template<typename MessageType > boost::optional<int> smacc::client_bases::SmaccSubscriberClient< MessageType >::queueSize
Definition at line 26 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize().
sub_
template<typename MessageType > ros::Subscriber smacc::client_bases::SmaccSubscriberClient< MessageType >::sub_ private
Definition at line 106 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize(), and smacc::client_bases::SmaccSubscriberClient< MessageType >::~SmaccSubscriberClient().
topicName
template<typename MessageType > boost::optional<std::string> smacc::client_bases::SmaccSubscriberClient< MessageType >::topicName
Definition at line 25 of file smacc_subscriber_client.h.
Referenced by smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize(), and smacc::client_bases::SmaccSubscriberClient< MessageType >::SmaccSubscriberClient().
The documentation for this class was generated from the following file:
smacc/include/smacc/client_bases/smacc_subscriber_client.h