SMACC: sm_subscriber::CbPostCustomEvent Class Reference
sm_subscriber::CbPostCustomEvent Class Reference
#include <cb_post_custom_event.h>
Public Member Functions
void onMessageReceived (const std_msgs::UInt16 &msg) override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc::CbSubscriptionCallbackBase< std_msgs::UInt16 >
virtual void onEntry () override
virtual void onMessageReceived (const std_msgs::UInt16 &msg)=0
Public Member Functions inherited from smacc::SmaccClientBehavior
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Public Attributes
std::function< void(int)> postEventImportantMessage
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Protected Attributes inherited from smacc::CbSubscriptionCallbackBase< std_msgs::UInt16 >
smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 > * attachedClient_
Detailed Description
Definition at line 13 of file cb_post_custom_event.h.
Member Function Documentation
onMessageReceived()
void sm_subscriber::CbPostCustomEvent::onMessageReceived (const std_msgs::UInt16 & msg) inline override virtual
Implements smacc::CbSubscriptionCallbackBase< std_msgs::UInt16 >.
Definition at line 16 of file cb_post_custom_event.h.
  {
    if (msg.data % 4 == 0)
    {
      ROS_WARN_STREAM("**** [CbPostCustomEvent] MESSAGE RECEIVED NUMBER MULTIPLE OF 4 "<< msg.data <<" , POSTING EvImportantMessage");
      this->postEventImportantMessage(msg.data);
    }
  }
References battery_monitor_node::msg, and postEventImportantMessage.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void sm_subscriber::CbPostCustomEvent::onOrthogonalAllocation () inline
Definition at line 26 of file cb_post_custom_event.h.
  {
    postEventImportantMessage = [=](int value) {
      auto ev = new EvImportantMessage<TSourceObject, TOrthogonal>();
      ev->value =  value;
      this->postEvent(ev);
    };
  }
References smacc::ISmaccClientBehavior::postEvent(), and postEventImportantMessage.
Member Data Documentation
postEventImportantMessage
std::function<void(int)> sm_subscriber::CbPostCustomEvent::postEventImportantMessage
Definition at line 35 of file cb_post_custom_event.h.
Referenced by onMessageReceived(), and onOrthogonalAllocation().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_subscriber/include/sm_subscriber/clients/cl_numbers_subscription/client_behaviors/cb_post_custom_event.h