SMACC: smacc::CbServiceServerCallbackBase< TService > Class Template Reference
smacc::CbServiceServerCallbackBase< TService > Class Template Reference abstract
#include <cb_service_server_callback_base.h>
Public Member Functions
virtual void onEntry () override
virtual bool onServiceRequestReceived (typename TService::Request &req, std::shared_ptr< typename TService::Response > res)=0
Public Member Functions inherited from smacc::SmaccClientBehavior
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Protected Attributes
smacc::client_bases::SmaccServiceServerClient< TService > * attachedClient_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Detailed Description
template<typename TService>
class smacc::CbServiceServerCallbackBase< TService >
Definition at line 6 of file cb_service_server_callback_base.h.
Member Function Documentation
onEntry()
template<typename TService > virtual void smacc::CbServiceServerCallbackBase< TService >::onEntry () inline override virtual
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 8 of file cb_service_server_callback_base.h.
{
    this->requiresClient(attachedClient_);
    attachedClient_->onServiceRequestReceived(
        &CbServiceServerCallbackBase::onServiceRequestReceived, this);
  }
References smacc::CbServiceServerCallbackBase< TService >::attachedClient_, smacc::CbServiceServerCallbackBase< TService >::onServiceRequestReceived(), and smacc::ISmaccClientBehavior::requiresClient().
onServiceRequestReceived()
template<typename TService > virtual bool smacc::CbServiceServerCallbackBase< TService >::onServiceRequestReceived (typename TService::Request & req, std::shared_ptr< typename TService::Response > res) pure virtual
Referenced by smacc::CbServiceServerCallbackBase< TService >::onEntry().
Member Data Documentation
attachedClient_
template<typename TService > smacc::client_bases::SmaccServiceServerClient<TService>* smacc::CbServiceServerCallbackBase< TService >::attachedClient_ protected
Initial value:
=
      nullptr
Definition at line 18 of file cb_service_server_callback_base.h.
Referenced by smacc::CbServiceServerCallbackBase< TService >::onEntry().
The documentation for this class was generated from the following file:
smacc/include/smacc/client_behavior_bases/cb_service_server_callback_base.h