SMACC: smacc::CbSubscriptionCallbackBase< TMsg > Class Template Reference
smacc::CbSubscriptionCallbackBase< TMsg > Class Template Reference abstract
#include <cb_subscription_callback_base.h>
Public Member Functions
virtual void onEntry () override
virtual void onMessageReceived (const TMsg &msg)=0
Public Member Functions inherited from smacc::SmaccClientBehavior
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Protected Attributes
smacc::client_bases::SmaccSubscriberClient< TMsg > * attachedClient_ = nullptr
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Detailed Description
template<typename TMsg>
class smacc::CbSubscriptionCallbackBase< TMsg >
Definition at line 12 of file cb_subscription_callback_base.h.
Member Function Documentation
onEntry()
template<typename TMsg > virtual void smacc::CbSubscriptionCallbackBase< TMsg >::onEntry () inline override virtual
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 15 of file cb_subscription_callback_base.h.
  {
    this->requiresClient(attachedClient_);
    attachedClient_->onMessageReceived(&CbSubscriptionCallbackBase::onMessageReceived, this);
  }
References smacc::CbSubscriptionCallbackBase< TMsg >::attachedClient_, smacc::CbSubscriptionCallbackBase< TMsg >::onMessageReceived(), smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), and smacc::ISmaccClientBehavior::requiresClient().
onMessageReceived()
template<typename TMsg > virtual void smacc::CbSubscriptionCallbackBase< TMsg >::onMessageReceived (const TMsg & msg) pure virtual
Implemented in sm_subscriber::CbPostCustomEvent, and sm_subscriber::CbPrintMessageNumber.
Referenced by smacc::CbSubscriptionCallbackBase< TMsg >::onEntry().
Member Data Documentation
attachedClient_
template<typename TMsg > smacc::client_bases::SmaccSubscriberClient<TMsg>* smacc::CbSubscriptionCallbackBase< TMsg >::attachedClient_ = nullptr protected
Definition at line 24 of file cb_subscription_callback_base.h.
Referenced by smacc::CbSubscriptionCallbackBase< TMsg >::onEntry().
The documentation for this class was generated from the following file:
smacc/include/smacc/client_behavior_bases/cb_subscription_callback_base.h