SMACC: cl_keyboard::CbDefaultKeyboardBehavior Class Reference
cl_keyboard::CbDefaultKeyboardBehavior Class Reference
#include <cb_default_keyboard_behavior.h>
Public Member Functions
void onEntry ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void OnKeyPress (char character)
template<typename TEv >
void postKeyEvent ()
Public Member Functions inherited from smacc::SmaccClientBehavior
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
ros::NodeHandle getNode ()
Public Attributes
ClKeyboard * ClKeyboard_
std::function< void(char)> postEventKeyPress
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
Detailed Description
Definition at line 10 of file cb_default_keyboard_behavior.h.
Member Function Documentation
onEntry()
void cl_keyboard::CbDefaultKeyboardBehavior::onEntry () inline virtual
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 16 of file cb_default_keyboard_behavior.h.
    {
        this->requiresClient(ClKeyboard_);
        this->ClKeyboard_->OnKeyPress(&CbDefaultKeyboardBehavior::OnKeyPress, this);
    }
References OnKeyPress(), cl_keyboard::ClKeyboard::OnKeyPress(), and smacc::ISmaccClientBehavior::requiresClient().
OnKeyPress()
void cl_keyboard::CbDefaultKeyboardBehavior::OnKeyPress (char character) inline
Definition at line 81 of file cb_default_keyboard_behavior.h.
    {
        postEventKeyPress(character);
    }
References postEventKeyPress.
Referenced by onEntry().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_keyboard::CbDefaultKeyboardBehavior::onOrthogonalAllocation () inline
Definition at line 23 of file cb_default_keyboard_behavior.h.
    {
        postEventKeyPress = [=](char character) {
            if (character == 'a')
                postKeyEvent<EvKeyPressA<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'b')
                postKeyEvent<EvKeyPressB<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'c')
                postKeyEvent<EvKeyPressC<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'd')
                postKeyEvent<EvKeyPressD<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'e')
                postKeyEvent<EvKeyPressE<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'f')
                postKeyEvent<EvKeyPressF<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'g')
                postKeyEvent<EvKeyPressG<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'h')
                postKeyEvent<EvKeyPressH<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'i')
                postKeyEvent<EvKeyPressI<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'j')
                postKeyEvent<EvKeyPressJ<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'k')
                postKeyEvent<EvKeyPressK<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'l')
                postKeyEvent<EvKeyPressL<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'm')
                postKeyEvent<EvKeyPressM<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'n')
                postKeyEvent<EvKeyPressN<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'o')
                postKeyEvent<EvKeyPressO<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'p')
                postKeyEvent<EvKeyPressP<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'q')
                postKeyEvent<EvKeyPressQ<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'r')
                postKeyEvent<EvKeyPressR<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 's')
                postKeyEvent<EvKeyPressS<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 't')
                postKeyEvent<EvKeyPressT<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'u')
                postKeyEvent<EvKeyPressU<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'v')
                postKeyEvent<EvKeyPressV<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'w')
                postKeyEvent<EvKeyPressW<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'x')
                postKeyEvent<EvKeyPressX<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'y')
                postKeyEvent<EvKeyPressY<CbDefaultKeyboardBehavior, TOrthogonal>>();
            else if (character == 'z')
                postKeyEvent<EvKeyPressZ<CbDefaultKeyboardBehavior, TOrthogonal>>();
        };
    }
References postEventKeyPress.
postKeyEvent()
template<typename TEv > void cl_keyboard::CbDefaultKeyboardBehavior::postKeyEvent () inline
Definition at line 87 of file cb_default_keyboard_behavior.h.
    {
        ROS_WARN("CbDefaultKeyboardBehavior %ld ev: %s", (long)(void *)this, smacc::demangleSymbol(typeid(TEv).name()).c_str());
        auto event = new TEv();
        this->postEvent(event);
    }
References smacc::introspection::demangleSymbol(), and smacc::ISmaccClientBehavior::postEvent().
Member Data Documentation
ClKeyboard_
ClKeyboard* cl_keyboard::CbDefaultKeyboardBehavior::ClKeyboard_
Definition at line 13 of file cb_default_keyboard_behavior.h.
postEventKeyPress
std::function<void(char)> cl_keyboard::CbDefaultKeyboardBehavior::postEventKeyPress
Definition at line 14 of file cb_default_keyboard_behavior.h.
Referenced by OnKeyPress(), and onOrthogonalAllocation().
The documentation for this class was generated from the following file:
smacc_client_library/keyboard_client/include/keyboard_client/client_behaviors/cb_default_keyboard_behavior.h