SMACC: smacc::state_reactors::EgRandomGenerator Class Reference
smacc::state_reactors::EgRandomGenerator Class Reference
#include <eg_random_generator.h>
Public Member Functions
EgRandomGenerator (RandomGenerateReactorMode mode, double evAMin=1, double evAMax=4, double evBMin=5, double evBMax=8, double evCMin=9, double evCMax=12)
virtual void onEntry () override
template<typename TState , typename TSource >
void onStateAllocation ()
void postRandomEvents ()
virtual void update () override
Public Member Functions inherited from smacc::SmaccEventGenerator
SmaccEventGenerator ()
virtual ~SmaccEventGenerator ()
template<typename TState , typename TSource >
void onStateAllocation ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
void initialize (ISmaccState *ownerState)
virtual void onInitialized ()
Public Member Functions inherited from smacc::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (ros::Duration duration)
void executeUpdate ()
void setUpdatePeriod (ros::Duration duration)
Public Attributes
RandomGenerateReactorMode mode_
Private Attributes
std::function< void()> postEventA
std::function< void()> postEventB
std::function< void()> postEventC
double evAMin_
double evAMax_
double evBMin_
double evBMax_
double evCMin_
double evCMax_
double minValue
double maxValue
Additional Inherited Members
virtual void update ()=0
Detailed Description
Definition at line 36 of file eg_random_generator.h.
Constructor & Destructor Documentation
EgRandomGenerator()
smacc::state_reactors::EgRandomGenerator::EgRandomGenerator (RandomGenerateReactorMode mode, double evAMin = 1, double evAMax = 4, double evBMin = 5, double evBMax = 8, double evCMin = 9, double evCMax = 12)
Definition at line 7 of file eg_random_generator.cpp.
            :
              mode_(mode),
              evAMin_(evAMin),
              evAMax_(evAMax),
              evBMin_(evBMin),
              evBMax_(evBMax),
              evCMin_(evCMin),
              evCMax_(evCMax)
        {
            auto values = {evAMin, evAMax, evBMin, evBMax, evCMin, evCMax};
            this->minValue = std::numeric_limits<double>::max();
            this->maxValue = std::numeric_limits<double>::min();
            for (auto &v : values)
            {
                if (v < minValue)
                {
                    minValue = v;
                }
                if (v > maxValue)
                {
                    maxValue = v;
                }
            }
        }
References maxValue, and minValue.
Member Function Documentation
onEntry()
void smacc::state_reactors::EgRandomGenerator::onEntry () override virtual
Reimplemented from smacc::SmaccEventGenerator.
Definition at line 57 of file eg_random_generator.cpp.
        {
            if (mode_ == RandomGenerateReactorMode::ONE_SHOT)
            {
                this->postRandomEvents();
            }
        }
References mode_, smacc::state_reactors::ONE_SHOT, and postRandomEvents().
onStateAllocation()
template<typename TState , typename TSource > void smacc::state_reactors::EgRandomGenerator::onStateAllocation () inline
Definition at line 44 of file eg_random_generator.h.
            {
                this->postEventA = [this]() { this->postEvent<EventA<TSource, TState>>(); };
                this->postEventB = [this]() { this->postEvent<EventB<TSource, TState>>(); };
                this->postEventC = [this]() { this->postEvent<EventC<TSource, TState>>(); };
            }
References postEventA, postEventB, and postEventC.
postRandomEvents()
void smacc::state_reactors::EgRandomGenerator::postRandomEvents ()
Definition at line 36 of file eg_random_generator.cpp.
        {
            int range = this->maxValue - this->minValue;
            int result = (rand() % range) + minValue;
            if (result >= evAMin_ && result <= evAMax_)
            {
                this->postEventA();
            }
            if (result >= evBMin_ && result <= evBMax_)
            {
                this->postEventB();
            }
            if (result >= evCMin_ && result <= evCMax_)
            {
                this->postEventC();
            }
        }
References evAMax_, evAMin_, evBMax_, evBMin_, evCMax_, evCMin_, maxValue, minValue, postEventA, postEventB, and postEventC.
Referenced by onEntry(), and update().
update()
void smacc::state_reactors::EgRandomGenerator::update () override virtual
Implements smacc::ISmaccUpdatable.
Definition at line 65 of file eg_random_generator.cpp.
        {
            if (mode_ == RandomGenerateReactorMode::ON_UPDATE)
            {
                this->postRandomEvents();
            }
        }
References mode_, smacc::state_reactors::ON_UPDATE, and postRandomEvents().
Member Data Documentation
evAMax_
double smacc::state_reactors::EgRandomGenerator::evAMax_ private
Definition at line 63 of file eg_random_generator.h.
Referenced by postRandomEvents().
evAMin_
double smacc::state_reactors::EgRandomGenerator::evAMin_ private
Definition at line 62 of file eg_random_generator.h.
Referenced by postRandomEvents().
evBMax_
double smacc::state_reactors::EgRandomGenerator::evBMax_ private
Definition at line 65 of file eg_random_generator.h.
Referenced by postRandomEvents().
evBMin_
double smacc::state_reactors::EgRandomGenerator::evBMin_ private
Definition at line 64 of file eg_random_generator.h.
Referenced by postRandomEvents().
evCMax_
double smacc::state_reactors::EgRandomGenerator::evCMax_ private
Definition at line 67 of file eg_random_generator.h.
Referenced by postRandomEvents().
evCMin_
double smacc::state_reactors::EgRandomGenerator::evCMin_ private
Definition at line 66 of file eg_random_generator.h.
Referenced by postRandomEvents().
maxValue
double smacc::state_reactors::EgRandomGenerator::maxValue private
Definition at line 70 of file eg_random_generator.h.
Referenced by EgRandomGenerator(), and postRandomEvents().
minValue
double smacc::state_reactors::EgRandomGenerator::minValue private
Definition at line 69 of file eg_random_generator.h.
Referenced by EgRandomGenerator(), and postRandomEvents().
mode_
RandomGenerateReactorMode smacc::state_reactors::EgRandomGenerator::mode_
Definition at line 55 of file eg_random_generator.h.
Referenced by onEntry(), and update().
postEventA
std::function<void()> smacc::state_reactors::EgRandomGenerator::postEventA private
Definition at line 58 of file eg_random_generator.h.
Referenced by onStateAllocation(), and postRandomEvents().
postEventB
std::function<void()> smacc::state_reactors::EgRandomGenerator::postEventB private
Definition at line 59 of file eg_random_generator.h.
Referenced by onStateAllocation(), and postRandomEvents().
postEventC
std::function<void()> smacc::state_reactors::EgRandomGenerator::postEventC private
Definition at line 60 of file eg_random_generator.h.
Referenced by onStateAllocation(), and postRandomEvents().
The documentation for this class was generated from the following files:
smacc_event_generator_library/eg_random_generator/include/eg_random_generator/eg_random_generator.h
smacc_event_generator_library/eg_random_generator/src/eg_random_generator/eg_random_generator.cpp