SMACC: generate_debs Namespace Reference
generate_debs Namespace Reference
Functions
def build_deb_package (workspace_source_folder, package_name, packagepath, ubuntu_version, ros_distro, already_visited)
def iterate_debian_generation (workspace_source_folder, package_names, identified_install_packages, osversion, rosversion)
def get_identified_packages (workspace_folder)
def push_debian_files_package_cloud (repo_owner, reponame, osname, osversion, debianfiles)
def remove_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
def create_and_push_smacc_debians (osname, osversion, rosversion, reponame, action, list packages)
Variables
rospack = rospkg.RosPack()
packages = rospack.list()
packagesl = list(packages)
parser = argparse.ArgumentParser()
help
required
default
type
nargs
args = parser.parse_args()
string osname = "ubuntu"
osversion = args.ubuntu_version
ros_version = args.ros_version
relative_smacc_folder = args.src_folder
workspace_folder = os.path.abspath(os.path.join(os.getcwd(), "."))
repo_owner = args.repo_owner
string homefolder = "/tmp"
packagecloud_token_filepath = os.path.join(homefolder, ".packagecloud")
outfile = open(packagecloud_token_filepath, "w")
def smacc_debians
Function Documentation
build_deb_package()
def generate_debs.build_deb_package (workspace_source_folder, package_name, packagepath, ubuntu_version, ros_distro, already_visited)
Definition at line 28 of file generate_debs.py.
):
    os.chdir(workspace_source_folder)
    print("------------------------------------------------------------")
    print("Working folder: " + str(os.getcwd()))
    print("Building debian package: " + str(package_name))
    cmd = (
        "bloom-generate rosdebian --os-name ubuntu --os-version "
        + str(ubuntu_version)
        + " --ros-distro "
        + str(ros_distro)
        + " "
        + str(packagepath)
    )
    # finding actual source package directory of the package in the workspace
    develpackagefolder = None
    for root, dirs, files in os.walk(workspace_source_folder, topdown=False):
        if "package.xml" in files and package_name == root.split("/")[-1] and "debian" not in root:
            print(root)
            develpackagefolder = root
            break
    if develpackagefolder is None:
        print("ERROR: package " + str(package_name) + " not found in workspace")
    localpackagepath = develpackagefolder
    print(f"local package path: {localpackagepath} ")
    # cleaning possible previous wrong builds
    if os.path.exists(os.path.join(localpackagepath, "debian")):
        shutil.rmtree(os.path.join(localpackagepath, "debian"))
    # executing bloom to generate debian-fakeroot build data
    print(cmd)
    bloomprocess = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    bloomprocess.wait()
    print("bloom process finished: " + str(bloomprocess.returncode))
    for line in bloomprocess.stdout:
        print(str(line))
    print("------------------------------------------------------------")
    os.chdir(workspace_source_folder)
    print(" - Local package path: " + localpackagepath)
    print(" - Workspace directory:")
    print(os.getcwd())
    print(" - list localpackagepath:")
    print(os.listdir(localpackagepath))
    # copy the debian folder generated by bloom inside the package
    shutil.move("debian", os.path.join(localpackagepath, "debian"))
    os.chdir(localpackagepath)
    fakerootprocess = subprocess.Popen("fakeroot debian/rules binary", shell=True)
    (result, err) = fakerootprocess.communicate()
    print("--------------------")
    os.chdir(workspace_source_folder)
    firstregexstr = ".*ros-" + ros_distro + r"-.*\.deb$"
    regexstr = ".*ros-" + ros_distro + "-" + package_name.replace("_", "-") + r"_.*\.deb$"
    print("Finding deb package: " + str(regexstr))
    thisfolderfiles = []
    for root, dirs, files in os.walk(workspace_source_folder, topdown=False):
        thisfolderfiles = thisfolderfiles + [os.path.join(root, f) for f in files]
    debianfiles = [f for f in thisfolderfiles if re.search(firstregexstr, f)]
    print("DETECTED DEBIAN FILES:")
    for d in debianfiles:
        print(f"- {d}")
    visited_debian_files = [
        f for f in debianfiles if re.search(regexstr, f) and f not in already_visited
    ]
    debianfilename = visited_debian_files[0]
    print("VISITED DEBIAN FILES:")
    for d in visited_debian_files:
        print(f"- {d}")
    print("Debian file found: ")
    print(debianfilename)
    os.chdir(localpackagepath)
    shutil.rmtree(".obj-x86_64-linux-gnu")
    shutil.rmtree("debian")
    print("installing debian package (required to build new debs): " + debianfilename)
    installdebiantask = subprocess.Popen("sudo dpkg -i " + debianfilename, shell=True)
    installdebiantask.wait()
    return debianfilename
Referenced by iterate_debian_generation().
create_and_push_smacc_debians()
def generate_debs.create_and_push_smacc_debians (osname, osversion, rosversion, reponame, action, list packages)
Definition at line 218 of file generate_debs.py.
def create_and_push_smacc_debians(osname, osversion, rosversion, reponame, action, packages: list):
    workspace_source_folder = os.path.join(workspace_folder, relative_smacc_folder)
    identified_install_packages = get_identified_packages(workspace_folder)
    print("workspace source folder: " + workspace_source_folder)
    print("packages: " + str(packages))
    print("--")
    print("identified packages: " + str(identified_install_packages.keys()))
    if "build" in action:
        smacc_debian_files = iterate_debian_generation(
            workspace_source_folder, packages, identified_install_packages, osversion, rosversion
        )
    else:
        smacc_debian_files = []
        for package_name in packages:
            firstregexstr = ".*ros-" + rosversion + r"-.*\.deb$"
            regexstr = ".*ros-" + rosversion + "-" + package_name.replace("_", "-") + r"_.*\.deb$"
            print("Finding deb package: " + str(regexstr))
            thisfolderfiles = []
            for root, dirs, files in os.walk(workspace_source_folder, topdown=False):
                thisfolderfiles = thisfolderfiles + [os.path.join(root, f) for f in files]
            debianfiles = [f for f in thisfolderfiles if re.search(firstregexstr, f)]
            print("DETECTED DEBIAN FILES:")
            for d in debianfiles:
                print(f"- {d}")
                smacc_debian_files.append(d)
    if "push" in action:
        if reponame is None:
            print("ERROR: reponame is required for push action")
            raise Exception("reponame is required for push action")
        create_repo_task = subprocess.Popen("package_cloud repository create smacc", shell=True)
        create_repo_task.wait()
        # ----- PUSHING TO SMACC --------------
        remove_debian_files(repo_owner, "smacc", osname, osversion, smacc_debian_files)
        push_debian_files_package_cloud(
            repo_owner, reponame, osname, osversion, smacc_debian_files
        )
    return smacc_debian_files
References get_identified_packages(), iterate_debian_generation(), push_debian_files_package_cloud(), and remove_debian_files().
get_identified_packages()
def generate_debs.get_identified_packages (workspace_folder)
Definition at line 150 of file generate_debs.py.
def get_identified_packages(workspace_folder):
    print("finding packages in workspace folder:" + workspace_folder)
    rospack = rospkg.RosPack()
    packages = rospack.list()
    packagesl = list(packages)
    identified_install_packages = {}
    print("packages2: " + str(packagesl))
    exclude_with_words = ["ridgeback", "mecanum", "catkin"]
    for pname in packagesl:
        packpath = rospack.get_path(pname)
        print(pname)
        if workspace_folder in packpath:
            if any([True for excludedword in exclude_with_words if excludedword in pname]):
                continue
            identified_install_packages[pname] = packpath
    return identified_install_packages
Referenced by create_and_push_smacc_debians().
iterate_debian_generation()
def generate_debs.iterate_debian_generation (workspace_source_folder, package_names, identified_install_packages, osversion, rosversion)
Definition at line 124 of file generate_debs.py.
):
    os.chdir(workspace_source_folder)
    debianfiles = []
    for pname in package_names:
        try:
            debianfiles.append(
                build_deb_package(
                    workspace_source_folder,
                    pname,
                    identified_install_packages[pname],
                    osversion,
                    rosversion,
                    debianfiles,
                )
            )
        except Exception as ex:
            print(ex)
            print("ERROR: package " + str(pname) + " could not be built")
            print("existing packages: " + str(identified_install_packages.keys()))
            raise ex
    return debianfiles
References build_deb_package().
Referenced by create_and_push_smacc_debians().
push_debian_files_package_cloud()
def generate_debs.push_debian_files_package_cloud (repo_owner, reponame, osname, osversion, debianfiles)
Definition at line 171 of file generate_debs.py.
def push_debian_files_package_cloud(repo_owner, reponame, osname, osversion, debianfiles):
    for debf in debianfiles:
        print("pushing debfile")
        cmd = (
            "package_cloud push "
            + repo_owner
            + "/"
            + reponame
            + "/"
            + osname
            + "/"
            + osversion
            + " "
            + debf
        )
        print(cmd)
        push_debian_task = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
        push_debian_task.wait()
        for line in push_debian_task.stdout:
            print(str(line))
Referenced by create_and_push_smacc_debians().
remove_debian_files()
def generate_debs.remove_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
Definition at line 195 of file generate_debs.py.
def remove_debian_files(repo_owner, reponame, osname, osversion, debianfiles):
    for debf in debianfiles:
        shortdebfile = debf.split("/")[-1]
        print("removing/yanking debfile")
        push_debian_task = subprocess.Popen(
            "package_cloud yank "
            + repo_owner
            + "/"
            + reponame
            + "/"
            + osname
            + "/"
            + osversion
            + " "
            + shortdebfile,
            shell=True,
        )
        push_debian_task.wait()
# ------------------------ SMACC PACKAGES -----------------------
Referenced by create_and_push_smacc_debians().
Variable Documentation
args
generate_debs.args = parser.parse_args()
Definition at line 304 of file generate_debs.py.
Referenced by smacc::ISmaccState.configure(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >.configure_orthogonal(), smacc::Orthogonal< TOrthogonal >.createClient(), smacc::ISmaccState.createEventGenerator(), smacc::ISmaccState.createStateReactor(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >.static_createEventGenerator(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >.static_createStateReactor(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >.static_createStateReactor_aux().
default
generate_debs.default
Definition at line 285 of file generate_debs.py.
help
generate_debs.help
Definition at line 282 of file generate_debs.py.
homefolder
string generate_debs.homefolder = "/tmp"
Definition at line 320 of file generate_debs.py.
nargs
generate_debs.nargs
Definition at line 296 of file generate_debs.py.
osname
string generate_debs.osname = "ubuntu"
Definition at line 306 of file generate_debs.py.
osversion
generate_debs.osversion = args.ubuntu_version
Definition at line 307 of file generate_debs.py.
outfile
generate_debs.outfile = open(packagecloud_token_filepath, "w")
Definition at line 323 of file generate_debs.py.
packagecloud_token_filepath
generate_debs.packagecloud_token_filepath = os.path.join(homefolder, ".packagecloud")
Definition at line 321 of file generate_debs.py.
packages
generate_debs.packages = rospack.list()
Definition at line 277 of file generate_debs.py.
packagesl
generate_debs.packagesl = list(packages)
Definition at line 278 of file generate_debs.py.
parser
generate_debs.parser = argparse.ArgumentParser()
Definition at line 280 of file generate_debs.py.
Referenced by cl_move_group_interface::CbMoveKnownState.loadJointStatesFromFile(), and cl_move_base_z::WaypointNavigator.loadWayPointsFromFile().
relative_smacc_folder
generate_debs.relative_smacc_folder = args.src_folder
Definition at line 314 of file generate_debs.py.
repo_owner
generate_debs.repo_owner = args.repo_owner
Definition at line 317 of file generate_debs.py.
required
generate_debs.required
Definition at line 282 of file generate_debs.py.
ros_version
generate_debs.ros_version = args.ros_version
Definition at line 308 of file generate_debs.py.
rospack
generate_debs.rospack = rospkg.RosPack()
Definition at line 276 of file generate_debs.py.
smacc_debians
def generate_debs.smacc_debians
Initial value:
=  create_and_push_smacc_debians(
        osname, osversion, ros_version, args.repo_name, args.action, args.packages
    )
Definition at line 327 of file generate_debs.py.
type
generate_debs.type
Definition at line 285 of file generate_debs.py.
Referenced by smacc::ISmaccState.createStateReactor(), smacc::client_bases::SmaccActionClientBase< ActionType >.getEventLabel(), smacc::introspection.getTransitionType(), smacc::state_reactors::SrAllEventsGo.onInitialized(), smacc::state_reactors::SrEventCountdown.onInitialized(), smacc::introspection::AddSubState.operator()(), smacc::introspection::AddTransition.operator()(), smacc::introspection.processSubState(), smacc::introspection.processTransitions(), SmaccTestRuntimeNode.tryTestPolicyFactory(), and smacc::introspection::WalkStatesExecutor< InitialStateType >.walkStates().
workspace_folder
generate_debs.workspace_folder = os.path.abspath(os.path.join(os.getcwd(), "."))
Definition at line 315 of file generate_debs.py.