SMACC: smacc_sm_reference_library/sm_ridgeback_barrel_search_1/servers/opencv_perception_node/opencv_perception_node.cpp File Reference
opencv_perception_node.cpp File Reference
#include <cv_bridge/cv_bridge.h>
#include <ros/ros.h>
#include <sensor_msgs/Image.h>
#include <std_msgs/Int32.h>
#include <iostream>
#include <opencv2/opencv.hpp>
#include <opencv2/features2d.hpp>
Functions
void segmentColor (const cv::Mat &inputRGB, int hueMean, int hueWindow, cv::Mat &out)
int testImage (cv::Mat &input, cv::Mat &debugImage, std::string colorName, int hueMean, int hueWindow)
int testRed (cv::Mat &input, cv::Mat &debugImage)
int testBlue (cv::Mat &input, cv::Mat &debugImage)
int testGreen (cv::Mat &input, cv::Mat &debugImage)
int testRed (std::string path, cv::Mat &debugImage)
int testBlue (std::string path, cv::Mat &debugImage)
int testGreen (std::string path, cv::Mat &debugImage)
void update ()
void callback (const sensor_msgs::Image &img)
int main (int argc, char **argv)
Variables
ros::Publisher detectionPub
ros::Publisher debugImagePub
ros::Subscriber imageSub
Function Documentation
callback()
void callback (const sensor_msgs::Image & img)
Definition at line 104 of file opencv_perception_node.cpp.
{
  cv_bridge::CvImagePtr cv_image = cv_bridge::toCvCopy(img, "rgb8");
  cv::Mat image = cv_image->image;
  cv_bridge::CvImage debugImageBridge;
  debugImageBridge.encoding = "rgb8";
  debugImageBridge.image = image.clone();
  int detectedColor = 0;
  if (testRed(image, debugImageBridge.image) > 0)
  {
    detectedColor = 1;
  }
  if (testGreen(image, debugImageBridge.image) > 0)
  {
    detectedColor = 2;
  }
  if (testBlue(image, debugImageBridge.image) > 0)
  {
    detectedColor = 3;
  }
  std_msgs::Int32 detectedColorMsg;
  detectedColorMsg.data = detectedColor;
  detectionPub.publish(detectedColorMsg);
  debugImageBridge.header = img.header;
  debugImagePub.publish(debugImageBridge.toImageMsg());
}
References debugImagePub, detectionPub, testBlue(), testGreen(), and testRed().
Referenced by smacc::utils::Bind< 1 >::bindaux(), smacc::utils::Bind< 2 >::bindaux(), smacc::utils::Bind< 3 >::bindaux(), smacc::utils::Bind< 4 >::bindaux(), smacc::introspection::EventGeneratorHandler::configureEventGenerator(), smacc::introspection::StateReactorHandler::configureStateReactor(), smacc::ISmaccClient::connectSignal(), smacc::StateReactor::createEventCallback(), smacc::ISmaccStateMachine::createSignalConnection(), main(), smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted(), smacc::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived(), smacc::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived(), cl_keyboard::ClKeyboard::OnKeyPress(), smacc::components::CpTopicSubscriber< MessageType >::onMessageReceived(), smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout(), cl_move_group_interface::ClMoveGroup::onMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::onMotionExecutionSuccedded(), smacc::client_bases::SmaccActionClientBase< ActionType >::onPreempted(), smacc::client_bases::SmaccActionClientBase< ActionType >::onRejected(), smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), and smacc::state_reactors::Srsr_conditional::Srsr_conditional().
main()
int main (int argc, char ** argv)
Definition at line 137 of file opencv_perception_node.cpp.
{
  ros::init(argc, argv, "blob_detector_node");
  ros::NodeHandle nh;
  detectionPub = nh.advertise<std_msgs::Int32>("detected_color", 1);
  imageSub = nh.subscribe("/image_raw", 1, callback);
  debugImagePub = nh.advertise<sensor_msgs::Image>("/opencv_debug_image", 1);
  ros::Rate r(10);
  while (ros::ok())
  {
    update();
    ros::spinOnce();
    r.sleep();
  }
  /*
  testRed("../../red1.png");
  testRed("../../green1.png");
  testRed("../../blue1.png");
  testRed("../../red2.png");
  testGreen("../../red1.png");
  testGreen("../../green1.png");
  testGreen("../../blue1.png");
  testGreen("../../red2.png");
  testBlue("../../red1.png");
  testBlue("../../green1.png");
  testBlue("../../blue1.png");
  testBlue("../../red2.png");
  */
}
References callback(), debugImagePub, detectionPub, imageSub, and update().
segmentColor()
void segmentColor (const cv::Mat & inputRGB, int hueMean, int hueWindow, cv::Mat & out)
Definition at line 13 of file opencv_perception_node.cpp.
{
  cv::Mat hsvInput;
  cv::cvtColor(inputRGB, hsvInput, cv::COLOR_BGR2HSV);
  cv::inRange(hsvInput, cv::Scalar(hueMean - hueWindow, 20, 20), cv::Scalar(hueMean + hueWindow, 255, 255), out);
  cv::threshold(out, out, 100, 255, cv::THRESH_BINARY);
}
Referenced by testImage().
testBlue() [1/2]
int testBlue (cv::Mat & input, cv::Mat & debugImage)
Definition at line 72 of file opencv_perception_node.cpp.
{
  return testImage(input, debugImage, "blue", 10, 10);
}
References testImage().
Referenced by callback().
testBlue() [2/2]
int testBlue (std::string path, cv::Mat & debugImage)
Definition at line 88 of file opencv_perception_node.cpp.
{
  cv::Mat input = cv::imread(path);
  return testImage(input, debugImage, "blue", 10, 10);
}
References testImage().
testGreen() [1/2]
int testGreen (cv::Mat & input, cv::Mat & debugImage)
Definition at line 77 of file opencv_perception_node.cpp.
{
  return testImage(input, debugImage, "green", 50, 10);
}
References testImage().
Referenced by callback().
testGreen() [2/2]
int testGreen (std::string path, cv::Mat & debugImage)
Definition at line 94 of file opencv_perception_node.cpp.
{
  cv::Mat input = cv::imread(path);
  return testImage(input, debugImage, "green", 50, 10);
}
References testImage().
testImage()
int testImage (cv::Mat & input, cv::Mat & debugImage, std::string colorName, int hueMean, int hueWindow)
Definition at line 21 of file opencv_perception_node.cpp.
{
  cv::Mat segmented;
  segmentColor(input, hueMean, hueWindow, segmented);
  cv::SimpleBlobDetector::Params params;
  // params.filterByArea= true;
  // params.minArea = 10;
  params.filterByArea = true;
  params.minArea = 100;
  params.maxArea = 100000;
  params.filterByColor = true;
  params.blobColor = 255;
  auto blobDetector = cv::SimpleBlobDetector::create(params);
  std::vector<cv::KeyPoint> blobs;
  blobDetector->detect(segmented, blobs);
  std::cout << "-------" << std::endl;
  for (auto& b : blobs)
  {
    std::cout << "blob " << colorName << " detected: " << b.size << std::endl;
  }
  if(!blobs.empty())
  {
    for(auto& b: blobs)
    {
      cv::Rect r;
      float diameter = b.size;
      auto radius = diameter*0.5;
      r.x = b.pt.x - radius;
      r.y = b.pt.y - radius;
      r.width = diameter;
      r.height = diameter;
      cv::rectangle(debugImage,r, cv::Scalar(255,0,0),1 );
    }
  }
  // cv::imshow(colorName + " filter - "+ path, segmented);
  // cv::waitKey();
  return blobs.size();
}
References segmentColor().
Referenced by testBlue(), testGreen(), and testRed().
testRed() [1/2]
int testRed (cv::Mat & input, cv::Mat & debugImage)
Definition at line 67 of file opencv_perception_node.cpp.
{
  return testImage(input, debugImage, "red", 130, 20);
}
References testImage().
Referenced by callback().
testRed() [2/2]
int testRed (std::string path, cv::Mat & debugImage)
Definition at line 82 of file opencv_perception_node.cpp.
{
  cv::Mat input = cv::imread(path);
  return testImage(input, debugImage, "red", 130, 20);
}
References testImage().
update()
void update ()
Definition at line 100 of file opencv_perception_node.cpp.
{
}
Referenced by main().
Variable Documentation
debugImagePub
ros::Publisher debugImagePub
Definition at line 10 of file opencv_perception_node.cpp.
Referenced by callback(), and main().
detectionPub
ros::Publisher detectionPub
Definition at line 9 of file opencv_perception_node.cpp.
Referenced by callback(), and main().
imageSub
ros::Subscriber imageSub
Definition at line 11 of file opencv_perception_node.cpp.
Referenced by main().