SMACC: smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType > Struct Template Reference
smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType > Struct Template Reference
State Machine.
#include <smacc_state_machine_base.h>
Public Member Functions
SmaccStateMachineBase (my_context ctx, SignalDetector *signalDetector)
virtual ~SmaccStateMachineBase ()
virtual void reset () override
virtual void stop () override
virtual void eStop () override
virtual void initiate_impl () override
Public Member Functions inherited from smacc::ISmaccStateMachine
ISmaccStateMachine (SignalDetector *signalDetector)
virtual ~ISmaccStateMachine ()
virtual void reset ()
virtual void stop ()
virtual void eStop ()
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
const std::map< std::string, std::shared_ptr< smacc::ISmaccOrthogonal > > & getOrthogonals () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename EventType >
void postEvent (EventType *ev, EventLifeTime evlifetime=EventLifeTime::ABSOLUTE)
template<typename EventType >
void postEvent (EventLifeTime evlifetime=EventLifeTime::ABSOLUTE)
void getTransitionLogHistory ()
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename StateField , typename BehaviorType >
void mapBehavior ()
std::string getStateMachineName ()
void state_machine_visualization (const ros::TimerEvent &)
std::shared_ptr< SmaccStateInfo > getCurrentStateInfo ()
void publishTransition (const SmaccTransitionInfo &transitionInfo)
virtual void onInitialize ()
this function should be implemented by the user to create the orthogonals
bool getTransitionLogHistory (smacc_msgs::SmaccGetTransitionHistory::Request &req, smacc_msgs::SmaccGetTransitionHistory::Response &res)
template<typename TSmaccSignal , typename TMemberFunctionPrototype , typename TSmaccObjectType >
boost::signals2::connection createSignalConnection (TSmaccSignal &signal, TMemberFunctionPrototype callback, TSmaccObjectType *object)
template<typename StateType >
void notifyOnStateEntryStart (StateType *state)
template<typename StateType >
void notifyOnStateEntryEnd (StateType *state)
template<typename StateType >
void notifyOnRuntimeConfigured (StateType *state)
template<typename StateType >
void notifyOnStateExitting (StateType *state)
template<typename StateType >
void notifyOnStateExited (StateType *state)
template<typename StateType >
void notifyOnRuntimeConfigurationFinished (StateType *state)
unsigned long getCurrentStateCounter () const
ISmaccState * getCurrentState () const
const SmaccStateMachineInfo & getStateMachineInfo ()
template<typename InitialStateType >
void buildStateMachineInfo ()
ros::NodeHandle getNode ()
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccStateMachine
void checkStateMachineConsistence ()
void initializeROS (std::string smshortname)
void onInitialized ()
template<typename TOrthogonal >
void createOrthogonal ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
template<typename T >
bool param (std::string param_name, T &param_val, const T &default_val) const
Protected Attributes inherited from smacc::ISmaccStateMachine
ros::NodeHandle nh_
ros::NodeHandle private_nh_
ros::Timer timer_
ros::Publisher stateMachinePub_
ros::Publisher stateMachineStatusPub_
ros::Publisher transitionLogPub_
ros::ServiceServer transitionHistoryService_
ISmaccState * currentState_
std::shared_ptr< SmaccStateInfo > currentStateInfo_
smacc_msgs::SmaccStatus status_msg_
std::map< std::string, std::shared_ptr< smacc::ISmaccOrthogonal > > orthogonals_
Detailed Description
template<typename DerivedStateMachine, typename InitialStateType>
struct smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >
State Machine.
Definition at line 17 of file smacc_state_machine_base.h.
Constructor & Destructor Documentation
SmaccStateMachineBase()
template<typename DerivedStateMachine , typename InitialStateType > smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::SmaccStateMachineBase (my_context ctx, SignalDetector * signalDetector) inline
Definition at line 20 of file smacc_state_machine_base.h.
        : ISmaccStateMachine(signalDetector),
          sc::asynchronous_state_machine<DerivedStateMachine, InitialStateType, SmaccFifoScheduler, SmaccAllocator>(ctx)
    {
    }
~SmaccStateMachineBase()
template<typename DerivedStateMachine , typename InitialStateType > virtual smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::~SmaccStateMachineBase () inline virtual
Definition at line 26 of file smacc_state_machine_base.h.
    {
        //updateCurrentState<InitialStateType>(false);
    }
Member Function Documentation
eStop()
template<typename DerivedStateMachine , typename InitialStateType > virtual void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::eStop () inline override virtual
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 44 of file smacc_state_machine_base.h.
    {
        ISmaccStateMachine::eStop();
        this->terminate();
    }
References smacc::ISmaccStateMachine::eStop().
initiate_impl()
template<typename DerivedStateMachine , typename InitialStateType > virtual void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::initiate_impl () inline override virtual
Definition at line 50 of file smacc_state_machine_base.h.
    {
        // this is before because this creates orthogonals
        this->onInitialize();
        ROS_INFO("[SmaccStateMachine] Introspecting state machine via typeWalker");
        this->buildStateMachineInfo<InitialStateType>();
        ROS_INFO("[SmaccStateMachine] initiate_impl");
        auto shortname =  smacc::utils::cleanShortTypeName(typeid(DerivedStateMachine));
        this->initializeROS(shortname);
        ROS_INFO("[SmaccStateMachine] Initializing ROS communication mechanisms");
        this->onInitialized();
        ROS_INFO("[SmaccStateMachine] Initializing state machine");
        sc::state_machine<DerivedStateMachine, InitialStateType, SmaccAllocator>::initiate();
    }
References smacc::utils::cleanShortTypeName(), smacc::ISmaccStateMachine::initializeROS(), smacc::ISmaccStateMachine::onInitialize(), and smacc::ISmaccStateMachine::onInitialized().
reset()
template<typename DerivedStateMachine , typename InitialStateType > virtual void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::reset () inline override virtual
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 31 of file smacc_state_machine_base.h.
    {
        ISmaccStateMachine::reset();
        this->terminate();
        smacc::run<DerivedStateMachine>();
    }
References smacc::ISmaccStateMachine::reset().
stop()
template<typename DerivedStateMachine , typename InitialStateType > virtual void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::stop () inline override virtual
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 38 of file smacc_state_machine_base.h.
    {
        ISmaccStateMachine::stop();
        this->terminate();
    }
References smacc::ISmaccStateMachine::stop().
The documentation for this struct was generated from the following file:
smacc/include/smacc/smacc_state_machine_base.h