SMACC: smacc::introspection::SmaccEventInfo Struct Reference
smacc::introspection::SmaccEventInfo Struct Reference
#include <smacc_state_info.h>
Public Member Functions
SmaccEventInfo (std::shared_ptr< TypeInfo > eventType)
std::string getEventTypeName ()
std::string getEventSourceName ()
std::string getOrthogonalName ()
Public Attributes
std::string label
std::shared_ptr< TypeInfo > eventType
Detailed Description
Definition at line 26 of file smacc_state_info.h.
Constructor & Destructor Documentation
SmaccEventInfo()
smacc::SmaccEventInfo::SmaccEventInfo (std::shared_ptr< TypeInfo > eventType)
Definition at line 69 of file smacc_state_info.cpp.
{
    ROS_INFO_STREAM("CREATING EVENT INFO: " << eventType->getFullName());
    this->eventType = eventType;
}
References eventType.
Member Function Documentation
getEventSourceName()
std::string smacc::SmaccEventInfo::getEventSourceName ()
Definition at line 76 of file smacc_state_info.cpp.
{
    if (eventType->templateParameters.size() > 0)
    {
        auto eventsourcename = demangleSymbol(eventType->templateParameters[0]->getFullName().c_str());
        return eventsourcename;
    }
    else
    {
        return "";
    }
}
References smacc::introspection::demangleSymbol(), and eventType.
getEventTypeName()
std::string smacc::SmaccEventInfo::getEventTypeName ()
Definition at line 89 of file smacc_state_info.cpp.
{
    return demangleSymbol(eventType->getNonTemplatedTypeName().c_str());
}
References smacc::introspection::demangleSymbol(), and eventType.
getOrthogonalName()
std::string smacc::SmaccEventInfo::getOrthogonalName ()
Definition at line 94 of file smacc_state_info.cpp.
{
    if (eventType->templateParameters.size() > 1)
    {
        return demangleSymbol(eventType->templateParameters[1]->getFullName().c_str());
    }
    else
    {
        return "";
    }
}
References smacc::introspection::demangleSymbol(), and eventType.
Member Data Documentation
eventType
std::shared_ptr<TypeInfo> smacc::introspection::SmaccEventInfo::eventType
Definition at line 39 of file smacc_state_info.h.
Referenced by getEventSourceName(), getEventTypeName(), getOrthogonalName(), and SmaccEventInfo().
label
std::string smacc::introspection::SmaccEventInfo::label
Definition at line 37 of file smacc_state_info.h.
The documentation for this struct was generated from the following files:
smacc/include/smacc/introspection/smacc_state_info.h
smacc/src/smacc/smacc_state_info.cpp