SMACC: LEDActionServer Class Reference
LEDActionServer Class Reference
Public Member Functions
LEDActionServer ()
void publishFeedback ()
void execute (const sm_dance_bot::LEDControlGoalConstPtr &goal)
void run ()
void publishStateMarker ()
LEDActionServer ()
void publishFeedback ()
void execute (const sm_dance_bot_2::LEDControlGoalConstPtr &goal)
void run ()
void publishStateMarker ()
LEDActionServer ()
void publishFeedback ()
void execute (const sm_dance_bot_strikes_back::LEDControlGoalConstPtr &goal)
void run ()
void publishStateMarker ()
Public Attributes
std::shared_ptr< Server > as_
ros::Publisher stateMarkerPublisher_
sm_dance_bot::LEDControlGoal cmd
uint8_t currentState_
sm_dance_bot_2::LEDControlGoal cmd
sm_dance_bot_strikes_back::LEDControlGoal cmd
Detailed Description
Definition at line 22 of file led_action_server_node.cpp.
Constructor & Destructor Documentation
LEDActionServer() [1/3]
LEDActionServer::LEDActionServer () inline
constructor()
Definition at line 38 of file led_action_server_node.cpp.
  {
    currentState_ =  sm_dance_bot::LEDControlResult::STATE_UNKNOWN;
  }
References currentState_.
LEDActionServer() [2/3]
LEDActionServer::LEDActionServer () inline
constructor()
Definition at line 38 of file led_action_server_node.cpp.
  {
    currentState_ =  sm_dance_bot_2::LEDControlResult::STATE_UNKNOWN;
  }
References currentState_.
LEDActionServer() [3/3]
LEDActionServer::LEDActionServer () inline
constructor()
Definition at line 38 of file led_action_server_node.cpp.
  {
    currentState_ =  sm_dance_bot_strikes_back::LEDControlResult::STATE_UNKNOWN;
  }
References currentState_.
Member Function Documentation
execute() [1/3]
void LEDActionServer::execute (const sm_dance_bot::LEDControlGoalConstPtr & goal) inline
execute()
Definition at line 60 of file led_action_server_node.cpp.
{
  ROS_INFO_STREAM("Tool action server request: "<< *goal);
  cmd = *goal;
  if(goal->command == sm_dance_bot::LEDControlGoal::CMD_ON)
  {
    currentState_ =  sm_dance_bot::LEDControlResult::STATE_RUNNING;
  }
  else  if (goal->command == sm_dance_bot::LEDControlGoal::CMD_OFF)
  {
    currentState_ =  sm_dance_bot::LEDControlResult::STATE_IDLE;
  }
  // 10Hz internal loop
  ros::Rate rate(20);
  while(ros::ok())
  {
    if(as_->isPreemptRequested())
    {
       // a new request is being executed, we will stop this one
       ROS_WARN("LEDActionServer request preempted. Forgetting older request.");
       as_->setPreempted();
       return;
    }
    publishFeedback();
    publishStateMarker();
    rate.sleep();
  }
   // never reach succeeded because were are interested in keeping the feedback alive
   as_->setSucceeded();
}
References as_, cmd, currentState_, publishFeedback(), and publishStateMarker().
Referenced by run().
execute() [2/3]
void LEDActionServer::execute (const sm_dance_bot_2::LEDControlGoalConstPtr & goal) inline
execute()
Definition at line 60 of file led_action_server_node.cpp.
{
  ROS_INFO_STREAM("Tool action server request: "<< *goal);
  cmd = *goal;
  if(goal->command == sm_dance_bot_2::LEDControlGoal::CMD_ON)
  {
    currentState_ =  sm_dance_bot_2::LEDControlResult::STATE_RUNNING;
  }
  else  if (goal->command == sm_dance_bot_2::LEDControlGoal::CMD_OFF)
  {
    currentState_ =  sm_dance_bot_2::LEDControlResult::STATE_IDLE;
  }
  // 10Hz internal loop
  ros::Rate rate(20);
  while(ros::ok())
  {
    if(as_->isPreemptRequested())
    {
       // a new request is being executed, we will stop this one
       ROS_WARN("LEDActionServer request preempted. Forgetting older request.");
       as_->setPreempted();
       return;
    }
    publishFeedback();
    publishStateMarker();
    rate.sleep();
  }
   // never reach succeeded because were are interested in keeping the feedback alive
   as_->setSucceeded();
}
References as_, cmd, currentState_, publishFeedback(), and publishStateMarker().
execute() [3/3]
void LEDActionServer::execute (const sm_dance_bot_strikes_back::LEDControlGoalConstPtr & goal) inline
execute()
Definition at line 60 of file led_action_server_node.cpp.
{
  ROS_INFO_STREAM("Tool action server request: "<< *goal);
  cmd = *goal;
  if(goal->command == sm_dance_bot_strikes_back::LEDControlGoal::CMD_ON)
  {
    currentState_ =  sm_dance_bot_strikes_back::LEDControlResult::STATE_RUNNING;
  }
  else  if (goal->command == sm_dance_bot_strikes_back::LEDControlGoal::CMD_OFF)
  {
    currentState_ =  sm_dance_bot_strikes_back::LEDControlResult::STATE_IDLE;
  }
  // 10Hz internal loop
  ros::Rate rate(20);
  while(ros::ok())
  {
    if(as_->isPreemptRequested())
    {
       // a new request is being executed, we will stop this one
       ROS_WARN("LEDActionServer request preempted. Forgetting older request.");
       as_->setPreempted();
       return;
    }
    publishFeedback();
    publishStateMarker();
    rate.sleep();
  }
   // never reach succeeded because were are interested in keeping the feedback alive
   as_->setSucceeded();
}
References as_, cmd, currentState_, publishFeedback(), and publishStateMarker().
publishFeedback() [1/3]
void LEDActionServer::publishFeedback () inline
publishFeedback()
Definition at line 48 of file led_action_server_node.cpp.
{
    sm_dance_bot::LEDControlFeedback feedback_msg;
    as_->publishFeedback(feedback_msg);
}
References as_.
Referenced by execute().
publishFeedback() [2/3]
void LEDActionServer::publishFeedback () inline
publishFeedback()
Definition at line 48 of file led_action_server_node.cpp.
{
    sm_dance_bot_2::LEDControlFeedback feedback_msg;
    as_->publishFeedback(feedback_msg);
}
References as_.
publishFeedback() [3/3]
void LEDActionServer::publishFeedback () inline
publishFeedback()
Definition at line 48 of file led_action_server_node.cpp.
{
    sm_dance_bot_strikes_back::LEDControlFeedback feedback_msg;
    as_->publishFeedback(feedback_msg);
}
References as_.
publishStateMarker() [1/3]
void LEDActionServer::publishStateMarker () inline
publishStateMarker()
Definition at line 121 of file led_action_server_node.cpp.
{
    visualization_msgs::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = ros::Time::now ();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::Marker::SPHERE;
    marker.action = visualization_msgs::Marker::ADD;
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if(currentState_ == sm_dance_bot::LEDControlResult::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == sm_dance_bot::LEDControlResult::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w=1;
    marker.pose.position.x=0;
    marker.pose.position.y=0;
    marker.pose.position.z=1;
    visualization_msgs::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_.publish(ma);
}
References currentState_, and stateMarkerPublisher_.
Referenced by execute().
publishStateMarker() [2/3]
void LEDActionServer::publishStateMarker () inline
publishStateMarker()
Definition at line 121 of file led_action_server_node.cpp.
{
    visualization_msgs::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = ros::Time::now ();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::Marker::SPHERE;
    marker.action = visualization_msgs::Marker::ADD;
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if(currentState_ == sm_dance_bot_2::LEDControlResult::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == sm_dance_bot_2::LEDControlResult::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w=1;
    marker.pose.position.x=0;
    marker.pose.position.y=0;
    marker.pose.position.z=1;
    visualization_msgs::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_.publish(ma);
}
References currentState_, and stateMarkerPublisher_.
publishStateMarker() [3/3]
void LEDActionServer::publishStateMarker () inline
publishStateMarker()
Definition at line 121 of file led_action_server_node.cpp.
{
    visualization_msgs::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = ros::Time::now ();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::Marker::SPHERE;
    marker.action = visualization_msgs::Marker::ADD;
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if(currentState_ == sm_dance_bot_strikes_back::LEDControlResult::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == sm_dance_bot_strikes_back::LEDControlResult::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w=1;
    marker.pose.position.x=0;
    marker.pose.position.y=0;
    marker.pose.position.z=1;
    visualization_msgs::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_.publish(ma);
}
References currentState_, and stateMarkerPublisher_.
run() [1/3]
void LEDActionServer::run () inline
run()
Definition at line 101 of file led_action_server_node.cpp.
{
  ros::NodeHandle n;
  ROS_INFO("Creating tool action server");
  as_ = std::make_shared<Server>(n, "led_action_server", boost::bind(&LEDActionServer::execute, this,  _1), false);
  ROS_INFO("Starting Tool Action Server");
  stateMarkerPublisher_ = n.advertise<visualization_msgs::MarkerArray>("tool_markers", 1);
  as_->start();
  ros::spin();
}
References as_, execute(), and stateMarkerPublisher_.
Referenced by main().
run() [2/3]
void LEDActionServer::run () inline
run()
Definition at line 101 of file led_action_server_node.cpp.
{
  ros::NodeHandle n;
  ROS_INFO("Creating tool action server");
  as_ = std::make_shared<Server>(n, "led_action_server", boost::bind(&LEDActionServer::execute, this,  _1), false);
  ROS_INFO("Starting Tool Action Server");
  stateMarkerPublisher_ = n.advertise<visualization_msgs::MarkerArray>("tool_markers", 1);
  as_->start();
  ros::spin();
}
References as_, execute(), and stateMarkerPublisher_.
run() [3/3]
void LEDActionServer::run () inline
run()
Definition at line 101 of file led_action_server_node.cpp.
{
  ros::NodeHandle n;
  ROS_INFO("Creating tool action server");
  as_ = std::make_shared<Server>(n, "led_action_server", boost::bind(&LEDActionServer::execute, this,  _1), false);
  ROS_INFO("Starting Tool Action Server");
  stateMarkerPublisher_ = n.advertise<visualization_msgs::MarkerArray>("tool_markers", 1);
  as_->start();
  ros::spin();
}
References as_, execute(), and stateMarkerPublisher_.
Member Data Documentation
as_
std::shared_ptr< Server > LEDActionServer::as_
Definition at line 25 of file led_action_server_node.cpp.
Referenced by execute(), publishFeedback(), and run().
cmd [1/3]
sm_dance_bot::LEDControlGoal LEDActionServer::cmd
Definition at line 29 of file led_action_server_node.cpp.
Referenced by execute().
cmd [2/3]
sm_dance_bot_2::LEDControlGoal LEDActionServer::cmd
Definition at line 29 of file led_action_server_node.cpp.
cmd [3/3]
sm_dance_bot_strikes_back::LEDControlGoal LEDActionServer::cmd
Definition at line 29 of file led_action_server_node.cpp.
currentState_
uint8_t LEDActionServer::currentState_
Definition at line 31 of file led_action_server_node.cpp.
Referenced by execute(), LEDActionServer(), and publishStateMarker().
stateMarkerPublisher_
ros::Publisher LEDActionServer::stateMarkerPublisher_
Definition at line 27 of file led_action_server_node.cpp.
Referenced by publishStateMarker(), and run().
The documentation for this class was generated from the following files:
smacc_sm_reference_library/sm_dance_bot/servers/led_action_server/src/led_action_server_node.cpp
smacc_sm_reference_library/sm_dance_bot_2/servers/led_action_server/src/led_action_server_node.cpp
smacc_sm_reference_library/sm_dance_bot_strikes_back/servers/led_action_server/src/led_action_server_node.cpp