SMACC: sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception Class Reference
sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception Class Reference
#include <cp_simulated_gazebo_perception.h>
Public Member Functions
virtual void onInitialize () override
void simulatedLinkStateCallback (const gazebo_msgs::LinkStates &linksmsg)
void identifyCubeColorsByNames (const std::vector< std::string > &linknames)
void propagateLinkStatesToTf (const gazebo_msgs::LinkStates &linksmsg, std::string linkNameFilter, std::string objectPrefix, std::string globalFrame, std::vector< tf::StampedTransform > &transforms)
Public Member Functions inherited from smacc::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Private Attributes
ros::Time startTime
ros::Duration readDelay
ros::Time lastUpdateStamp_
ros::Duration updatePeriod_
bool tableCollision_
bool cubeCollision_
tf::TransformListener tfListener_
tf::TransformBroadcaster tfBroadcaster_
ros::Subscriber gazeboStateSubscriber_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccComponent
virtual void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
virtual void onInitialize ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
Protected Attributes inherited from smacc::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 25 of file cp_simulated_gazebo_perception.h.
Member Function Documentation
identifyCubeColorsByNames()
void sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::identifyCubeColorsByNames (const std::vector< std::string > & linknames) inline
Definition at line 69 of file cp_simulated_gazebo_perception.h.
            {
                CpSceneState *scene;
                this->requiresComponent(scene);
                if (scene->cubeInfos_.front().color == "")
                {
                    std::vector<std::string> strs;
                    int i=0;
                    for (auto &linkname : linknames)
                    {
                        if (linkname.find("cube") != std::string::npos)
{
                            strs.clear();
                            boost::split(strs, linkname, boost::is_any_of("_:")); // demo_cube_green::link
                            CubeInfo& cubeinfo = scene->cubeInfos_[i++];
                            cubeinfo.color = strs[2];
                            cubeinfo.dstTableInfo_ = &(*(std::find_if(scene->tablesInfo_.begin(), scene->tablesInfo_.end(),
                                                                      [&](auto &ti) { return ti.associatedCubeColor_ == cubeinfo.color; })));
                        }
                    }
                }
            }
References sm_fetch_two_table_whiskey_pour::cl_perception_system::CubeInfo::color, sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSceneState::cubeInfos_, sm_fetch_two_table_whiskey_pour::cl_perception_system::CubeInfo::dstTableInfo_, smacc::ISmaccComponent::requiresComponent(), and sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSceneState::tablesInfo_.
Referenced by simulatedLinkStateCallback().
onInitialize()
virtual void sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::onInitialize () inline override virtual
Reimplemented from smacc::ISmaccComponent.
Definition at line 41 of file cp_simulated_gazebo_perception.h.
            {
                tableCollision_ = true;
                updatePeriod_ = ros::Duration(0.25);
                startTime = ros::Time::now();
                // order is important, to avoid "preemption" of the callback before it is initialized
                ros::NodeHandle nh;
                gazeboStateSubscriber_ =
                    nh.subscribe("/gazebo/link_states", 1, &CpSimulatedGazeboPerception::simulatedLinkStateCallback, this);
            }
References gazeboStateSubscriber_, simulatedLinkStateCallback(), startTime, tableCollision_, and updatePeriod_.
propagateLinkStatesToTf()
void sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::propagateLinkStatesToTf (const gazebo_msgs::LinkStates & linksmsg, std::string linkNameFilter, std::string objectPrefix, std::string globalFrame, std::vector< tf::StampedTransform > & transforms) inline
Definition at line 95 of file cp_simulated_gazebo_perception.h.
            {
                transforms.clear();
                int i = 0;
                std::vector<geometry_msgs::Pose> filteredLinkPoses;
                for (auto &b : linksmsg.pose)
                {
                    auto linkname = linksmsg.name[i];
                    if (linkname.find(linkNameFilter) != std::string::npos)
                        filteredLinkPoses.push_back(b);
                    i++;
                }
                i = 0;
                for (auto &linkpose : filteredLinkPoses)
                {
                    tf::Pose tfpose;
                    tf::poseMsgToTF(linkpose, tfpose);
                    tf::StampedTransform transform;
                    transform.setOrigin(tfpose.getOrigin());
                    transform.setRotation(tfpose.getRotation());
                    transform.frame_id_ = globalFrame;
                    transform.child_frame_id_ = objectPrefix + std::to_string(i + 1);
                    transform.stamp_ = ros::Time::now();
                    tfBroadcaster_.sendTransform(transform);
                    i++;
                    transforms.push_back(transform);
                }
            }
References tfBroadcaster_.
Referenced by simulatedLinkStateCallback().
simulatedLinkStateCallback()
void sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::simulatedLinkStateCallback (const gazebo_msgs::LinkStates & linksmsg) inline
Definition at line 53 of file cp_simulated_gazebo_perception.h.
            {
                identifyCubeColorsByNames(linksmsg.name);
                std::vector<tf::StampedTransform> cubeTransforms;
                this->propagateLinkStatesToTf(linksmsg, "cube", "cube_", "map", cubeTransforms);
                std::vector<tf::StampedTransform> tableTransforms;
                this->propagateLinkStatesToTf(linksmsg, "table", "table_", "map", tableTransforms);
                auto elapsed = ros::Time::now() - this->lastUpdateStamp_;
            }
References identifyCubeColorsByNames(), lastUpdateStamp_, and propagateLinkStatesToTf().
Referenced by onInitialize().
Member Data Documentation
cubeCollision_
bool sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::cubeCollision_ private
Definition at line 34 of file cp_simulated_gazebo_perception.h.
gazeboStateSubscriber_
ros::Subscriber sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::gazeboStateSubscriber_ private
Definition at line 38 of file cp_simulated_gazebo_perception.h.
Referenced by onInitialize().
lastUpdateStamp_
ros::Time sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::lastUpdateStamp_ private
Definition at line 31 of file cp_simulated_gazebo_perception.h.
Referenced by simulatedLinkStateCallback().
readDelay
ros::Duration sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::readDelay private
Definition at line 29 of file cp_simulated_gazebo_perception.h.
startTime
ros::Time sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::startTime private
Definition at line 28 of file cp_simulated_gazebo_perception.h.
Referenced by onInitialize().
tableCollision_
bool sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::tableCollision_ private
Definition at line 33 of file cp_simulated_gazebo_perception.h.
Referenced by onInitialize().
tfBroadcaster_
tf::TransformBroadcaster sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::tfBroadcaster_ private
Definition at line 37 of file cp_simulated_gazebo_perception.h.
Referenced by propagateLinkStatesToTf().
tfListener_
tf::TransformListener sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::tfListener_ private
Definition at line 36 of file cp_simulated_gazebo_perception.h.
updatePeriod_
ros::Duration sm_fetch_two_table_whiskey_pour::cl_perception_system::CpSimulatedGazeboPerception::updatePeriod_ private
Definition at line 32 of file cp_simulated_gazebo_perception.h.
Referenced by onInitialize().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_fetch_two_table_whiskey_pour/include/sm_fetch_two_table_whiskey_pour/clients/perception_system_client/components/cp_simulated_gazebo_perception.h