SMACC: smacc::ISmaccState Class Reference
smacc::ISmaccState Class Reference abstract
#include <smacc_state.h>
Inherited by smacc::SmaccState< State1, SmAtomic >, smacc::SmaccState< State2, SmAtomic >, smacc::SmaccState< State1, SmAtomicCB >, smacc::SmaccState< State2, SmAtomicCB >, smacc::SmaccState< State1, SmAtomicServices >, smacc::SmaccState< State2, SmAtomicServices >, smacc::SmaccState< MsWeekend, SmCalendarWeek, StSaturday >, smacc::SmaccState< MsWorkweek, SmCalendarWeek, StMonday >, smacc::SmaccState< StFriday, MsWorkweek >, smacc::SmaccState< StMonday, MsWorkweek >, smacc::SmaccState< StSaturday, MsWeekend >, smacc::SmaccState< StSunday, MsWeekend >, smacc::SmaccState< StThursday, MsWorkweek >, smacc::SmaccState< StTuesday, MsWorkweek >, smacc::SmaccState< StWednesday, MsWorkweek >, smacc::SmaccState< MsDanceBotRecoveryMode, SmDanceBot >, smacc::SmaccState< MsDanceBotRunMode, SmDanceBot, StAcquireSensors >, smacc::SmaccState< SsRadialPattern1, MsDanceBotRunMode, StiRadialLoopStart >, smacc::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >, smacc::SmaccState< SsRadialPattern3, MsDanceBotRunMode, StiRadialLoopStart >, smacc::SmaccState< SsFPattern1, MsDanceBotRunMode, StiFPatternStartLoop< SsFPattern1 > >, smacc::SmaccState< StiFPatternStartLoop< SsFPattern1 >, SsFPattern1 >, smacc::SmaccState< SsSPattern1, MsDanceBotRunMode, StiSPatternLoopStart >, smacc::SmaccState< StAcquireSensors, MsDanceBotRunMode >, smacc::SmaccState< StEventCountDown, MsDanceBotRunMode >, smacc::SmaccState< StNavigateForward1, MsDanceBotRunMode >, smacc::SmaccState< StNavigateForward2, MsDanceBotRunMode >, smacc::SmaccState< StNavigateReverse1, MsDanceBotRunMode >, smacc::SmaccState< StNavigateReverse2, MsDanceBotRunMode >, smacc::SmaccState< StNavigateReverse3, MsDanceBotRunMode >, smacc::SmaccState< StNavigateToWaypoint1, MsDanceBotRunMode >, smacc::SmaccState< StNavigateToWaypointsX, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees1, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees2, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees3, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees4, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees5, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees6, MsDanceBotRunMode >, smacc::SmaccState< StiFPatternForward1< SS >, SS >, smacc::SmaccState< StiFPatternForward2< SS >, SS >, smacc::SmaccState< StiFPatternReturn1< SS >, SS >, smacc::SmaccState< StiFPatternRotate1< SS >, SS >, smacc::SmaccState< StiFPatternRotate2< SS >, SS >, smacc::SmaccState< StiFPatternStartLoop< SS >, SS >, smacc::SmaccState< StiRadialEndPoint, SS >, smacc::SmaccState< StiRadialLoopStart, SS >, smacc::SmaccState< StiRadialReturn, SS >, smacc::SmaccState< StiRadialRotate, SS >, smacc::SmaccState< StiSPatternForward1, SS >, smacc::SmaccState< StiSPatternForward2, SS >, smacc::SmaccState< StiSPatternForward3, SS >, smacc::SmaccState< StiSPatternForward4, SS >, smacc::SmaccState< StiSPatternLoopStart, SS >, smacc::SmaccState< StiSPatternRotate1, SS >, smacc::SmaccState< StiSPatternRotate2, SS >, smacc::SmaccState< StiSPatternRotate3, SS >, smacc::SmaccState< StiSPatternRotate4, SS >, smacc::SmaccState< MsDanceBotRecoveryMode, SmDanceBot2 >, smacc::SmaccState< MsDanceBotRunMode, SmDanceBot2, StAcquireSensors >, smacc::SmaccState< MsDanceBotRecoveryMode, SmDanceBotStrikesBack >, smacc::SmaccState< MsDanceBotRunMode, SmDanceBotStrikesBack, StAcquireSensors >, smacc::SmaccState< StFpatternPrealignment, MsDanceBotRunMode >, smacc::SmaccState< StSpatternPrealignment, MsDanceBotRunMode >, smacc::SmaccState< MsRecover, SmFerrari >, smacc::SmaccState< MsRun, SmFerrari, StState1 >, smacc::SmaccState< Ss1, MsRun, StiState1 >, smacc::SmaccState< Ss2, MsRun, StiState1 >, smacc::SmaccState< StState1, MsRun >, smacc::SmaccState< StState2, MsRun >, smacc::SmaccState< StState3, MsRun >, smacc::SmaccState< StState4, MsRun >, smacc::SmaccState< StiState1, SS >, smacc::SmaccState< StiState2, SS >, smacc::SmaccState< StiState3, SS >, smacc::SmaccState< SsRecoveryScrew, SmFetchScrewLoop1, StRecoveryScrewInitial >, smacc::SmaccState< StFinalRaiseHandsUp, SmFetchScrewLoop1 >, smacc::SmaccState< StInitialPosture, SmFetchScrewLoop1 >, smacc::SmaccState< StSecondPosture, SmFetchScrewLoop1 >, smacc::SmaccState< StRecoveryScrewInitial, SS >, smacc::SmaccState< StRecoveryScrewSecond, SS >, smacc::SmaccState< StRecoveryScrewThird, SS >, smacc::SmaccState< SsPickObject, SmFetchSixTablePickNSort1, StMovePregraspPose >, smacc::SmaccState< SsPlaceObject, SmFetchSixTablePickNSort1, StMovePrePlacePose >, smacc::SmaccState< StFinalRaiseHandsUp, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StInitialPosture, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StNavigateFinalPose, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StNavigateToDestinyTable, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StNavigateToSourceTable, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StNavigationTableRetreat, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StCloseGripper, SS >, smacc::SmaccState< StGraspApproach, SS >, smacc::SmaccState< StGraspRetreat, SS >, smacc::SmaccState< StMovePregraspPose, SS >, smacc::SmaccState< StNavigationPosture, SS >, smacc::SmaccState< StMovePrePlacePose, SS >, smacc::SmaccState< StOpenGripper, SS >, smacc::SmaccState< StPlaceApproach, SS >, smacc::SmaccState< StPlaceRetreat, SS >, smacc::SmaccState< SsPickObject, SmFetchTwoTablePickNPlace1, StMovePregraspPose >, smacc::SmaccState< SsPlaceObject, SmFetchTwoTablePickNPlace1, StMovePrePlacePose >, smacc::SmaccState< StForwardNextTable, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< StInitialForward, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< StInitialPosture, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< StRotate180, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< StUndoIncorrectForward, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< SsPickObject, SmFetchTwoTableWhiskeyPour, StMovePregraspPose >, smacc::SmaccState< SsRecoveryScrew, SmFetchTwoTableWhiskeyPour, StRecoveryScrewInitial >, smacc::SmaccState< StBringBottleBackBackwardNavigation, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StBringBottleBackNavigateSourceTable, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StDecideDestinyTableAction, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StFinalRaiseHandsUp, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StInitialPosture, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StMoveCartesianBottleToContainer, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StNavigateToDestinyTable, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StNavigateToSourceTable, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StNavigationPosture, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPlaceBottleBack, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPlaceGlassBack, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPlaceRetreat, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPouringPosture, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPouringUndoPosture, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StReleaseGlass, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StReleaseGripper, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StRetreatBackwards, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< MsRun, SmPackML, StStarting >, smacc::SmaccState< MsStop, SmPackML, StStopping >, smacc::SmaccState< StAborted, SmPackML >, smacc::SmaccState< StAborting, SmPackML >, smacc::SmaccState< StClearing, MsStop >, smacc::SmaccState< StComplete, MsRun >, smacc::SmaccState< StCompleting, MsRun >, smacc::SmaccState< StExecute, MsRun >, smacc::SmaccState< StHeld, MsRun >, smacc::SmaccState< StHolding, MsRun >, smacc::SmaccState< StIdle, MsRun >, smacc::SmaccState< StResetting, MsRun >, smacc::SmaccState< StStarting, MsRun >, smacc::SmaccState< StStopped, MsStop >, smacc::SmaccState< StStopping, MsStop >, smacc::SmaccState< StSuspended, MsRun >, smacc::SmaccState< StSuspending, MsRun >, smacc::SmaccState< StUnholding, MsRun >, smacc::SmaccState< StUnsuspending, MsRun >, smacc::SmaccState< MsCalibration, SmRespira1, StCalibrationStep1 >, smacc::SmaccState< MsLeakyLung, SmRespira1, StLeakyLungStep1 >, smacc::SmaccState< MsPatientObstruction, SmRespira1, StPatientObstructionStep1 >, smacc::SmaccState< MsRun, SmRespira1, StObserve >, smacc::SmaccState< MsShutdown, SmRespira1, StSystemShutdown >, smacc::SmaccState< SsACCycle, MsRun, StiACCycleLoop >, smacc::SmaccState< SsCMVCycle, MsRun, StiCMVCycleLoop >, smacc::SmaccState< SsPCCycle, MsRun, StiPCCycleLoop >, smacc::SmaccState< SsPSCycle, MsRun, StiPSCycleLoop >, smacc::SmaccState< StCalibrationStep1, MsCalibration >, smacc::SmaccState< StLeakyLungStep1, MsLeakyLung >, smacc::SmaccState< StLeakyLungStep2, MsLeakyLung >, smacc::SmaccState< StLeakyLungStep3, MsLeakyLung >, smacc::SmaccState< StObserve, MsRun >, smacc::SmaccState< StPatientObstructionStep1, MsPatientObstruction >, smacc::SmaccState< StPatientObstructionStep2, MsPatientObstruction >, smacc::SmaccState< StSystemShutdown, MsShutdown >, smacc::SmaccState< StiACCycleDwell, SsACCycle >, smacc::SmaccState< StiACCycleExpire, SsACCycle >, smacc::SmaccState< StiACCycleInspire, SsACCycle >, smacc::SmaccState< StiACCycleLoop, SsACCycle >, smacc::SmaccState< StiACCyclePlateau, SsACCycle >, smacc::SmaccState< StiCMVCycleDwell, SsCMVCycle >, smacc::SmaccState< StiCMVCycleExpire, SsCMVCycle >, smacc::SmaccState< StiCMVCycleInspire, SsCMVCycle >, smacc::SmaccState< StiCMVCycleLoop, SsCMVCycle >, smacc::SmaccState< StiCMVCyclePlateau, SsCMVCycle >, smacc::SmaccState< StiPCCycleDwell, SsPCCycle >, smacc::SmaccState< StiPCCycleExpire, SsPCCycle >, smacc::SmaccState< StiPCCycleInspire, SsPCCycle >, smacc::SmaccState< StiPCCycleLoop, SsPCCycle >, smacc::SmaccState< StiPCCyclePlateau, SsPCCycle >, smacc::SmaccState< StiPSCycleDwell, SsPSCycle >, smacc::SmaccState< StiPSCycleExpire, SsPSCycle >, smacc::SmaccState< StiPSCycleInspire, SsPSCycle >, smacc::SmaccState< StiPSCycleLoop, SsPSCycle >, smacc::SmaccState< StiPSCyclePlateau, SsPSCycle >, smacc::SmaccState< StDetectItems, SmRidgebackBarrelSearch1 >, smacc::SmaccState< StNavigateToWaypointX, SmRidgebackBarrelSearch1 >, smacc::SmaccState< StDetectItems, SmRidgebackBarrelSearch2 >, smacc::SmaccState< StNavigateToWaypointX, SmRidgebackBarrelSearch2 >, smacc::SmaccState< MsRun, SmStarcraftAI, StObserve >, smacc::SmaccState< SsMove, MsRun, StiMove1 >, smacc::SmaccState< SsBuild, MsRun, StiBuild1 >, smacc::SmaccState< SsAttack, MsRun, StiAttack1 >, smacc::SmaccState< StiAttack1, SS >, smacc::SmaccState< StiAttack2, SS >, smacc::SmaccState< StiAttack3, SS >, smacc::SmaccState< StiBuild1, SS >, smacc::SmaccState< StiBuild2, SS >, smacc::SmaccState< StiBuild3, SS >, smacc::SmaccState< StiMove1, SS >, smacc::SmaccState< StiMove2, SS >, smacc::SmaccState< StiMove3, SS >, smacc::SmaccState< State1, SmSubscriber >, smacc::SmaccState< State2, SmSubscriber >, smacc::SmaccState< MsRecover, SmThreeSome >, smacc::SmaccState< MsRun, SmThreeSome, StState1 >, smacc::SmaccState< State1, SmUpdateLoop >, smacc::SmaccState< State2, SmUpdateLoop >, smacc::SmaccState< St2, MsRunMode >, and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >.
Public Member Functions
virtual ISmaccStateMachine & getStateMachine ()=0
ISmaccState * getParentState ()
ros::NodeHandle & getROSNode ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
template<typename T >
bool param (std::string param_name, T &param_val, const T &default_val) const
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Protected Attributes
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc::SmaccEventGenerator > > eventGenerators_
ros::NodeHandle nh
ros::NodeHandle contextNh
ISmaccState * parentState_
const smacc::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 11 of file smacc_state.h.
Member Function Documentation
configure()
template<typename TOrthogonal , typename TBehavior , typename... Args> std::shared_ptr< TBehavior > smacc::ISmaccState::configure (Args &&... args)
Definition at line 48 of file smacc_state_impl.h.
    {
        std::string orthogonalkey = demangledTypeName<TOrthogonal>();
        ROS_INFO("[%s] Configuring orthogonal: %s", THIS_STATE_NAME, orthogonalkey.c_str());
        TOrthogonal *orthogonal = this->getOrthogonal<TOrthogonal>();
        if (orthogonal != nullptr)
        {
            auto clientBehavior = std::shared_ptr<TBehavior>(new TBehavior(args...));
            clientBehavior->currentState = this;
            orthogonal->addClientBehavior(clientBehavior);
            clientBehavior->template onOrthogonalAllocation<TOrthogonal, TBehavior>();
            return clientBehavior;
        }
        else
        {
            ROS_ERROR("[%s] Skipping client behavior creation in orthogonal [%s]. It does not exist.", THIS_STATE_NAME, orthogonalkey.c_str());
            return nullptr;
        }
    }
References generate_debs::args, and THIS_STATE_NAME.
Referenced by smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal_runtime().
createEventGenerator()
template<typename TEventGenerator , typename... TEvArgs> std::shared_ptr< TEventGenerator > smacc::ISmaccState::createEventGenerator (TEvArgs... args)
Definition at line 120 of file smacc_state_impl.h.
    {
        auto eg = std::make_shared<TEventGenerator>(args...);
        eventGenerators_.push_back(eg);
        return eg;
    }
References generate_debs::args, and eventGenerators_.
createStateReactor() [1/2]
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs> std::shared_ptr< TStateReactor > smacc::ISmaccState::createStateReactor (TEvArgs... args)
Definition at line 143 of file smacc_state_impl.h.
    {
        auto sr = std::make_shared<TStateReactor>(args...);
        TEventList *mock;
        sr->initialize(this);
        sr->template setOutputEvent<TTriggerEvent>();
        using boost::mpl::_1;
        using wrappedList = typename boost::mpl::transform<TEventList, _1>::type;
        AddTEventType<TEventList> op(sr.get());
        boost::mpl::for_each<wrappedList>(op);
        stateReactors_.push_back(sr);
        return sr;
    }
References generate_debs::args, stateReactors_, and generate_debs::type.
createStateReactor() [2/2]
template<typename TStateReactor , typename... TEvArgs> std::shared_ptr< TStateReactor > smacc::ISmaccState::createStateReactor (TEvArgs... args)
Definition at line 110 of file smacc_state_impl.h.
    {
        auto sr = std::make_shared<TStateReactor>(args...);
        //sb->initialize(this, mock);
        //sb->setOutputEvent(typelist<TTriggerEvent>());
        stateReactors_.push_back(sr);
        return sr;
    }
References generate_debs::args, and stateReactors_.
getClassName()
std::string smacc::ISmaccState::getClassName () virtual
Definition at line 6 of file smacc_state.cpp.
{
    return demangleSymbol(typeid(*this).name());
}
References smacc::introspection::demangleSymbol().
Referenced by smacc::ISmaccStateMachine::propagateEventToStateReactors().
getEventGenerator()
template<typename TEventGenerator > TEventGenerator * smacc::ISmaccState::getEventGenerator
Definition at line 168 of file smacc_state_impl.h.
    {
        TEventGenerator* ret = nullptr;
        for(auto& evg: this->eventGenerators_)
        {
            ret = dynamic_cast<TEventGenerator *>(evg.get());
            if(ret!=nullptr)
                break;
        }
        return ret;
    }
References eventGenerators_.
getEventGenerators()
std::vector< std::shared_ptr< SmaccEventGenerator > > & smacc::ISmaccState::getEventGenerators () inline
Definition at line 62 of file smacc_state.h.
{ return eventGenerators_; }
References eventGenerators_.
Referenced by smacc::SignalDetector::findUpdatableStateElements(), and smacc::ISmaccStateMachine::notifyOnStateEntryEnd().
getGlobalSMData()
template<typename T > bool smacc::ISmaccState::getGlobalSMData (std::string name, T & ret)
Definition at line 95 of file smacc_state_impl.h.
    {
        return this->getStateMachine().getGlobalSMData(name, ret);
    }
References smacc::ISmaccStateMachine::getGlobalSMData(), and getStateMachine().
getOrthogonal()
template<typename TOrthogonal > TOrthogonal * smacc::ISmaccState::getOrthogonal
Definition at line 161 of file smacc_state_impl.h.
    {
        //static_assert(boost::type_traits::is_base_of<ISmaccOrthogonal,TOrthogonal>::value);
        return this->getStateMachine().getOrthogonal<TOrthogonal>();
    }
References smacc::ISmaccStateMachine::getOrthogonal(), and getStateMachine().
getParam()
template<typename T > bool smacc::ISmaccState::getParam (std::string param_name, T & param_storage)
Definition at line 24 of file smacc_state_impl.h.
    {
        return nh.getParam(param_name, param_storage);
    }
References nh.
Referenced by cl_move_base_z::CbNavigateGlobalPosition::readStartPoseFromParameterServer().
getParentState()
ISmaccState * smacc::ISmaccState::getParentState () inline
Definition at line 16 of file smacc_state.h.
{ return parentState_; }
References parentState_.
Referenced by smacc::ISmaccStateMachine::propagateEventToStateReactors().
getROSNode()
ros::NodeHandle & smacc::ISmaccState::getROSNode () inline
Definition at line 18 of file smacc_state.h.
{ return nh; }
References nh.
getStateMachine()
virtual ISmaccStateMachine & smacc::ISmaccState::getStateMachine () pure virtual
Implemented in smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >, smacc::SmaccState< State1, SmAtomic >, smacc::SmaccState< State2, SmAtomic >, smacc::SmaccState< State1, SmAtomicCB >, smacc::SmaccState< State2, SmAtomicCB >, smacc::SmaccState< State1, SmAtomicServices >, smacc::SmaccState< State2, SmAtomicServices >, smacc::SmaccState< MsWeekend, SmCalendarWeek, StSaturday >, smacc::SmaccState< MsWorkweek, SmCalendarWeek, StMonday >, smacc::SmaccState< StFriday, MsWorkweek >, smacc::SmaccState< StMonday, MsWorkweek >, smacc::SmaccState< StSaturday, MsWeekend >, smacc::SmaccState< StSunday, MsWeekend >, smacc::SmaccState< StThursday, MsWorkweek >, smacc::SmaccState< StTuesday, MsWorkweek >, smacc::SmaccState< StWednesday, MsWorkweek >, smacc::SmaccState< MsDanceBotRecoveryMode, SmDanceBot >, smacc::SmaccState< MsDanceBotRunMode, SmDanceBot, StAcquireSensors >, smacc::SmaccState< SsRadialPattern1, MsDanceBotRunMode, StiRadialLoopStart >, smacc::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >, smacc::SmaccState< SsRadialPattern3, MsDanceBotRunMode, StiRadialLoopStart >, smacc::SmaccState< SsFPattern1, MsDanceBotRunMode, StiFPatternStartLoop< SsFPattern1 > >, smacc::SmaccState< StiFPatternStartLoop< SsFPattern1 >, SsFPattern1 >, smacc::SmaccState< SsSPattern1, MsDanceBotRunMode, StiSPatternLoopStart >, smacc::SmaccState< StAcquireSensors, MsDanceBotRunMode >, smacc::SmaccState< StEventCountDown, MsDanceBotRunMode >, smacc::SmaccState< StNavigateForward1, MsDanceBotRunMode >, smacc::SmaccState< StNavigateForward2, MsDanceBotRunMode >, smacc::SmaccState< StNavigateReverse1, MsDanceBotRunMode >, smacc::SmaccState< StNavigateReverse2, MsDanceBotRunMode >, smacc::SmaccState< StNavigateReverse3, MsDanceBotRunMode >, smacc::SmaccState< StNavigateToWaypoint1, MsDanceBotRunMode >, smacc::SmaccState< StNavigateToWaypointsX, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees1, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees2, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees3, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees4, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees5, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees6, MsDanceBotRunMode >, smacc::SmaccState< StiFPatternForward1< SS >, SS >, smacc::SmaccState< StiFPatternForward2< SS >, SS >, smacc::SmaccState< StiFPatternReturn1< SS >, SS >, smacc::SmaccState< StiFPatternRotate1< SS >, SS >, smacc::SmaccState< StiFPatternRotate2< SS >, SS >, smacc::SmaccState< StiFPatternStartLoop< SS >, SS >, smacc::SmaccState< StiRadialEndPoint, SS >, smacc::SmaccState< StiRadialLoopStart, SS >, smacc::SmaccState< StiRadialReturn, SS >, smacc::SmaccState< StiRadialRotate, SS >, smacc::SmaccState< StiSPatternForward1, SS >, smacc::SmaccState< StiSPatternForward2, SS >, smacc::SmaccState< StiSPatternForward3, SS >, smacc::SmaccState< StiSPatternForward4, SS >, smacc::SmaccState< StiSPatternLoopStart, SS >, smacc::SmaccState< StiSPatternRotate1, SS >, smacc::SmaccState< StiSPatternRotate2, SS >, smacc::SmaccState< StiSPatternRotate3, SS >, smacc::SmaccState< StiSPatternRotate4, SS >, smacc::SmaccState< MsDanceBotRecoveryMode, SmDanceBot2 >, smacc::SmaccState< MsDanceBotRunMode, SmDanceBot2, StAcquireSensors >, smacc::SmaccState< MsDanceBotRecoveryMode, SmDanceBotStrikesBack >, smacc::SmaccState< MsDanceBotRunMode, SmDanceBotStrikesBack, StAcquireSensors >, smacc::SmaccState< StFpatternPrealignment, MsDanceBotRunMode >, smacc::SmaccState< StSpatternPrealignment, MsDanceBotRunMode >, smacc::SmaccState< MsRecover, SmFerrari >, smacc::SmaccState< MsRun, SmFerrari, StState1 >, smacc::SmaccState< Ss1, MsRun, StiState1 >, smacc::SmaccState< Ss2, MsRun, StiState1 >, smacc::SmaccState< StState1, MsRun >, smacc::SmaccState< StState2, MsRun >, smacc::SmaccState< StState3, MsRun >, smacc::SmaccState< StState4, MsRun >, smacc::SmaccState< StiState1, SS >, smacc::SmaccState< StiState2, SS >, smacc::SmaccState< StiState3, SS >, smacc::SmaccState< SsRecoveryScrew, SmFetchScrewLoop1, StRecoveryScrewInitial >, smacc::SmaccState< StFinalRaiseHandsUp, SmFetchScrewLoop1 >, smacc::SmaccState< StInitialPosture, SmFetchScrewLoop1 >, smacc::SmaccState< StSecondPosture, SmFetchScrewLoop1 >, smacc::SmaccState< StRecoveryScrewInitial, SS >, smacc::SmaccState< StRecoveryScrewSecond, SS >, smacc::SmaccState< StRecoveryScrewThird, SS >, smacc::SmaccState< SsPickObject, SmFetchSixTablePickNSort1, StMovePregraspPose >, smacc::SmaccState< SsPlaceObject, SmFetchSixTablePickNSort1, StMovePrePlacePose >, smacc::SmaccState< StFinalRaiseHandsUp, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StInitialPosture, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StNavigateFinalPose, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StNavigateToDestinyTable, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StNavigateToSourceTable, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StNavigationTableRetreat, SmFetchSixTablePickNSort1 >, smacc::SmaccState< StCloseGripper, SS >, smacc::SmaccState< StGraspApproach, SS >, smacc::SmaccState< StGraspRetreat, SS >, smacc::SmaccState< StMovePregraspPose, SS >, smacc::SmaccState< StNavigationPosture, SS >, smacc::SmaccState< StMovePrePlacePose, SS >, smacc::SmaccState< StOpenGripper, SS >, smacc::SmaccState< StPlaceApproach, SS >, smacc::SmaccState< StPlaceRetreat, SS >, smacc::SmaccState< SsPickObject, SmFetchTwoTablePickNPlace1, StMovePregraspPose >, smacc::SmaccState< SsPlaceObject, SmFetchTwoTablePickNPlace1, StMovePrePlacePose >, smacc::SmaccState< StForwardNextTable, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< StInitialForward, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< StInitialPosture, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< StRotate180, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< StUndoIncorrectForward, SmFetchTwoTablePickNPlace1 >, smacc::SmaccState< SsPickObject, SmFetchTwoTableWhiskeyPour, StMovePregraspPose >, smacc::SmaccState< SsRecoveryScrew, SmFetchTwoTableWhiskeyPour, StRecoveryScrewInitial >, smacc::SmaccState< StBringBottleBackBackwardNavigation, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StBringBottleBackNavigateSourceTable, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StDecideDestinyTableAction, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StFinalRaiseHandsUp, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StInitialPosture, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StMoveCartesianBottleToContainer, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StNavigateToDestinyTable, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StNavigateToSourceTable, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StNavigationPosture, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPlaceBottleBack, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPlaceGlassBack, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPlaceRetreat, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPouringPosture, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StPouringUndoPosture, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StReleaseGlass, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StReleaseGripper, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< StRetreatBackwards, SmFetchTwoTableWhiskeyPour >, smacc::SmaccState< MsRun, SmPackML, StStarting >, smacc::SmaccState< MsStop, SmPackML, StStopping >, smacc::SmaccState< StAborted, SmPackML >, smacc::SmaccState< StAborting, SmPackML >, smacc::SmaccState< StClearing, MsStop >, smacc::SmaccState< StComplete, MsRun >, smacc::SmaccState< StCompleting, MsRun >, smacc::SmaccState< StExecute, MsRun >, smacc::SmaccState< StHeld, MsRun >, smacc::SmaccState< StHolding, MsRun >, smacc::SmaccState< StIdle, MsRun >, smacc::SmaccState< StResetting, MsRun >, smacc::SmaccState< StStarting, MsRun >, smacc::SmaccState< StStopped, MsStop >, smacc::SmaccState< StStopping, MsStop >, smacc::SmaccState< StSuspended, MsRun >, smacc::SmaccState< StSuspending, MsRun >, smacc::SmaccState< StUnholding, MsRun >, smacc::SmaccState< StUnsuspending, MsRun >, smacc::SmaccState< MsCalibration, SmRespira1, StCalibrationStep1 >, smacc::SmaccState< MsLeakyLung, SmRespira1, StLeakyLungStep1 >, smacc::SmaccState< MsPatientObstruction, SmRespira1, StPatientObstructionStep1 >, smacc::SmaccState< MsRun, SmRespira1, StObserve >, smacc::SmaccState< MsShutdown, SmRespira1, StSystemShutdown >, smacc::SmaccState< SsACCycle, MsRun, StiACCycleLoop >, smacc::SmaccState< SsCMVCycle, MsRun, StiCMVCycleLoop >, smacc::SmaccState< SsPCCycle, MsRun, StiPCCycleLoop >, smacc::SmaccState< SsPSCycle, MsRun, StiPSCycleLoop >, smacc::SmaccState< StCalibrationStep1, MsCalibration >, smacc::SmaccState< StLeakyLungStep1, MsLeakyLung >, smacc::SmaccState< StLeakyLungStep2, MsLeakyLung >, smacc::SmaccState< StLeakyLungStep3, MsLeakyLung >, smacc::SmaccState< StObserve, MsRun >, smacc::SmaccState< StPatientObstructionStep1, MsPatientObstruction >, smacc::SmaccState< StPatientObstructionStep2, MsPatientObstruction >, smacc::SmaccState< StSystemShutdown, MsShutdown >, smacc::SmaccState< StiACCycleDwell, SsACCycle >, smacc::SmaccState< StiACCycleExpire, SsACCycle >, smacc::SmaccState< StiACCycleInspire, SsACCycle >, smacc::SmaccState< StiACCycleLoop, SsACCycle >, smacc::SmaccState< StiACCyclePlateau, SsACCycle >, smacc::SmaccState< StiCMVCycleDwell, SsCMVCycle >, smacc::SmaccState< StiCMVCycleExpire, SsCMVCycle >, smacc::SmaccState< StiCMVCycleInspire, SsCMVCycle >, smacc::SmaccState< StiCMVCycleLoop, SsCMVCycle >, smacc::SmaccState< StiCMVCyclePlateau, SsCMVCycle >, smacc::SmaccState< StiPCCycleDwell, SsPCCycle >, smacc::SmaccState< StiPCCycleExpire, SsPCCycle >, smacc::SmaccState< StiPCCycleInspire, SsPCCycle >, smacc::SmaccState< StiPCCycleLoop, SsPCCycle >, smacc::SmaccState< StiPCCyclePlateau, SsPCCycle >, smacc::SmaccState< StiPSCycleDwell, SsPSCycle >, smacc::SmaccState< StiPSCycleExpire, SsPSCycle >, smacc::SmaccState< StiPSCycleInspire, SsPSCycle >, smacc::SmaccState< StiPSCycleLoop, SsPSCycle >, smacc::SmaccState< StiPSCyclePlateau, SsPSCycle >, smacc::SmaccState< StDetectItems, SmRidgebackBarrelSearch1 >, smacc::SmaccState< StNavigateToWaypointX, SmRidgebackBarrelSearch1 >, smacc::SmaccState< StDetectItems, SmRidgebackBarrelSearch2 >, smacc::SmaccState< StNavigateToWaypointX, SmRidgebackBarrelSearch2 >, smacc::SmaccState< MsRun, SmStarcraftAI, StObserve >, smacc::SmaccState< SsMove, MsRun, StiMove1 >, smacc::SmaccState< SsBuild, MsRun, StiBuild1 >, smacc::SmaccState< SsAttack, MsRun, StiAttack1 >, smacc::SmaccState< StiAttack1, SS >, smacc::SmaccState< StiAttack2, SS >, smacc::SmaccState< StiAttack3, SS >, smacc::SmaccState< StiBuild1, SS >, smacc::SmaccState< StiBuild2, SS >, smacc::SmaccState< StiBuild3, SS >, smacc::SmaccState< StiMove1, SS >, smacc::SmaccState< StiMove2, SS >, smacc::SmaccState< StiMove3, SS >, smacc::SmaccState< State1, SmSubscriber >, smacc::SmaccState< State2, SmSubscriber >, smacc::SmaccState< MsRecover, SmThreeSome >, smacc::SmaccState< MsRun, SmThreeSome, StState1 >, smacc::SmaccState< State1, SmUpdateLoop >, smacc::SmaccState< State2, SmUpdateLoop >, and smacc::SmaccState< St2, MsRunMode >.
Referenced by getGlobalSMData(), getOrthogonal(), notifyTransitionFromTransitionTypeInfo(), postEvent(), requiresClient(), requiresComponent(), setGlobalSMData(), and smacc::StateReactor::setOutputEvent().
getStateReactor()
template<typename TStateReactor > TStateReactor * smacc::ISmaccState::getStateReactor
Definition at line 181 of file smacc_state_impl.h.
    {
        TStateReactor* ret = nullptr;
        for(auto& sr: this->stateReactors_)
        {
            ret = dynamic_cast<TStateReactor *>(sr.get());
            if(ret!=nullptr)
                break;
        }
        return ret;
    }
References stateReactors_.
getStateReactors()
std::vector< std::shared_ptr< StateReactor > > & smacc::ISmaccState::getStateReactors () inline
Definition at line 60 of file smacc_state.h.
{ return stateReactors_; }
References stateReactors_.
Referenced by smacc::SignalDetector::findUpdatableStateElements(), smacc::ISmaccStateMachine::notifyOnStateEntryEnd(), and smacc::ISmaccStateMachine::propagateEventToStateReactors().
notifyTransition()
template<typename TransitionType > void smacc::ISmaccState::notifyTransition
Definition at line 219 of file smacc_state_impl.h.
    {
        auto transitionType = TypeInfo::getTypeInfoFromType<TransitionType>();
        this->notifyTransitionFromTransitionTypeInfo(transitionType);
    }
References notifyTransitionFromTransitionTypeInfo().
notifyTransitionFromTransitionTypeInfo()
void smacc::ISmaccState::notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc::introspection::TypeInfo > & transitionTypeInfo)
Definition at line 11 of file smacc_state.cpp.
{
    ROS_INFO_STREAM("NOTIFY TRANSITION: " << transitionType->getFullName());
    //auto currstateinfo = this->getStateMachine().getCurrentStateInfo();
    auto currstateinfo = this->stateInfo_;
    if (currstateinfo != nullptr)
    {
        //ROS_ERROR_STREAM("CURRENT STATE INFO: " << currstateinfo->fullStateName);
        for (auto &transition : currstateinfo->transitions_)
        {
            std::string transitionCandidateName = transition.transitionTypeInfo->getFullName();
            //ROS_ERROR_STREAM("candidate transition: " << transitionCandidateName);
            if (transitionType->getFullName() == transitionCandidateName)
            {
                this->getStateMachine().publishTransition(transition);
                return;
            }
        }
        // debug information if not found
        ROS_ERROR_STREAM("Transition happened, from current state " << currstateinfo->getDemangledFullName() << " but there is not any transitioninfo match available to publish transition: " << transitionType->getFullName());
        std::stringstream ss;
        auto stateinfo = currstateinfo;
        for (auto &transition : currstateinfo->transitions_)
        {
            std::string transitionCandidateName = transition.transitionTypeInfo->getFullName();
            ROS_ERROR_STREAM("- candidate transition: " << transitionCandidateName);
        }
        ROS_ERROR("Ancestors candidates: ");
        std::list<const SmaccStateInfo *> ancestors;
        stateinfo->getAncestors(ancestors);
        for (auto &ancestor : ancestors)
        {
            ROS_ERROR_STREAM(" * Ancestor " << ancestor->getDemangledFullName() << ":");
            for (auto &transition : ancestor->transitions_)
            {
                std::string transitionCandidateName = transition.transitionTypeInfo->getFullName();
                ROS_ERROR_STREAM("- candidate transition: " << transitionCandidateName);
                if (transitionType->getFullName() == transitionCandidateName)
                {
                    ROS_ERROR("GOTCHA");
                }
            }
        }
    }
    else
    {
        ROS_ERROR_STREAM("Transition happened, but current state was not set. Transition candidates:");
    }
}
References getStateMachine(), smacc::ISmaccStateMachine::publishTransition(), and stateInfo_.
Referenced by notifyTransition().
param()
template<typename T > bool smacc::ISmaccState::param (std::string param_name, T & param_val, const T & default_val) const
Definition at line 40 of file smacc_state_impl.h.
    {
        return nh.param(param_name, param_val, default_val);
    }
References nh.
Referenced by cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), and cl_move_base_z::CbRotate::onEntry().
postEvent() [1/2]
template<typename EventType > void smacc::ISmaccState::postEvent
Definition at line 212 of file smacc_state_impl.h.
    {
        getStateMachine().postEvent<EventType>();
    }
References getStateMachine(), and smacc::ISmaccStateMachine::postEvent().
postEvent() [2/2]
template<typename EventType > void smacc::ISmaccState::postEvent (const EventType & ev)
Definition at line 206 of file smacc_state_impl.h.
    {
        getStateMachine().postEvent(ev);
    }
References getStateMachine(), and smacc::ISmaccStateMachine::postEvent().
Referenced by sm_viewer_sim::delayedPostEvent(), smacc::SmaccEventGenerator::postEvent(), and smacc::StateReactor::postEvent().
requiresClient()
template<typename SmaccClientType > void smacc::ISmaccState::requiresClient (SmaccClientType *& storage)
Definition at line 78 of file smacc_state_impl.h.
    {
        const char *sname = (demangleSymbol(typeid(*this).name()).c_str());
        storage = nullptr;
        auto &orthogonals = this->getStateMachine().getOrthogonals();
        for (auto &ortho : orthogonals)
        {
            ortho.second->requiresClient(storage);
            if (storage != nullptr)
                return;
        }
        ROS_ERROR("[%s] Client of type '%s' not found in any orthogonal of the current state machine. This may produce a segmentation fault if the returned reference is used.", sname, demangleSymbol<SmaccClientType>().c_str());
    }
References smacc::introspection::demangleSymbol(), smacc::ISmaccStateMachine::getOrthogonals(), and getStateMachine().
Referenced by sm_fetch_two_table_pick_n_place_1::StForwardNextTable::configureForwardBehavior(), sm_fetch_two_table_pick_n_place_1::StForwardNextTable::configureGlobalNavigation(), sm_dance_bot_strikes_back::f_pattern_states::StiFPatternStartLoop< SS >::loopCondition(), sm_dance_bot::radial_motion_states::StiRadialReturn::onExit(), sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper::onExit(), sm_fetch_six_table_pick_n_sort_1::place_states::StMovePrePlacePose::onExit(), sm_fetch_six_table_pick_n_sort_1::place_states::StPlaceRetreat::onExit(), sm_fetch_two_table_pick_n_place_1::pick_states::StCloseGripper::onExit(), sm_fetch_two_table_pick_n_place_1::place_states::StPlaceApproach::onExit(), sm_fetch_two_table_whiskey_pour::pick_states::StCloseGripper::onExit(), sm_fetch_two_table_whiskey_pour::StNavigationPosture::onExit(), sm_fetch_six_table_pick_n_sort_1::pick_states::StGraspRetreat::onExit(), sm_fetch_two_table_whiskey_pour::pick_states::StGraspRetreat::onExit(), sm_fetch_two_table_whiskey_pour::StPlaceRetreat::onExit(), sm_fetch_two_table_pick_n_place_1::SS1::SsPickObject::onMoveitError(), sm_fetch_six_table_pick_n_sort_1::place_states::StNavigationPosture::onSuccessFullExit(), sm_atomic_cb::State1::runtimeConfigure(), sm_atomic_cb::State2::runtimeConfigure(), sm_dance_bot::StNavigateForward1::runtimeConfigure(), sm_dance_bot_2::StNavigateForward1::runtimeConfigure(), sm_dance_bot_strikes_back::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_strikes_back::radial_motion_states::StiRadialEndPoint::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternForward2::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternForward4::runtimeConfigure(), sm_dance_bot_strikes_back::SS4::SsFPattern1::runtimeConfigure(), sm_dance_bot_strikes_back::SS5::SsSPattern1::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::pick_states::StGraspApproach::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::pick_states::StGraspRetreat::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::pick_states::StMovePregraspPose::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::pick_states::StNavigationPosture::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::place_states::StMovePrePlacePose::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::place_states::StNavigationPosture::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::place_states::StPlaceRetreat::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::pick_states::StGraspRetreat::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::pick_states::StMovePregraspPose::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::pick_states::StNavigationPosture::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::place_states::StMovePrePlacePose::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::place_states::StOpenGripper::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::place_states::StPlaceApproach::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::place_states::StPlaceRetreat::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::StRotate180::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::SS1::SsPickObject::runtimeConfigure(), sm_fetch_two_table_whiskey_pour::pick_states::StCloseGripper::runtimeConfigure(), sm_fetch_two_table_whiskey_pour::pick_states::StGraspApproach::runtimeConfigure(), sm_fetch_two_table_whiskey_pour::pick_states::StGraspRetreat::runtimeConfigure(), and sm_fetch_two_table_whiskey_pour::pick_states::StMovePregraspPose::runtimeConfigure().
requiresComponent()
template<typename SmaccComponentType > void smacc::ISmaccState::requiresComponent (SmaccComponentType *& storage)
Definition at line 71 of file smacc_state_impl.h.
    {
        this->getStateMachine().requiresComponent(storage);
    }
References getStateMachine(), and smacc::ISmaccStateMachine::requiresComponent().
setGlobalSMData()
template<typename T > void smacc::ISmaccState::setGlobalSMData (std::string name, T value)
Definition at line 103 of file smacc_state_impl.h.
    {
        this->getStateMachine().setGlobalSMData(name, value);
    }
References getStateMachine(), and smacc::ISmaccStateMachine::setGlobalSMData().
setParam()
template<typename T > void smacc::ISmaccState::setParam (std::string param_name, T param_val)
Definition at line 32 of file smacc_state_impl.h.
    {
        return nh.setParam(param_name, param_val);
    }
References nh.
Referenced by smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal().
Member Data Documentation
contextNh
ros::NodeHandle smacc::ISmaccState::contextNh protected
Definition at line 91 of file smacc_state.h.
Referenced by smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
eventGenerators_
std::vector<std::shared_ptr<smacc::SmaccEventGenerator> > smacc::ISmaccState::eventGenerators_ protected
Definition at line 87 of file smacc_state.h.
Referenced by createEventGenerator(), getEventGenerator(), and getEventGenerators().
nh
ros::NodeHandle smacc::ISmaccState::nh protected
Definition at line 89 of file smacc_state.h.
Referenced by smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), getParam(), getROSNode(), param(), and setParam().
parentState_
ISmaccState* smacc::ISmaccState::parentState_ protected
Definition at line 93 of file smacc_state.h.
Referenced by getParentState(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getParentState(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
stateInfo_
const smacc::introspection::SmaccStateInfo* smacc::ISmaccState::stateInfo_ protected
Definition at line 95 of file smacc_state.h.
Referenced by notifyTransitionFromTransitionTypeInfo(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
stateReactors_
std::vector<std::shared_ptr<StateReactor> > smacc::ISmaccState::stateReactors_ protected
Definition at line 86 of file smacc_state.h.
Referenced by createStateReactor(), getStateReactor(), and getStateReactors().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_state.h
smacc/include/smacc/impl/smacc_state_impl.h
smacc/src/smacc/smacc_state.cpp