SMACC: smacc::introspection::StateReactorHandler Class Reference
smacc::introspection::StateReactorHandler Class Reference
#include <smacc_state_info.h>
Public Member Functions
void configureStateReactor (std::shared_ptr< smacc::StateReactor > sr)
template<typename TEv >
void addInputEvent ()
template<typename TEv >
void setOutputEvent ()
Public Attributes
std::shared_ptr< smacc::introspection::SmaccStateReactorInfo > srInfo_
Private Attributes
std::vector< StateReactorCallbackFunctor > callbacks_
Detailed Description
Definition at line 68 of file smacc_state_info.h.
Member Function Documentation
addInputEvent()
template<typename TEv > void smacc::introspection::StateReactorHandler::addInputEvent
Definition at line 66 of file smacc_state_reactor_impl.h.
{
    StateReactorCallbackFunctor functor;
    functor.fn = [=](std::shared_ptr<smacc::StateReactor> sr) {
        ROS_INFO("[%s] State Reactor adding input event: %s", demangleType(srInfo_->stateReactorType).c_str(), demangledTypeName<TEv>().c_str());
        sr->addInputEvent<TEv>();
    };
    this->callbacks_.push_back(functor);
    auto evtype = TypeInfo::getFromStdTypeInfo(typeid(TEv));
    auto evinfo = std::make_shared<SmaccEventInfo>(evtype);
    EventLabel<TEv>(evinfo->label);
    srInfo_->sourceEventTypes.push_back(evinfo);
}
References callbacks_, smacc::introspection::demangleType(), smacc::introspection::StateReactorCallbackFunctor::fn, smacc::introspection::TypeInfo::getFromStdTypeInfo(), and srInfo_.
configureStateReactor()
void smacc::introspection::StateReactorHandler::configureStateReactor (std::shared_ptr< smacc::StateReactor > sr)
Definition at line 46 of file state_reactor.cpp.
{
    for (auto callback : this->callbacks_)
    {
        callback.fn(sb);
    }
}
References callback(), and callbacks_.
setOutputEvent()
template<typename TEv > void smacc::introspection::StateReactorHandler::setOutputEvent
Definition at line 84 of file smacc_state_reactor_impl.h.
{
    StateReactorCallbackFunctor functor;
    functor.fn = [=](std::shared_ptr<smacc::StateReactor> sr) {
        ROS_INFO("[%s] State Reactor setting output event: %s", demangleType(srInfo_->stateReactorType).c_str(), demangledTypeName<TEv>().c_str());
        sr->setOutputEvent<TEv>();
    };
    this->callbacks_.push_back(functor);
}
References callbacks_, smacc::introspection::demangleType(), smacc::introspection::StateReactorCallbackFunctor::fn, and srInfo_.
Member Data Documentation
callbacks_
std::vector<StateReactorCallbackFunctor> smacc::introspection::StateReactorHandler::callbacks_ private
Definition at line 71 of file smacc_state_info.h.
Referenced by addInputEvent(), configureStateReactor(), and setOutputEvent().
srInfo_
std::shared_ptr<smacc::introspection::SmaccStateReactorInfo> smacc::introspection::StateReactorHandler::srInfo_
Definition at line 82 of file smacc_state_info.h.
Referenced by addInputEvent(), and setOutputEvent().
The documentation for this class was generated from the following files:
smacc/include/smacc/introspection/smacc_state_info.h
smacc/include/smacc/impl/smacc_state_reactor_impl.h
smacc/src/smacc/state_reactor.cpp