SMACC: sm_ridgeback_barrel_search_2::OrNavigation Class Reference
sm_ridgeback_barrel_search_2::OrNavigation Class Reference
#include <or_navigation.h>
Public Member Functions
virtual void onInitialize () override
void loadWaypointsFromYaml (WaypointNavigator *waypointsNavigator)
Public Member Functions inherited from smacc::Orthogonal< OrNavigation >
std::shared_ptr< ClientHandler< OrNavigation, TClient > > createClient (TArgs... args)
Public Member Functions inherited from smacc::ISmaccOrthogonal
void setStateMachine (ISmaccStateMachine *value)
ISmaccStateMachine * getStateMachine ()
void addClientBehavior (std::shared_ptr< smacc::ISmaccClientBehavior > clientBehavior)
void runtimeConfigure ()
void onEntry ()
void onExit ()
virtual std::string getName () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
bool requiresClient (SmaccClientType *&storage)
const std::vector< std::shared_ptr< smacc::ISmaccClient > > & getClients ()
const std::vector< std::shared_ptr< smacc::ISmaccClientBehavior > > & getClientBehaviors () const
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename TClientBehavior >
TClientBehavior * getClientBehavior ()
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccOrthogonal
virtual void onInitialize ()
template<typename TOrthogonal , typename TClient >
void assignClientToOrthogonal (TClient *client)
Protected Attributes inherited from smacc::ISmaccOrthogonal
std::vector< std::shared_ptr< smacc::ISmaccClient > > clients_
Detailed Description
Definition at line 14 of file or_navigation.h.
Member Function Documentation
loadWaypointsFromYaml()
void sm_ridgeback_barrel_search_2::OrNavigation::loadWaypointsFromYaml (WaypointNavigator * waypointsNavigator) inline
Definition at line 38 of file or_navigation.h.
        {
            // if it is the first time and the waypoints navigator is not configured
            std::string planfilepath;
            ros::NodeHandle nh("~");
            if (nh.getParam("waypoints_plan", planfilepath))
            {
                ROS_INFO("Loaded waypoints path file: %s", planfilepath.c_str());
                waypointsNavigator->loadWayPointsFromFile(planfilepath);
            }
            else
            {
                ROS_ERROR("Error while loading waypoints_path file: not found");
            }
        }
References cl_move_base_z::WaypointNavigator::loadWayPointsFromFile().
Referenced by onInitialize().
onInitialize()
virtual void sm_ridgeback_barrel_search_2::OrNavigation::onInitialize () inline override virtual
Reimplemented from smacc::ISmaccOrthogonal.
Definition at line 17 of file or_navigation.h.
        {
            auto movebaseClient = this->createClient<ClMoveBaseZ>();
            movebaseClient->initialize();
            movebaseClient->createComponent<Pose>();
            // create planner switcher
            movebaseClient->createComponent<PlannerSwitcher>();
            // create odom tracker
            movebaseClient->createComponent<cl_move_base_z::odom_tracker::OdomTracker>();
            // create waypoints navigator component
            auto waypointsNavigator = movebaseClient->createComponent<WaypointNavigator>();
            loadWaypointsFromYaml(waypointsNavigator);
            // change this to skip some points of the yaml file, default = 0
            // waypointsNavigator->currentWaypoint_ = 3;
        }
References loadWaypointsFromYaml().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_ridgeback_barrel_search_2/include/sm_ridgeback_barrel_search_2/orthogonals/or_navigation.h