SMACC: smacc::ISmaccClient Class Reference
smacc::ISmaccClient Class Reference
#include <smacc_client.h>
Public Member Functions
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Protected Member Functions
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Protected Attributes
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Private Attributes
ISmaccStateMachine * stateMachine_
ISmaccOrthogonal * orthogonal_
Friends
class ISmaccOrthogonal
class ISmaccComponent
Detailed Description
Definition at line 36 of file smacc_client.h.
Constructor & Destructor Documentation
ISmaccClient()
smacc::ISmaccClient::ISmaccClient ()
Definition at line 13 of file client.cpp.
{
}
~ISmaccClient()
smacc::ISmaccClient::~ISmaccClient () virtual
Definition at line 17 of file client.cpp.
{
}
Member Function Documentation
connectSignal()
template<typename TSmaccSignal , typename T > void smacc::ISmaccClient::connectSignal (TSmaccSignal & signal, void(T::*)() callback, T * object)
Definition at line 96 of file smacc_client_impl.h.
    {
        return this->getStateMachine()->createSignalConnection(signal, callback, object);
    }
References callback(), smacc::ISmaccStateMachine::createSignalConnection(), and getStateMachine().
createComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs> SmaccComponentType * smacc::ISmaccClient::createComponent (TArgs... targs) protected
Definition at line 90 of file smacc_client_impl.h.
    {
        return this->createNamedComponent<SmaccComponentType, TOrthogonal, TClient>(std::string(), targs...);
    }
Referenced by smacc::ClientHandler< TOrthogonal, TClient >::createComponent(), and smacc::ISmaccComponent::createSiblingComponent().
createNamedComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs> SmaccComponentType * smacc::ISmaccClient::createNamedComponent (std::string name, TArgs... targs) protected
Definition at line 57 of file smacc_client_impl.h.
    {
        ComponentKey componentkey(&typeid(SmaccComponentType), name);
        std::shared_ptr<SmaccComponentType> ret;
        auto it = this->components_.find(componentkey);
        if (it == this->components_.end())
        {
            auto tname = demangledTypeName<SmaccComponentType>();
            ROS_DEBUG("%s smacc component is required. Creating a new instance.", tname.c_str());
            ret = std::shared_ptr<SmaccComponentType>(new SmaccComponentType(targs...));
            ret->setStateMachine(this->getStateMachine());
            ret->owner_ = this;
            ret->initialize(this);
            this->components_[componentkey] = ret; //std::dynamic_pointer_cast<smacc::ISmaccComponent>(ret);
            ROS_DEBUG("%s resource is required. Done.", tname.c_str());
        }
        else
        {
            ROS_DEBUG("%s resource is required. Found resource in cache.", demangledTypeName<SmaccComponentType>().c_str());
            ret = dynamic_pointer_cast<SmaccComponentType>(it->second);
        }
        ret->template onOrthogonalAllocation<TOrthogonal, TClient>();
        return ret.get();
    }
References components_, and getStateMachine().
Referenced by smacc::ClientHandler< TOrthogonal, TClient >::createNamedComponent(), and smacc::ISmaccComponent::createSiblingNamedComponent().
getComponent() [1/2]
template<typename TComponent > TComponent * smacc::ISmaccClient::getComponent
Definition at line 27 of file smacc_client_impl.h.
    {
        return this->getComponent<TComponent>(std::string());
    }
Referenced by sm_fetch_two_table_pick_n_place_1::StForwardNextTable::configureForwardBehavior(), sm_fetch_two_table_pick_n_place_1::StForwardNextTable::configureGlobalNavigation(), sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::decidePlacePose(), sm_fetch_screw_loop_1::cl_perception_system::ClPerceptionSystem::decidePlacePose(), sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::decidePlacePose(), sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::decidePlacePose(), cl_move_base_z::CbNavigateGlobalPosition::execute(), sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::getCurrentTable(), sm_dance_bot_strikes_back::f_pattern_states::StiFPatternStartLoop< SS >::loopCondition(), cl_move_base_z::CbNavigateGlobalPosition::onEntry(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_move_base_z::CbNavigateNextWaypoint::onEntry(), cl_move_base_z::CbRotate::onEntry(), cl_move_base_z::CbUndoPathBackwards::onEntry(), cl_move_base_z::CbUndoPathBackwards2::onEntry(), sm_dance_bot::radial_motion_states::StiRadialReturn::onExit(), cl_move_base_z::CbUndoPathBackwards::onExit(), cl_move_base_z::CbUndoPathBackwards2::onExit(), smacc::ISmaccComponent::requiresComponent(), sm_dance_bot_strikes_back::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_strikes_back::radial_motion_states::StiRadialEndPoint::runtimeConfigure(), sm_dance_bot_strikes_back::SS4::SsFPattern1::runtimeConfigure(), sm_dance_bot_strikes_back::SS5::SsSPattern1::runtimeConfigure(), sm_fetch_two_table_pick_n_place_1::StRotate180::runtimeConfigure(), cl_move_base_z::WaypointNavigator::sendNextGoal(), and sm_fetch_six_table_pick_n_sort_1::StNavigationTableRetreat::staticConfigure().
getComponent() [2/2]
template<typename TComponent > TComponent * smacc::ISmaccClient::getComponent (std::string name)
Definition at line 33 of file smacc_client_impl.h.
    {
        for (auto &component : components_)
        {
            if (component.first.name != name)
                continue;
            auto *tcomponent = dynamic_cast<TComponent *>(component.second.get());
            if (tcomponent != nullptr)
            {
                return tcomponent;
            }
        }
        return nullptr;
    }
References components_.
getComponents()
void smacc::ISmaccClient::getComponents (std::vector< std::shared_ptr< ISmaccComponent > > & components)
Definition at line 26 of file client.cpp.
{
    for (auto &ce : components_)
    {
        components.push_back(ce.second);
    }
}
References components_.
getName()
std::string smacc::ISmaccClient::getName () const virtual
Reimplemented in cl_move_base_z::ClMoveBaseZ, sm_dance_bot::cl_led::ClLED, sm_dance_bot_2::cl_led::ClLED, sm_dance_bot_strikes_back::cl_led::ClLED, sm_fetch_screw_loop_1::cl_gripper::ClGripper, sm_fetch_six_table_pick_n_sort_1::cl_gripper::ClGripper, sm_fetch_two_table_pick_n_place_1::cl_gripper::ClGripper, and sm_fetch_two_table_whiskey_pour::cl_gripper::ClGripper.
Definition at line 34 of file client.cpp.
{
    std::string keyname = demangleSymbol(typeid(*this).name());
    return keyname;
}
References smacc::introspection::demangleSymbol().
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::cancelGoal(), smacc::client_bases::SmaccPublisherClient::configure(), smacc::client_bases::SmaccSubscriberClient< MessageType >::initialize(), smacc::client_bases::SmaccServiceClient< ServiceType >::initialize(), smacc::client_bases::SmaccServiceServerClient< TService >::initialize(), cl_microstrain_mips::ClMicrostainMips::initialize(), smacc::client_bases::SmaccActionClientBase< ActionType >::onResult(), and smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
getStateMachine()
ISmaccStateMachine * smacc::ISmaccClient::getStateMachine () inline
Definition at line 51 of file smacc_client_impl.h.
    {
        return this->stateMachine_;
    }
References stateMachine_.
Referenced by connectSignal(), createNamedComponent(), smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted(), smacc::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived(), cl_keyboard::ClKeyboard::OnKeyPress(), smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout(), cl_move_group_interface::ClMoveGroup::onMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::onMotionExecutionSuccedded(), smacc::client_bases::SmaccActionClientBase< ActionType >::onPreempted(), smacc::client_bases::SmaccActionClientBase< ActionType >::onRejected(), smacc::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived(), smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), and cl_ros_timer::ClRosTimer::onTimerTick().
getType()
smacc::introspection::TypeInfo::Ptr smacc::ISmaccClient::getType () virtual
Definition at line 50 of file client.cpp.
{
    return smacc::introspection::TypeInfo::getFromStdTypeInfo(typeid(*this));
}
References smacc::introspection::TypeInfo::getFromStdTypeInfo().
initialize()
void smacc::ISmaccClient::initialize () virtual
Reimplemented in smacc::client_bases::SmaccSubscriberClient< MessageType >, smacc::client_bases::SmaccSubscriberClient< sensor_msgs::BatteryState >, smacc::client_bases::SmaccSubscriberClient< std_msgs::UInt16 >, smacc::client_bases::SmaccSubscriberClient< sensor_msgs::LaserScan >, smacc::client_bases::SmaccSubscriberClient< sensor_msgs::Temperature >, smacc::client_bases::SmaccSubscriberClient< std_msgs::Float32 >, smacc::client_bases::SmaccSubscriberClient< std_msgs::Int32 >, smacc::client_bases::SmaccSubscriberClient< TMsg >, cl_ros_timer::ClRosTimer, smacc::client_bases::SmaccActionClientBase< ActionType >, smacc::client_bases::SmaccActionClientBase< move_base_msgs::MoveBaseAction >, smacc::client_bases::SmaccActionClientBase< sm_dance_bot::LEDControlAction >, smacc::client_bases::SmaccActionClientBase< sm_dance_bot_2::LEDControlAction >, smacc::client_bases::SmaccActionClientBase< sm_dance_bot_strikes_back::LEDControlAction >, smacc::client_bases::SmaccActionClientBase< control_msgs::GripperCommandAction >, smacc::client_bases::SmaccServiceClient< ServiceType >, smacc::client_bases::SmaccServiceClient< std_srvs::Empty >, smacc::client_bases::SmaccServiceClient< std_srvs::SetBool >, smacc::client_bases::SmaccServiceServerClient< TService >, smacc::client_bases::SmaccServiceServerClient< std_srvs::Empty >, cl_keyboard::ClKeyboard, cl_microstrain_mips::ClMicrostainMips, cl_move_base_z::ClMoveBaseZ, cl_multirole_sensor::ClMultiroleSensor< MessageType >, cl_multirole_sensor::ClMultiroleSensor< sensor_msgs::LaserScan >, and cl_multirole_sensor::ClMultiroleSensor< sensor_msgs::Temperature >.
Definition at line 21 of file client.cpp.
{
}
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc::ISmaccClient::onOrthogonalAllocation () inline protected
Definition at line 75 of file smacc_client.h.
{}
postEvent() [1/2]
template<typename EventType > void smacc::ISmaccClient::postEvent
Definition at line 21 of file smacc_client_impl.h.
    {
        stateMachine_->postEvent<EventType>();
    }
References smacc::ISmaccStateMachine::postEvent(), and stateMachine_.
Referenced by smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), smacc::client_bases::SmaccSubscriberClient< MessageType >::onOrthogonalAllocation(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onOrthogonalAllocation(), and smacc::client_bases::SmaccActionClientBase< ActionType >::postResultEvent().
postEvent() [2/2]
template<typename EventType > void smacc::ISmaccClient::postEvent (const EventType & ev)
Definition at line 15 of file smacc_client_impl.h.
    {
        stateMachine_->postEvent(ev);
    }
References smacc::ISmaccStateMachine::postEvent(), and stateMachine_.
requiresClient()
template<typename SmaccClientType > void smacc::ISmaccClient::requiresClient (SmaccClientType *& storage)
Definition at line 102 of file smacc_client_impl.h.
    {
        this->orthogonal_->requiresClient(storage);
    }
References orthogonal_, and smacc::ISmaccOrthogonal::requiresClient().
Referenced by sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::decidePlacePose(), sm_fetch_screw_loop_1::cl_perception_system::ClPerceptionSystem::decidePlacePose(), sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::decidePlacePose(), sm_fetch_two_table_whiskey_pour::cl_perception_system::ClPerceptionSystem::decidePlacePose(), sm_fetch_two_table_pick_n_place_1::cl_perception_system::ClPerceptionSystem::getCurrentTable(), smacc::ISmaccComponent::requiresClient(), sm_fetch_six_table_pick_n_sort_1::StNavigateToDestinyTable::runtimeConfigure(), sm_fetch_six_table_pick_n_sort_1::StNavigateToSourceTable::runtimeConfigure(), sm_fetch_two_table_whiskey_pour::StBringBottleBackNavigateSourceTable::runtimeConfigure(), sm_fetch_two_table_whiskey_pour::StNavigateToDestinyTable::runtimeConfigure(), sm_fetch_two_table_whiskey_pour::StNavigateToSourceTable::runtimeConfigure(), and sm_fetch_six_table_pick_n_sort_1::StNavigationTableRetreat::staticConfigure().
setOrthogonal()
void smacc::ISmaccClient::setOrthogonal (ISmaccOrthogonal * orthogonal) protected
Definition at line 45 of file client.cpp.
{
    orthogonal_ = orthogonal;
}
References orthogonal_.
setStateMachine()
void smacc::ISmaccClient::setStateMachine (ISmaccStateMachine * stateMachine) protected
Definition at line 40 of file client.cpp.
{
    stateMachine_ = stateMachine;
}
References stateMachine_.
Friends And Related Function Documentation
ISmaccComponent
friend class ISmaccComponent friend
Definition at line 97 of file smacc_client.h.
ISmaccOrthogonal
friend class ISmaccOrthogonal friend
Definition at line 96 of file smacc_client.h.
Member Data Documentation
components_
std::map<ComponentKey, std::shared_ptr<smacc::ISmaccComponent> > smacc::ISmaccClient::components_ protected
Definition at line 78 of file smacc_client.h.
Referenced by createNamedComponent(), getComponent(), and getComponents().
orthogonal_
ISmaccOrthogonal* smacc::ISmaccClient::orthogonal_ private
Definition at line 94 of file smacc_client.h.
Referenced by requiresClient(), and setOrthogonal().
stateMachine_
ISmaccStateMachine* smacc::ISmaccClient::stateMachine_ private
Definition at line 93 of file smacc_client.h.
Referenced by getStateMachine(), postEvent(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_client.h
smacc/include/smacc/impl/smacc_client_impl.h
smacc/src/smacc/client.cpp