SMACC: sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem Class Reference
sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem Class Reference
#include <cl_perception_system.h>
Public Member Functions
ClPerceptionSystem ()
virtual ~ClPerceptionSystem ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
geometry_msgs::PoseStamped getMainTablePose ()
geometry_msgs::PoseStamped getTargetTablePose ()
void printCubesState ()
CubeInfo * nextCube ()
virtual void update () override
CubeInfo * getTargetCurrentCubeInfo ()
bool decidePickCubePose (geometry_msgs::PoseStamped &out)
bool decidePlacePose (geometry_msgs::PoseStamped &placePose)
void computePregraspPoseFromCubePose (geometry_msgs::PoseStamped &objectPose)
bool decidePrePlacePose (geometry_msgs::PoseStamped &preplacePose)
void computePlaceCubeGraspingOrientation (geometry_msgs::PoseStamped &objectPose)
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void initialize ()
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
Public Member Functions inherited from smacc::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (ros::Duration duration)
void executeUpdate ()
void setUpdatePeriod (ros::Duration duration)
Public Attributes
int decissionsCount
int currentCube = 0
CpSceneState * sceneState_
CpSimulatedGazeboPerception * gazeboPerceptionSimulation_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
virtual void update ()=0
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Detailed Description
Definition at line 19 of file cl_perception_system.h.
Constructor & Destructor Documentation
ClPerceptionSystem()
sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::ClPerceptionSystem () inline
Definition at line 30 of file cl_perception_system.h.
            {
                decissionsCount = 0;
            }
References decissionsCount.
~ClPerceptionSystem()
virtual sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::~ClPerceptionSystem () inline virtual
Definition at line 35 of file cl_perception_system.h.
            {
            }
Member Function Documentation
computePlaceCubeGraspingOrientation()
void sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::computePlaceCubeGraspingOrientation (geometry_msgs::PoseStamped & objectPose) inline
Definition at line 206 of file cl_perception_system.h.
            {
                // ------ cube grasping orientation -------
                // grasp the object with the gripper using top-to-bottom direction
                auto cubeYawOnTable = tf::getYaw(objectPose.pose.orientation);
                const double degrees90 = M_PI / 2;
                while (cubeYawOnTable > degrees90)
                {
                    cubeYawOnTable -= degrees90;
                }
                while (cubeYawOnTable < -degrees90)
                {
                    cubeYawOnTable += degrees90;
                }
                ROS_INFO("[ClPerceptionSystem] cube yaw: %lf", cubeYawOnTable);
                auto quat = tf::createQuaternionFromRPY(0, M_PI / 2, cubeYawOnTable);
                tf::quaternionTFToMsg(quat, objectPose.pose.orientation);
            }
Referenced by decidePrePlacePose().
computePregraspPoseFromCubePose()
void sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::computePregraspPoseFromCubePose (geometry_msgs::PoseStamped & objectPose) inline
Definition at line 166 of file cl_perception_system.h.
            {
                objectPose.pose.position.x -= 0;
                objectPose.pose.position.z += 0.3;
                // ------ cube grasping orientation -------
                // grasp the object with the gripper using top-to-bottom direction
                auto cubeYawOnTable = tf::getYaw(objectPose.pose.orientation);
                const double degrees90 = M_PI / 2;
                while (cubeYawOnTable > degrees90)
                {
                    cubeYawOnTable -= degrees90;
                }
                while (cubeYawOnTable < -degrees90)
                {
                    cubeYawOnTable += degrees90;
                }
                ROS_INFO("cube yaw: %lf", cubeYawOnTable);
                auto quat = tf::createQuaternionFromRPY(0, M_PI / 2, cubeYawOnTable);
                tf::quaternionTFToMsg(quat, objectPose.pose.orientation);
            }
Referenced by sm_fetch_six_table_pick_n_sort_1::pick_states::StMovePregraspPose::runtimeConfigure().
decidePickCubePose()
bool sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::decidePickCubePose (geometry_msgs::PoseStamped & out) inline
Definition at line 110 of file cl_perception_system.h.
            {
                // we select here the first cube in the list that is located in the
                // origin table
                auto *c = this->getTargetCurrentCubeInfo();
                if (c != nullptr)
                {
                    out = c->pose_->toPoseStampedMsg();
                    return true;
                }
                else
                {
                    return false;
                }
            }
References getTargetCurrentCubeInfo().
Referenced by sm_fetch_six_table_pick_n_sort_1::pick_states::StMovePregraspPose::runtimeConfigure().
decidePlacePose()
bool sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::decidePlacePose (geometry_msgs::PoseStamped & placePose) inline
Definition at line 129 of file cl_perception_system.h.
            {
                auto *c = this->getTargetCurrentCubeInfo();
                ClMoveBaseZ *moveBaseClient;
                this->requiresClient(moveBaseClient);
                if (c != nullptr && moveBaseClient != nullptr)
                {
                    auto basepose = moveBaseClient->getComponent<Pose>()->toPoseMsg();
                    auto dstTablePose = c->dstTableInfo_->pose_->toPoseStampedMsg();
                    placePose.pose.position.z = 0.7;
                    if (basepose.position.x < dstTablePose.pose.position.x)
                    {
                        placePose.pose.position.x = dstTablePose.pose.position.x - 0.25;
                        placePose.pose.position.y = dstTablePose.pose.position.y + 0.1;
                    }
                    else
                    {
                        placePose.pose.position.x = dstTablePose.pose.position.x + 0.25;
                        placePose.pose.position.y = dstTablePose.pose.position.y + -0.1;
                    }
                    placePose.pose.position.y += -c->dstTableInfo_->cubesCounter_ * 0.1;
                    placePose.pose.orientation.w = 1;
                    placePose.header.frame_id = dstTablePose.header.frame_id;
                    placePose.header.stamp = dstTablePose.header.stamp;
                    return true;
                }
                return false;
            }
References smacc::ISmaccClient::getComponent(), getTargetCurrentCubeInfo(), and smacc::ISmaccClient::requiresClient().
Referenced by decidePrePlacePose().
decidePrePlacePose()
bool sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::decidePrePlacePose (geometry_msgs::PoseStamped & preplacePose) inline
Definition at line 191 of file cl_perception_system.h.
            {
                if (this->decidePlacePose(preplacePose))
                {
                    ROS_INFO_STREAM("[ClPerceptionSystem] Decided pre place pose for cube: " << preplacePose);
                    preplacePose.pose.position.x -= 0;
                    preplacePose.pose.position.z += 0.3;
                    computePlaceCubeGraspingOrientation(preplacePose);
                    return true;
                }
                return false;
            }
References computePlaceCubeGraspingOrientation(), and decidePlacePose().
Referenced by sm_fetch_six_table_pick_n_sort_1::place_states::StMovePrePlacePose::runtimeConfigure().
getMainTablePose()
geometry_msgs::PoseStamped sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::getMainTablePose () inline
Definition at line 50 of file cl_perception_system.h.
            {
                for (auto &table : this->sceneState_->tablesInfo_)
                {
                    if (table.associatedCubeColor_ == "none")
                    {
                        return table.pose_->toPoseStampedMsg();
                    }
                }
                geometry_msgs::PoseStamped empty;
                return empty;
            }
References sm_fetch_six_table_pick_n_sort_1::cl_perception_system::CpSceneState::tablesInfo_.
getTargetCurrentCubeInfo()
CubeInfo * sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::getTargetCurrentCubeInfo () inline
Definition at line 97 of file cl_perception_system.h.
            {
                for (auto &c : this->sceneState_->cubeInfos_)
                {
                    if (c.location_ == CubeLocation::ORIGIN_TABLE)
                    {
                        return &c;
                    }
                }
                return nullptr;
            }
References sm_fetch_six_table_pick_n_sort_1::cl_perception_system::CpSceneState::cubeInfos_, and sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ORIGIN_TABLE.
Referenced by decidePickCubePose(), decidePlacePose(), getTargetTablePose(), nextCube(), and sm_fetch_six_table_pick_n_sort_1::pick_states::StCloseGripper::runtimeConfigure().
getTargetTablePose()
geometry_msgs::PoseStamped sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::getTargetTablePose () inline
Definition at line 64 of file cl_perception_system.h.
            {
                auto currentCube = getTargetCurrentCubeInfo();
                return currentCube->dstTableInfo_->pose_->toPoseStampedMsg();
            }
References currentCube, and getTargetCurrentCubeInfo().
nextCube()
CubeInfo * sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::nextCube () inline
Definition at line 83 of file cl_perception_system.h.
            {
                auto currentCube = getTargetCurrentCubeInfo();
                currentCube->location_ = CubeLocation::DESTINY_TABLE;
                currentCube->dstTableInfo_->cubesCounter_++;
                printCubesState();
                return getTargetCurrentCubeInfo();
            }
References currentCube, sm_fetch_six_table_pick_n_sort_1::cl_perception_system::DESTINY_TABLE, getTargetCurrentCubeInfo(), and printCubesState().
Referenced by sm_fetch_six_table_pick_n_sort_1::place_states::StNavigationPosture::onSuccessFullExit().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::onOrthogonalAllocation () inline
Definition at line 40 of file cl_perception_system.h.
            {
                const int TABLE_COUNT = 6;
                const int CUBE_COUNT = 10;
                // order matters, since gazeboPerception updates sceneState
                sceneState_ = this->createComponent<CpSceneState, TSourceObject, TOrthogonal>(CUBE_COUNT, TABLE_COUNT);
                gazeboPerceptionSimulation_ = this->createComponent<CpSimulatedGazeboPerception, TSourceObject, TOrthogonal>();
            }
References sm_fetch_two_table_whiskey_pour::CUBE_COUNT, gazeboPerceptionSimulation_, sceneState_, and sm_fetch_two_table_whiskey_pour::TABLE_COUNT.
printCubesState()
void sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::printCubesState () inline
Definition at line 70 of file cl_perception_system.h.
            {
                std::stringstream ss;
                int i = 0;
                for (auto &c : this->sceneState_->cubeInfos_)
                {
                    ss << "- Cube " << i++ << " frame: " << c.pose_->toPoseStampedMsg().header.frame_id << " location: " << (c.location_ == CubeLocation::ORIGIN_TABLE ? " origin table" : " destination table" )<< std::endl;
                }
                ROS_INFO_STREAM(ss.str());
            }
References sm_fetch_six_table_pick_n_sort_1::cl_perception_system::CpSceneState::cubeInfos_, and sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ORIGIN_TABLE.
Referenced by nextCube().
update()
virtual void sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::update () inline override virtual
Implements smacc::ISmaccUpdatable.
Definition at line 93 of file cl_perception_system.h.
            {
            }
Member Data Documentation
currentCube
int sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::currentCube = 0
Definition at line 24 of file cl_perception_system.h.
Referenced by getTargetTablePose(), and nextCube().
decissionsCount
int sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::decissionsCount
Definition at line 23 of file cl_perception_system.h.
Referenced by ClPerceptionSystem().
gazeboPerceptionSimulation_
CpSimulatedGazeboPerception* sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::gazeboPerceptionSimulation_
Definition at line 28 of file cl_perception_system.h.
Referenced by onOrthogonalAllocation().
sceneState_
CpSceneState* sm_fetch_six_table_pick_n_sort_1::cl_perception_system::ClPerceptionSystem::sceneState_
Definition at line 27 of file cl_perception_system.h.
Referenced by sm_fetch_six_table_pick_n_sort_1::cl_move_group_interface::CpConstraintTableWorkspaces::onInitialize(), and onOrthogonalAllocation().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_fetch_six_table_pick_n_sort_1/include/sm_fetch_six_table_pick_n_sort_1/clients/perception_system_client/cl_perception_system.h