SMACC: sm_atomic_cb::State1 Struct Reference
sm_atomic_cb::State1 Struct Reference
#include <st_state_1.h>
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, State2, SUCCESS > > reactions
Public Types inherited from smacc::SmaccState< State1, SmAtomicCB >
typedef SmAtomicCB TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef mpl::list<> LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
void runtimeConfigure ()
void onTimerClientTickCallback ()
void onRepeatBehaviorTickCallback ()
void onSingleBehaviorTickCallback ()
Public Member Functions inherited from smacc::SmaccState< State1, SmAtomicCB >
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc::introspection::SmaccStateInfo * getStateInfo ()
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
bool getGlobalSMData (std::string name, T &ret)
void setGlobalSMData (std::string name, T value)
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc::ISmaccState
virtual ISmaccStateMachine & getStateMachine ()=0
ISmaccState * getParentState ()
ros::NodeHandle & getROSNode ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
template<typename T >
bool param (std::string param_name, T &param_val, const T &default_val) const
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Static Public Member Functions
static void staticConfigure ()
Static Public Member Functions inherited from smacc::SmaccState< State1, SmAtomicCB >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, State1 &)> initializationFunction)
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
static void configure_orthogonal (Args &&... args)
static std::shared_ptr< smacc::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
static std::shared_ptr< smacc::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
static std::shared_ptr< smacc::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Additional Inherited Members
Public Attributes inherited from smacc::SmaccState< State1, SmAtomicCB >
bool finishStateThrown
mpl::list<> * smacc_inner_type
Protected Attributes inherited from smacc::ISmaccState
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc::SmaccEventGenerator > > eventGenerators_
ros::NodeHandle nh
ros::NodeHandle contextNh
ISmaccState * parentState_
const smacc::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 9 of file st_state_1.h.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, State2, SUCCESS> > sm_atomic_cb::State1::reactions
Definition at line 18 of file st_state_1.h.
Member Function Documentation
onRepeatBehaviorTickCallback()
void sm_atomic_cb::State1::onRepeatBehaviorTickCallback () inline
Definition at line 59 of file st_state_1.h.
    {
        ROS_INFO("repeat behavior tick!");
    }
Referenced by runtimeConfigure().
onSingleBehaviorTickCallback()
void sm_atomic_cb::State1::onSingleBehaviorTickCallback () inline
Definition at line 65 of file st_state_1.h.
    {
        ROS_INFO("single behavior tick!");
    }
Referenced by runtimeConfigure().
onTimerClientTickCallback()
void sm_atomic_cb::State1::onTimerClientTickCallback () inline
Definition at line 53 of file st_state_1.h.
    {
        ROS_INFO("timer client tick!");
    }
Referenced by runtimeConfigure().
runtimeConfigure()
void sm_atomic_cb::State1::runtimeConfigure () inline
Definition at line 28 of file st_state_1.h.
    {
        // get reference to the client
        ClRosTimer *client;
        this->requiresClient(client);
        // subscribe to the timer client callback
        client->onTimerTick(&State1::onTimerClientTickCallback, this);
        // getting reference to the repeat countdown behavior
        auto *cbrepeat = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownLoop>();
        // subscribe to the repeat countdown behavior callback
        cbrepeat->onTimerTick(&State1::onRepeatBehaviorTickCallback, this);
        // getting reference to the single countdown behavior
        auto *cbsingle = this->getOrthogonal<OrTimer>()
                             ->getClientBehavior<CbTimerCountdownOnce>();
        // subscribe to the single countdown behavior callback
        cbsingle->onTimerTick(&State1::onSingleBehaviorTickCallback, this);
    }
References onRepeatBehaviorTickCallback(), onSingleBehaviorTickCallback(), onTimerClientTickCallback(), cl_ros_timer::ClRosTimer::onTimerTick(), cl_ros_timer::CbTimerCountdownLoop::onTimerTick(), cl_ros_timer::CbTimerCountdownOnce::onTimerTick(), and smacc::ISmaccState::requiresClient().
staticConfigure()
static void sm_atomic_cb::State1::staticConfigure () inline static
Definition at line 22 of file st_state_1.h.
    {
        configure_orthogonal<OrTimer, CbTimerCountdownLoop>(3);  // EvTimer triggers each 3 client ticks
        configure_orthogonal<OrTimer, CbTimerCountdownOnce>(5); // EvTimer triggers once at 10 client ticks
    }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_atomic_cb/include/sm_atomic_cb/states/st_state_1.h